### ISSUE TITLE
Do we need to mount on the DOM?

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#10]
https://github.com/vuejs/vue-test-utils-next/blob/a66d8bcc09e85e5f8d977cfd2b53e705337a9134/src/mount.ts#L56

`createApp(...).mount` requires a real DOM element from what I can see - I'm not sure how VTU beta handled this, but I believe the default was NOT to mount on the dom, since we had an `attachToDocument` option.

We are currently tightly coupled to the DOM - not ideal, but I think it's fine for a pre alpha.

**Comment by lmiller1990** [comment]
@LinusBorg suggested we just mount on an element that is not on the DOM for now; this seems better than what we currently do, which is nuking the entire `document.outerHTML` every time we run the tests.

Let's do that for now. I am guessing this is what Vue 2 was internally as well.

**Comment by LinusBorg** [comment]
> I am guessing this is what Vue 2 was internally as well if you didn't pass an element to $mount.

Did a quick check - seems that in Vue 2, mount could indeed work without an element to mount to.

https://github.com/vuejs/vue/blob/e1fbfac66403aa0df5cdae040a8edf2f219455ca/src/core/instance/lifecycle.js#L143

**Comment by lmiller1990** [comment]
Going to close this for now - we have a pretty good solution where we mount on an element on in the DOM as of [this commit](https://github.com/vuejs/vue-test-utils-next/commit/b7b6254b1d2783f566a97823a5f85b12beeb3bf7) so we are not blowing up any potentially pre-existing state, which matches the VTU beta API.

If this turns out to be a problem (eg performance) we can look more deeply into how this was handled in Vue 2.
