### ISSUE TITLE
Add a few tests for Functional Components

### ISSUE THREAD

**Issue by dobromir-hristov** [vuejs/vue-test-utils-next#103]
I think we are lacking tests for functional components. Those types of components resemble allot more statefull components now.

A functional component signature is now - https://github.com/vuejs/rfcs/blob/master/active-rfcs/0031-attr-fallthrough.md#functional-components

```js
const Component = (props, { slots, attrs, emit }) => h('div', { class: ['a'] }, slots)

Component.props = { /*...*/ }
Component.inheritAttrs = false
Component.displayName = 'FunctionalComponent'
```

I can take this over and try to add test cases on as many places as I can.

We also need to test asyncFunctionalComponents - https://github.com/vuejs/rfcs/blob/async-component/active-rfcs/0026-async-component-api.md

**Comment by lmiller1990** [comment]
We also haven't got anything for `defineAsyncComponent`, either. IIRC this had some weird bugs in beta, we should test it. One common case is loading routes/pages async.

**Comment by lmiller1990** [comment]
We have #187 and #158 relating to bugs in functional components, so I will close this.
