### ISSUE TITLE
FR: Add replacement options for html output.

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [vuejs/vue-test-utils-next#1057]
Some vue frameworks use fancy dynamic generated values for matching for/id elements of input elements. it would be cool if that could be somehow made static to trick .toMatchSnapshot to report every time a test is run. the property matcher in jest only works with actual properties like in json.

**Comment by lmiller1990** [comment]
I don't fully understand what you are asking for. Are you suggesting a custom [snapshot serializer](https://jestjs.io/docs/configuration#snapshotserializers-arraystring)? [There was one for Vue 2 and Jest](https://www.npmjs.com/package/jest-serializer-vue-tjw), I'm not sure if it's ported to Vue 3.

This seems like a Jest specific feature request; I think this would be nice to have, but it's outside the scope of this particular project.

**Comment by sschneider-ihre-pvs** [comment]
It's more like a request to have replacement options for html attributes in the wrapper.html() for example
it is hard to tell wether it is a snapshot or a wrapper thing to me.

**Comment by lmiller1990** [comment]
Please help me clarify for my understanding - what do you mean by replacement options?

Maybe you could provide an example of what you get now in your snapshot, and what you'd like to get.

**Comment by sschneider-ihre-pvs** [comment]
let me try. Assume you have an input component that comes packaged with an input and label tag. for convenience the label gets a `for` attribute and the input an `id` attribute with a generated uuid. Now it would be cool if either a regex or a simple attributename value replacement could be in option in the .html() function.

```html
<label for="6b6f076e-5e8e-47df-a374-6ac8c8ceab4d">
<input id="6b6f076e-5e8e-47df-a374-6ac8c8ceab4d" type="text">
```
For snapshots this is pretty annoying when the id changes every time. So my idea was having something like
```js
wrapper.html({
  replace: {
    for: 'foo',
    id: 'foo'
  }
})
```
to make certain attributes static.

**Comment by afontcu** [comment]
Hi!  👋  I think your current solution is good (and smart!) enough, and given that there's a userland valid solution, I don't think adding/documenting/maintaining a new feature is worth it.

**Comment by lmiller1990** [comment]
I agree. Also, Jest has a very flexible custom snapshot API - you could definitely build this using it. I think that makes more sense - I'd prefer to only add features to VTU that are useful for all runners, not Jest specific.

If you do make a custom snapshot serializer for Jest, please share it! We could add a link to the docs.
