### ISSUE TITLE
can we have a `createElementWrapper` method?

### ISSUE THREAD

**Issue by wxsms** [vuejs/vue-test-utils-next#1095]
while building component lib or using teleport feature of Vue3, the HTML element sometimes goes out of the component. Although we can use `getComponent` to access it by VNode & component, but we don't want to always abstract anything into a component.

Therefore, it can be better if there's a function works like:

```js
const wrapper = createElementWrapper(document.querySelector('.something'))
```

So I can still use the query or trigger features provided by VTU.

**Comment by lmiller1990** [comment]
Would this be a better solution? As for rc.17 you can stub teleport and test your component like usual: https://github.com/vuejs/vue-test-utils-next/issues/798#issuecomment-974969774

If this won't work, please share a minimal test and we can explore some other solutions.

**Comment by wxsms** [comment]
Thanks. It works great.
