### ISSUE TITLE
What would be the best approach to test errors that are thrown by components?

### ISSUE THREAD

**Issue by sevilyilmaz** [vuejs/vue-test-utils-next#1096]
In version `1.x`, I used to use [this approach](https://github.com/vuejs/vue-test-utils/issues/641#issuecomment-443651405) to test errors that are thrown by components. But if I follow the same approach Vue complains about unhandled errors.

```
console.warn
    [Vue warn]: Unhandled error during execution of setup function 
      at <BuiStack ref="VTU_COMPONENT" > 
      at <VTUROOT>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6482:17)
      at logError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6656:9)
      at handleError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6648:5)
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6602:9)
      at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6225:29)
      at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6181:11)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4046:13)
```

I would also spy warnings as well but I want to make sure if this is OK or if there is another solution to this?

**Comment by lmiller1990** [comment]
I don't have a solution off the top of my head, I guess we probably need to add something in here to support this use case (in the same way we did in 1.0, I think - Vue has some way to customize error handling, maybe we can use that?)

**Comment by wxsms** [comment]
my solution:

```js
expect(
      createWrapper.bind(
        null,
        '<carousel><slide><slide>{{ msg }}</slide></slide></carousel>',
        {
          msg: 'hello',
        }
      )
    ).toThrow('Slide parent must be Carousel.');
```

**Comment by sevilyilmaz** [comment]
@wxsms it's a good approach without spying console errors. But Vue still throws the warning that I mentioned above.

@lmiller1990 yeah, maybe a helper function or a flag to silent these warnings would work. Something similar to `enableAutoUnmount` which can be used in a test file, suit or unit. Though, the users need to be aware of that this would be dangerous because it will silent all Vue warnings. Or maybe it would only silent unhandled errors?

**Comment by lmiller1990** [comment]
Not sure, if you want to do some exploration and see if you can come up with something, happy to take a look. I find that if I need to throw an error, it's usually in  a function, so I just test the function in isolation.

**Comment by sevilyilmaz** [comment]
We usually throw an error if there is something unwanted in the slot content and we notify the developers with an error. For example;

```js
created() {
  if (!hasAllowedComponent(this.$slots.default, ACTION_BAR_ITEM_NAME)) {
    throw new Error(createdDefaultSlotAllowedComponentErrorMessage);
  }
},
```

The code above checks if ActionBar component has ActionBarItem in it. If it has something else it throws an error, so, I cannot isolate that.

I can try to explore but it will take longer for me than the maintainers.

**Comment by xanf** [comment]
@sevilyilmaz @lmiller1990 I believe the best way to that - is simply pass `warnHandler` / `errorHandler` in `global.config`
You can use it both for silencing warnings / errors or building assertions (if passing `jest.fn()`)

I'm using it for example in https://github.com/xanf/vue-test-utils-compat/commit/53731ba67f7f970ede5c3abe39999358dc77ac6d to silence expected warnings :)

**Comment by sevilyilmaz** [comment]
@xanf it's a bit of a verbose approach but it definitely does the job. Thank you :)

**Comment by lmiller1990** [comment]
Seems like this is fine for now, we can revisit if this becomes a more requested feature.

**Comment by gaokun** [comment]
I found a solution:

### vue-test-utils mount
```js
// this is in`mount` source code of vue-test-utils
component = defineComponent({
      compatConfig: {
        MODE: 3,
        INSTANCE_LISTENERS: false,
        INSTANCE_ATTRS_CLASS_STYLE: false,
        COMPONENT_FUNCTIONAL: isLegacyFunctionalComponent(originalComponent)
          ? 'suppress-warning'
          : false
      },
      props: originalComponent.props || {},
      setup:
        (props, { attrs, slots }) =>
        () =>
          h(originalComponent, { ...props, ...attrs }, slots),
      ...instanceOptions  // check this !!!
    })
```
check [source code](https://github.dev/vuejs/test-utils/blob/30e9c0c90ccfa5c7a90340ee29efce4935ed0d4d/src/mount.ts#L324)

### My test case
`mount` options is destructured for `defineComponent`.
So We can pass `errorCaptured` in options like this:
```js
mount(Button, {
    props: { loading: true },
    errorCaptured(err: any) {  // check this ~
      console.log('errorCaptured', err);
      return false;
    },
  })
```

It works as expected.

### Flaw
Typescript Error. `errorCaptured` dosen't defined in mount options type.
