### ISSUE TITLE
Adding methods to mount removes component methods

### ISSUE THREAD

**Issue by marina-mosti** [vuejs/vue-test-utils-next#1104]
Hey team,

Consider the following component:

```html
<template>
    {{ obj }}
</template>

<script>
export default {
  props: { obj: { type: Object, required: true } },
  watch: {
    obj: {
      immediate: true,
      handler (obj) {
        this.myFunc(obj)
      }
    }
  },
  methods: {
    myFunc () {
      console.log('my func')
    }
  }
}
</script>
```

And the following test:

```js
import TestWatch from '../../src/components/TestWatch.vue'
import { shallowMount } from '@vue/test-utils'

describe('TestWatch', () => {
    it('should not crash', () => {
        const wrapper = shallowMount(TestWatch, {
            props: {
                obj: {test : 1}
            },
            methods: {}
        })
    })
})
```

The test fails currently with
![image](https://user-images.githubusercontent.com/14843771/143456542-43bb9905-61f8-4cba-ab61-698e07793def.png)

If `methods: {}` is commented out of the mount, it passes.
This behavior was introduced in rc.17

**Comment by marina-mosti** [comment]
Initially i believe this was a problem with watchers, but testing out in minimal repro with a created hook we can reproduce the same error:

```html
<template>
    {{ obj }}
</template>

<script>
export default {
  props: { obj: { type: Object, required: true } },
  //   watch: {
  //     obj: {
  //       immediate: true,
  //       handler (obj) {
  //         this.myFunc(obj)
  //       }
  //     }
  //   },
  methods: {
    myFunc () {
      console.log('my func')
    }
  },
  created () {
    this.myFunc()
  }
}
</script>
```

![image](https://user-images.githubusercontent.com/14843771/143456880-fc34cfd9-49da-4286-b0df-73d0169048f7.png)

**Comment by xanf** [comment]
@marina-mosti Thank you for catching that. I believe `methods:` was deprecated along with `setMethods` 
Definitely worth a workaround though

**Comment by lmiller1990** [comment]
Should we throw an error if someone passes `methods`? It's an undefined behavior, I wouldn't expect it to do something, but looks like it currently does, probably because of this spread: https://github.com/vuejs/vue-test-utils-next/blob/master/src/mount.ts#L493

**Comment by marina-mosti** [comment]
I like that idea @lmiller1990 :) an error would be so helpful for people like me that never realized it got deprecated. It was only being used in a very old component that never complained about anything until rc.17
