### ISSUE TITLE
DOMWrapper isn't exported

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/vue-test-utils-next#111]
We'd like to use DOMWrapper inside of our plugins like the Data Test ID Plugin we reference in our docs

**Comment by lmiller1990** [comment]
It is exported: https://github.com/vuejs/vue-test-utils-next/blob/ddb81a0d20831738dfbc0d15f3b2bb9ad62521d6/src/index.ts#L7

**Comment by lmiller1990** [comment]
We just need to do a release. I will do this now.

**Comment by lmiller1990** [comment]
fixed in alpha 4 https://github.com/vuejs/vue-test-utils-next/releases/tag/2.0.0-alpha.4
