### ISSUE TITLE
Cannot use VTU-next as a module because it depends on commonjs dependencies

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/vue-test-utils-next#112]
Found this when trying to use VTU inside of Vite. Ended up patching the modules.

```
<script type="module">
import '@vue/test-utils'
</script>
```

will fail because we depend on two modules that use commonjs exports in our es bundle:

1. lodash
2. dom-event-types

The changes I had to make to get them to work are here:
https://github.com/JessicaSachs/vite-component-test-starter/blob/master/patches

To recreate a failure, you can...
1. clone the vite-starter
2. remove the patches directory
3. remove the node_modules
4. re-install deps
5. launch the dev server and navigate to /test/index.html

**Comment by lmiller1990** [comment]
Fixed here https://github.com/vuejs/vue-test-utils-next/pull/116

Will go out as soon as this is merged

**Comment by lmiller1990** [comment]
Fixed in #116, will release in the next alpha.
