### ISSUE TITLE
Setup vuex mock store for submodule (TypeScript)

### ISSUE THREAD

**Issue by djKooks** [vuejs/vue-test-utils-next#1125]
Hello,
I'm trying to make unit test for simple project with store setup as
```
export default createStore({
  modules: {
    sample,
    ...
})
```

and `sample` looks like:
```
const state = {
  info: {
    name: 'my-name',
  }
}

const getters: GetterTree<any, any> = {
  getSampleState: state => {
    return state.info
  },
}
```

I'm using this as:
```
setup() {
    const store = useStore()
    const sampleState = computed(() => store.getters['sample/getSampleState'])
```

but I cannot make things as
```
describe('Sample.vue', () => {
  it('TODO: Dummy test', () => {
    const store = createStore({
      state: {
        sample: {
          info: {
            name: 'alice'
          }
        }
      },
      getters: {
        sample: {        
          getSampleState: state => {
            return state.info
          }
        }
      },
    })
```

Cannot make getter by typescript error
```
Object literal may only specify known properties, and 'getConnectionListState' does not exist in type 'Getter<{ sample: { info: { name: string; }; }; }, { sample: { info: { name: string; }; }; }>'
```

- Is mock setting correct?
- How can I avoid the error?

**Comment by cexbrayat** [comment]
Hi @djKooks 

Thank you for opening an issue, but I'm not sure we have enough context to help you. The error mentions `getConnectionListState` which I don't see anywhere else. You did not provide the unit test either: how do you mount the component and provide the store?

Here are a few links that I think will help you: you'll need to provide the store either by using `global.provide` (see the [docs here](https://next.vue-test-utils.vuejs.org/api/#global)), or use the Vuex plugin (I suppose this is Vuex?) (see the [docs on how to test Vuex](https://next.vue-test-utils.vuejs.org/guide/advanced/vuex.html))

I'll close the issue for now, as I don't think this is an issue with VTU. Feel free to reopen if you think it is, and provide a minimal reproduction so we can investigate.

**Comment by djKooks** [comment]
@cexbrayat sorry, error message was wrong. I've updated it.
Okay, let me check, and I'll open again if I find something 🙏
