### ISSUE TITLE
 TypeError: Cannot read properties of null (reading 'addEventListener')

### ISSUE THREAD

**Issue by kevinmarrec** [vuejs/vue-test-utils-next#1158]
## Versions
`@vue/test-utils` => `2.0.0-rc.17` === `next` (at time of writing)
`@vue/vue3-jest` => `27.0.0-alpha.4`
`jest` => `27.4.5`
`ts-jest` => `27.1.2`
`typescript` => `4.5.3`

## Issue
![image](https://user-images.githubusercontent.com/25272043/146409148-f8f8fdab-93ab-4ebf-955f-e330f06bee85.png)

I can't make a simple Vue component mount working using last versions of every packages for Vue 3 & Jest 27 (and also couldn't make it work with Vue 3 & Jest 26).

The issue here is that somehow the VM doesn't have any `$el`, making `element` null here:
https://github.com/vuejs/vue-test-utils-next/blob/master/src/vueWrapper.ts#L111

Note: there have been some changes on `master` regarding this part of code, maybe this issue has been fixed ?

## Reproduction

**test/index.spec.ts**
```ts
import { mount } from '@vue/test-utils'
import Editor from '../src/components/Editor.vue'

test('should mount', () => {
  const wrapper = mount(Editor)

  expect(wrapper).toBeDefined()
})
```

**package.json**
```json
"jest": {
  "preset": "ts-jest",
  "testEnvironment": "jsdom",
  "moduleFileExtensions": [
    "js",
    "ts",
    "json",
    "vue"
  ],
  "transform": {
    "^.+\\.vue$": "@vue/vue3-jest"
  }
}
```

**Comment by cexbrayat** [comment]
Hi @kevinmarrec 

Thank you for opening an issue.
I suspect that you have a configuration issue somewhere. Or maybe your component is special, but we'll need a reproduction to investigate in that case.

Try to use Vue CLI to reproduce your issue, and if your problem persists, push the reproduction to GitHub, and ping me so I can reopen the issue. Thanks!

**Comment by kevinmarrec** [comment]
@cexbrayat Thanks for your faster answer.
It indeed sounds that my component is somehow `special`, I've been able to try again with simple ones and it works well.
I'll investigate if I can find the culprit in my component, and ultimately create a reproduction repository.
