### ISSUE TITLE
v2.0.0-rc.17 got a lot of Vue warn

### ISSUE THREAD

**Issue by hansonfang** [vuejs/vue-test-utils-next#1161]
When I use v2.0.0-rc.16, everything performs normal. But once I upgrade to v2.0.0-rc.17, a lot of Vue warn appears on the terminal. It looks like this:
`console.warn
    [Vue warn]: Maximum recursive updates exceeded in component <ElDialog>. This means you have a reactive effect that 
is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6533:17)
      at checkRecursiveUpdates (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6910:13)
      at check (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6872:28)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6878:29)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6897:13)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6897:13)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6897:13)`

I'm developing a components lib based on element-plus. It's seem like the waring is all about `Maximum recursive updates exceeded `

**Comment by cexbrayat** [comment]
Hi @hansonfang 

Thank you for opening an issue. This looks weird indeed. 

Can you provide us a minimum reproduction, please? 

Ideally, you can either: 
- add a unit-test to this repository that produces the warning with a small component
- or create a new repository on Github, with a minimal reproduction (a small component and its test that produces this warning with rc.17 and not in rc.16). You can use Vue CLI to create this repository.

**Comment by hansonfang** [comment]
Hi @cexbrayat ,I can't reproduce this issue from a new project and I found out why. It's the `babel.config.js`，I used a plugin called `plugins: ["@vue/babel-plugin-jsx"]`。when I deleted this config, everything back to normal. Thanks for your attention.

**Comment by hansonfang** [comment]
From this, I'd like to know why I can't use vue-test-util for `tsx` in vue. It just can't render deeper components and output these warning above. no matter `shallow` is true or false.

**Comment by cexbrayat** [comment]
Hi @hansonfang 

We have a simple test with tsx here https://github.com/vuejs/vue-test-utils-next/blob/master/tests/features/with-tsx.spec.tsx 

If you think there is an issue, try to add your (simplified) use-case to it, and open a PR with the reproduction, we'll take a look 👍

It might be an issue with `@vue/babel-plugin-jsx`, as it is not super actively maintained (JSX is not really the way the Vue team pushes forward, as the template compiler is way more efficient).

**Comment by hansonfang** [comment]
Is there a way to ignore these warnings like former version `config.showDeprecationWarnings = false` ?

**Comment by hansonfang** [comment]
I reproduced this problem and seems like only part of `@vue/babel-plugin-jsx` 's problem. I bulit a repo
[reproduce-vue-test-util-warning](https://github.com/hansonfang/reproduce-vue-test-util-warning)
just install the dependency and run `test` script ，you'll see the warning on the console.

**Comment by YangLG-7** [comment]
@hansonfang The same situation as me，I'm also developing a components lib based on element-plus.
But the difference is If I use shallowMount to mount my outer components,This exception will not occur.But that's not what we expected。
