### ISSUE TITLE
docs: how to test transitions still blank

### ISSUE THREAD

**Issue by Sepush** [vuejs/vue-test-utils-next#1163]
https://next.vue-test-utils.vuejs.org/guide/advanced/transitions.html
the docs about how to test transition are still blank any updates about it?
![image](https://user-images.githubusercontent.com/39197136/146804010-774e17c3-eec3-457f-8867-dd2a5add8ebf.png)

**Comment by afontcu** [comment]
Hi! Yeah, we're aware of that and something that needs to be sorted out before we hit the stable version.

Vue Test Utils 2 stubs transition and transition-group by default, as you can see in https://github.com/vuejs/vue-test-utils-next/blob/fdf67c059661d68d04d61ea0c5d083e8d2fef585/tests/mountingOptions/global.stubs.spec.ts#L367-L420

so component with transition should work fine by default – that is, render the actual content without having to worry about the transition: https://github.com/vuejs/vue-test-utils-next/blob/master/tests/features/transition.spec.ts

**Comment by Sepush** [comment]
> 

Thanks,I got it

**Comment by lmiller1990** [comment]
I wonder if we even need this page? Eg, rather than having a blank page in the public docs, which looks a bit bad, do we just remove all the incomplete pages (that'd we like to do) and create an issue to track them? Seeing empty docs is a bad look, especially when the actual library itself is quite stable and working well. What do you think @afontcu ?

**Comment by afontcu** [comment]
> I wonder if we even need this page?

That's a good point. The initial idea here was to explain how to test in-between states, but I'm not sure the scenario is that critical. 

About blank pages, I think I've been slacking off just enough, I'll put in some work during Christmas and fill the important ones. Let me take a look which ones are empty and prioritize them.

**Comment by Sepush** [comment]
> I wonder if we even need this page? Eg, rather than having a blank page in the public docs, which looks a bit bad, do we just remove all the incomplete pages (that'd we like to do) and create an issue to track them? Seeing empty docs is a bad look, especially when the actual library itself is quite stable and working well. What do you think @afontcu ?
> 
> @Sepush any specific questions or difficulties you are having around transitions? Or did you just want to call out them empty page?

Removing these blank pages is OK.
I start to write some tests for a lib these days, so I go to the docs for learning.
when I read the section about how to test Transition, I found it blank so I create this issue for the report.
afontcu has given me some examples about this.

**Comment by lmiller1990** [comment]
closed by #1213
