### ISSUE TITLE
Trigger event with payload from stubbed component

### ISSUE THREAD

**Issue by ol1s** [vuejs/vue-test-utils-next#1177]
I want to test that my ParentComponent correctly handles an event emitted by the ChildComponent:

```
const ParentComponent = {
  template: `<div><child-component id="childComponent" @myevent="myHandler" /></div>`,
  components: { ChildComponent },
  methods: {
    myHandler(payload) {
      console.log(payload)
    },
  },
}
```
```
const ChildComponent = {
  template: `<p>Child</p>`,
  emits: ["myevent"],
}
```

I am not concerned with the underlying workings of the ChildComponent, only that it emits this particular event. For
that reason I have stubbed the ChildComponent. This leaves me with a DOMWrapper which has a `trigger()` method available:

```
test("handles my event", async () => {
  const wrapper = shallowMount(ParentComponent)
  await wrapper.find(`[id="childComponent"]`).trigger("myevent", { example: "Test 1" })
})
```

However, when adding a payload to the event it does not get passed as expected to the handler:

```
//console.log
{
  isTrusted: [Getter],
  example: 'Test 1'
}
```

Likewise, if I pass a string as the payload it gets split as follows:

```
test("handles my event", async () => {
  const wrapper = shallowMount(ParentComponent)
  await wrapper.find(`[id="childComponent"]`).trigger("myevent", "Test1")
})
```
```
//console.log
{
  '0': 'T',
  '1': 'e',
  '2': 's',
  '3': 't',
  '4': '1',
  isTrusted: [Getter]
}
```

I suspect I am passing the payload incorrectly, but how else can I test an event with payload from a stubbed component?

**Comment by freakzlike** [comment]
You should use `findComponent` and `vm.$emit` to emit custom events. `trigger` is only for DOM Events like `click` or `focus`.
```ts
const child = wrapper.findComponent({ name: 'ChildComponent' })
await child.vm.$emit('myevent', { example: "Test 1" })
```

**Comment by ol1s** [comment]
That’s great, love it when there’s a simple fix to doing something wrong 😁

**Comment by okmkey45** [comment]
Hello. I don't know if I'm missing something about this. I followed the suggestion of using `vm.$emit` for triggering a custom event from the child component. The issue I'm having is that if I check the event array returned by `wrapper.emitted()`, I'm getting the event I triggered from the child component. Does this make sense? I would expect that this event array should only contain events emitted by the `wrapper` itself and not events from children. And I'm sure I'm not emitting the same event from the component I mounted for testing

```js
const child = wrapper.findComponent({ name: 'ChildComponent' })
await child.vm.$emit('myevent', { example: "Test 1" })

const events = wrapper.emitted()
console.log(events) // or if you want, assert something
```
So, checking the `events` array, this is what I'm getting:

```js
{
  myevent: [
    [
      {
        example: 'Test 1',
      },
    ],
  ],
}
```

**Comment by okmkey45** [comment]
OK. I found out why this wasn't working. The component that I'm testing goes kind of like this:

```vue
<script setup lang="ts">
const props = defineProps<{
  someProp: string
}>()

const emit = defineEmits<{
  (event: 'parentSubmit', formData: object): void
}>()

const handleSubmit = (newFormData) => {
  emit('parentSubmit', newFormData)
}
</script>

<template>
  <MyChildForm
    @childSubmit="handleSubmit"
    data-test-id="ParentComponent__form"
  >
  </MyChildForm>
</template>
```

So, I wanted to test that when the `MyChildForm` component submits something with `childSubmit` event, the `parentSubmit` event was being emitted. It seems easy.

```js
const wrapper = shallowMount(ParentComponent, {
  props: { someProp: 'some value' },
})

const child = wrapper.findComponent({ name: 'MyChildForm' })
await child.vm.$emit('childSubmit', { example: "Test 1" })

expect(wrapper.emitted()).toHaveProperty('parentSubmit') // <- this fails
```

So the assert fails and actually, `wrapper.emitted()` contains `childSubmit`. You would expect that it would contain the `parentSubmit`, since I'm taking it from the `wrapper`.

Guess what?

Since `MyChildForm` is the root node of the component, it's inheriting all attributes. Even I printed out the props for both `wrapper.props()` and `wrapper.findComponent({ name: 'MyChildForm' }).props()` and they're the same.

Wow!!!

When I changed wrap `MyChildForm` inside a div, everything changed. `wrapper.emitted()` no longer has the `childSubmit` event. Well, now it's empty and I need to understand why. Maybe I'm missing something.
