### ISSUE TITLE
Cannot call setValue() on a stubbed component

### ISSUE THREAD

**Issue by ol1s** [vuejs/vue-test-utils-next#1178]
I have a ChildComponent which has a `v-model` binding to the `myData` property in the ParentComponent. Becuase I am not concerned with the underlying detail of the ChildComponent I have stubbed it in my test:

```
const ParentComponent = {
  template: `<div><child-component v-model="myData" id="childComponent" /></div>`,
  components: { ChildComponent },
  data() {
    return {
      myData: "",
    }
  },
}
```
```
const ChildComponent = {
  template: `<p>Child</p>`,
  emits: ["update:modelValue"],
}
```

As part of my test I want to ensure that the `v-model` bindings on the ChildComponent are setup correctly. My stubbed ChildComponent is an instance of the DOMWrapper which exposes the `setValue()` method:

```
test("sets value from child component", async () => {
  const wrapper = shallowMount(ParentComponent)
  await wrapper.find(`[id="childComponent"]`).setValue("Test 1")
  expect(wrapper.vm.myData).toEqual("Test 1")
})
```

However, when running this test I get the following error:

```
ERROR: wrapper.setValue() cannot be called on CHILD-COMPONENT-STUB
```

Hopefully my use case above explains clearly why I would expect a stubbed component to be able to have it's value set. Also, if I have missed something obvious please correct me 😁

**Comment by freakzlike** [comment]
Use something like this:
```ts
const child = wrapper.findComponent({ name: 'ChildComponent' })
expect(child.props('modelValue')).toBe('Test 1')

await child.vm.$emit('update:modelValue', 'Test 2')

expect(child.props('modelValue')).toBe('Test 2')
```

**Comment by ol1s** [comment]
Perfect, thanks for the help
