### ISSUE TITLE
Extend stub via mounting options

### ISSUE THREAD

**Issue by ol1s** [vuejs/vue-test-utils-next#1179]
I want to be able to "fake" the method of a stubbed component. Currently this is possible by providing my own defined stub at mount time:

```
const ParentComponent = {
  template: `<div><child-component id="childComponent" ref="childComponent" /></div>`,
  components: { ChildComponent },
  methods: {
    myAction() {
      return this.$refs.childComponent.childMethod()
    },
  },
}
```
```
test("calls method on child component", async () => {
  const wrapper = shallowMount(ParentComponent, {
    global: {
      stubs: {
        ChildComponent: {
          methods: {
            childMethod() {
              return "Test 1"
            },
          },
        },
      },
    },
  })
  expect(wrapper.vm.myAction()).toEqual("Test 1")
})
```

However, this approach fully replaces the stub that would be produced automatically by `shallowMount()` and I end up with this warning:

```
WARNING: Component is missing template or render function
```

Is there are way for to "extend" a stub so I can add faked methods etc but without having to redefine the template or render function each time?

**Comment by freakzlike** [comment]
I'm looking to make some improvements to stubs. Maybe I can add this too

**Comment by cexbrayat** [comment]
@ol1s There is currently no way to do this. I usually provide an empty template or render function. I tend to think this is not worth adding another feature to stubs (which are already quite complicated to maintain). What do the rest of team think?

**Comment by ol1s** [comment]
Thanks both for the replies. 

I am currently providing a hardcoded template to solve my situation:

```
const wrapper = shallowMount(ParentComponent, {
    global: {
      stubs: {
        ChildComponent: {
          template: `<div v-bind="$props" />`,
          methods: {
            childMethod() {
              return "Test 1"
            },
          },
        },
      },
    },
  })
```

On reflection, this is a pretty small price to pay in order to avoid bloating the API with additional configuration options.
