### ISSUE TITLE
Config leaks between tests

### ISSUE THREAD

**Issue by purepear** [vuejs/vue-test-utils-next#1187]
Thanks for the great work, guys! 🙇  
I just noticed that when i pass the router plugin in a test, then the rest of the tests were inheriting the router. 
```js
mount(Component, { global: { plugins: [router] }})
```

I also have a global config setup:  
```js
config.global.config.globalProperties = {
  $router: routerMock,
  $route: routeMock,
}
```

---

I believe it has sth to do with the config merging strategy - it uses shallow clone and in the case of deeply nested objects, it overwrites the VTU's global config object. This might not be limited to plugins/config/globalProperties but other parts of the config as well 🤔 

Here's how to reproduce:

```js
import { config, mount } from '@vue/test-utils'
import { h } from 'vue'

config.global.config.globalProperties = {
  $anotherThing: 'not used but sth to demonstrate a non-empty global config',
}

const Plugin = {
  install(app) {
    app.config.globalProperties.$something = 'something'
  },
}

const Component = {
  render() {
    return h('div', this.$something)
  },
}

test('should pass with plugin', () => {
  const wrapper = mount(Component, {
    global: {
      plugins: [Plugin],
    },
  })

  expect(wrapper.html()).toContain('something')
})

test('should pass without plugin but it fails!', () => {
  const wrapper = mount(Component)

  expect(wrapper.html()).not.toContain('something')
})

```

**Comment by cexbrayat** [comment]
Thanks @purepear for the repro 👍

Would you like to work on a PR to fix this? If you add this test to `config.spec.ts`, you may be able to figure out what's going on.

**Comment by purepear** [comment]
@cexbrayat yep, i will see if i can raise a PR during the weekend. Haven't looked too deep into the code but i suspect `cloneDeep` will be involved in the fix :) I guess a potential problem of config cloning might be a config with class/component instances but... 🤔 will see
