### ISSUE TITLE
`findAll` returns nothing when using a render function

### ISSUE THREAD

**Issue by huuff** [vuejs/vue-test-utils-next#1201]
### Subject of the issue
`findAll()` returns nothing when the component is using a render function.

### Steps to reproduce
This as `TestComponent.vue`:

```vue
<template>
<render></render>
</template>

<script setup lang="ts">
import { h } from 'vue';

const render = () => [
  h('a', {}, 'first'),
  h('a', {}, 'second'),
  h('a', {}, 'third'),
];
</script>
```

Then in `TestComponent.spec.ts`:

```ts
import { mount } from '@vue/test-utils';
import TestComponent from './TestComponent.vue';

describe('mcve', () => {
  test('should have all three anchors', () => {
    const wrapper = mount(TestComponent);

    expect(wrapper.findAll('a').length).toBe(3);
  });
});

```

### Expected behaviour
The test should pass.

### Actual behaviour
The test fails because `findAll` is unable to find the three anchors.

**Comment by LinusBorg** [comment]
Transferred to vue-test-utils-next as it's about Vue 3

**Comment by cexbrayat** [comment]
Hi @huuff 

Thank you for providing a small repro. Which version of VTU are you using? 

I think this may be the same as #1173 which appeared after releasing rc.18. 

cc @xanf as he started to work on that

**Comment by huuff** [comment]
Yes, the version I'm using is rc.18. [Here's](https://github.com/huuff/mcve-test-utils-render-function) an MCVE

**Comment by huuff** [comment]
Also, I just tested and it seems to also happen for rc.16

**Comment by huuff** [comment]
Found a (sort of) workaround. If your element is wrapped in some other element, you can first query for that one and then run the `findAll`.

Example element:

```vue
<template>
<render></render>
</template>

<script setup lang="ts">
import { h } from 'vue';

const render = () => [
  h('div', {}, [ 
    h('a', {}, 'first'),
    h('a', {}, 'second'),
    h('a', {}, 'third'),
  ]),
];
</script>
```

Then in the test:

```typescript
import { mount } from '@vue/test-utils';
import TestComponent from './TestComponent.vue';

describe('mcve', () => {
  test('should have all three anchors', () => {
    const wrapper = mount(TestComponent);

    expect(wrapper.get("div").findAll('a').length).toBe(3);
  });
});
```

It's not entirely a workaround since it requires wrapping the wanted element in another, but it helped me.

**Comment by justin-schroeder** [comment]
> Found a (sort of) workaround. If your element is wrapped in some other element, you can first query for that one and then run the `findAll`.

Really appreciate @huuff finding a fix for this while we wait for another publish. Had to rewrite a bunch of tests, but at least we're building again. 🙏

**Comment by Archetipo95** [comment]
@lmiller1990  Any ETA on when this fix will be on next release?
