### ISSUE TITLE
Wrong import in 2.0.0-rc.18

### ISSUE THREAD

**Issue by jamesalways** [vuejs/vue-test-utils-next#1206]
I updated to the latest version:` 2.0.0-rc.18` and I started having ts errors. I looked into `node_modules/@vue/test-utils/dist/interfaces/wrapperLike.d.ts` and I found this: 
```
import { DefinedComponent, FindAllComponentsSelector, FindComponentSelector, NameSelector, RefSelector } from 'src/types';
import { VueWrapper } from 'src/vueWrapper';
```

But I have this folder structure in  `node_modules/@vue/test-utils` and there is no src, you need to change src for ... I think

<img width="355" alt="Screenshot 2022-01-04 at 09 07 01" src="https://user-images.githubusercontent.com/3009870/148028184-9c3d7eef-4f78-4b16-9b72-14b98d18458a.png">

https://github.com/vuejs/vue-test-utils-next/blob/v2.0.0-rc.18/src/interfaces/wrapperLike.ts

Thanks!

**Comment by cexbrayat** [comment]
Thanks, this was already raised in #936 and fixed in #1184 

This should be released soon. In the meantime, you can use `skipLibCheck` in your tsconfig.
