### ISSUE TITLE
Snapshot tests render comments. Is this intentional?

### ISSUE THREAD

**Issue by sevilyilmaz** [vuejs/vue-test-utils-next#1208]
In `v1.x` the comments have been stripped from the snapshots but in `v2.x` they persist which makes the snapshots hard to read. Is this an expected behaviour? Here is an example:

```
exports[`FormControl Prop: [disabled] is passed renders with the disabled styles 1`] = `
<div class="root--variant-body_2 root"><label class="root--variant-emphasized_2 root--color-disabled label" for="__bui-1">
    <!-- @slot for label. -->Field label
    <!--v-if-->
    <!--v-if-->
    <!--v-if-->
  </label>
  <!--
      @slot for content.
        @binding {object} attrs Child attributes: id and aria attributes.
     --><input>
  <div class="root--variant-body_2 root--color-disabled note" id="__bui-1-note" role="alert">
    <!-- @slot for error. -->
    <!-- @slot for helper. -->Field note
  </div>
</div>
`;
```

**Additional info:**

- `@vue/test-utils@2.0.0-rc.18`
- `@vue/vue3-jest@^27.0.0-alpha.3`
- `jest@^27.3.1`

**Comment by tehciolo** [comment]
Hi @cexbrayat 

What is recommended basically everywhere (for Vue2) is usage of [this serializer](https://github.com/eddyerburgh/jest-serializer-vue/). The one you linked to is probably just a more up to date one, as it is a fork of the one I linked.

Shouldn't such a serializer actually come from `@vue/test-utils` instead?

Without using a serializer, the component snapshots are not readable at all. The comments are not the only problem. Spacing/indentation is missing as well.

**Comment by cexbrayat** [comment]
@tehciolo Yeah, the one linked is not maintained anymore I think, but you can use whatever serializer you want of course.

VTU chose to be unopinionated and doesn't do anything special for snapshots except prettifying `wrapper.html()` output using [`pretty`](https://www.npmjs.com/package/pretty). Jest lets you do whatever you want with a serializer, so if you write a custom one, or find one, we'll be happy to mention it in the docs 👍
