### ISSUE TITLE
Error: Component is missing template or render function.

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vue-test-utils-next#131]
### Error:
```
[Vue warn]: Component is missing template or render function.
  at <Anonymous ref="VTU_COMPONENT" >
  at <VTUROOT>
```
### My setup (simplified):
```js
import test from 'ava'
import { mount } from '@vue/test-utils'
import { createApp } from 'vue/dist/vue.cjs.js'

test('expected behaviour computed prop lifecycle - no reactivity', async t => {
  const vue = createApp({
    template: `<pre>{{ myComputed }}</pre>`,
    computed: {
      myComputed () {
        return 1
      },
    },
  })
  const wrapper = mount(vue)
  // @ts-ignore
  console.log(`wrapper.vm.myComputed → `, wrapper.vm.myComputed)
})
```
### Reproduction:
```
git clone https://github.com/vue-sync/simple-store
cd simple-store
npm i
npm run test test/internal/vueComputed.ts
```

Please let me know if I need to give more background or explain what it is exactly what I'm trying to do and why!

**Comment by afontcu** [comment]
Hi! 👋  VTU-next is [creating the App for you](https://github.com/vuejs/vue-test-utils-next/blob/master/src/mount.ts#L190), so I think you should use `defineComponent` ([example](https://github.com/vuejs/vue-test-utils-next/blob/master/tests/text.spec.ts#L7)) instead of createApp.

Let me know if that helped!

**Comment by mesqueeb** [comment]
@afontcu that worked!
is there anywhere I can contribute this knowledge to the vue-test-utils alpha for vue 3 docs?

**Comment by afontcu** [comment]
Hi! I do believe content is mostly there: [the example in Introduction](https://vuejs.github.io/vue-test-utils-next-docs/guide/introduction.html#what-is-vue-test-utils) shows how to pass a component to `mount()`, and so does the [API docs for mount()](https://vuejs.github.io/vue-test-utils-next-docs/api/#mount).
