### ISSUE TITLE
ctx.slots.default is not function

### ISSUE THREAD

**Issue by Hades-li** [vuejs/vue-test-utils-next#164]
```
// this is setup function of component
setup(props, ctx) {
      // const {type, hit, effect} = props
      const ELEMENT = useELEMENT()
      // computed
      const tagSize = computed(() => {
        return props.size || (ELEMENT || {}).size
      })

      // methods
      function handleClose(event) {
        event.stopPropagation()
        ctx.emit('close', event)
      }

      function handleClick(event) {
        ctx.emit('click', event)
      }

      const classes = [
        'el-tag',
        props.type ? `el-tag--${props.type}` : '',
        tagSize.value ? `el-tag--${tagSize.value}` : '',
        props.effect ? `el-tag--${props.effect}` : '',
        props.hit && 'is-hit'
      ]

      const child = h('i', {
        class: 'el-tag__close el-icon-close',
        onClick: handleClose
      })
      const tagEl = h('span', {
        class: classes,
        style: {backgroundColor: props.color},
        onClick: handleClick,
      }, [ctx.slots.default(), props.closable && child])

      return () => props.disableTransitions ? tagEl : h('transition', {
        name: 'el-zoom-in-center'
      }, [tagEl])
    },
```
```
// this is tag.specs.js
import { mount } from '@vue/test-utils/dist/vue-test-utils.cjs'
import Tag from 'packages/tag'

describe('Tag', () => {
  it('create', () => {
    const wrapper = mount(Tag)
    expect(wrapper.html()).to.be.include('span')
  })
})
```
the component can be render. but test fail。
log is :
![image](https://user-images.githubusercontent.com/12124478/88375281-e019d300-cdcd-11ea-84e7-52a542f91ac1.png)

project git: [https://github.com/Hades-li/element-next](https://github.com/Hades-li/element-next)

**Comment by lmiller1990** [comment]
Hello!

If there is no default slot, `ctx.slots.default` will not be defined, and you get this error. I was able to reproduce it in your project, too.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/19196536/88386593-110cfe80-cdf4-11ea-8efa-edd8327db19b.png">

I think you just need to do `ctx.slots.default && ctx.slots.default()`. Also, for `<transition>`, you need to do `import { Transition } from 'vue'` and do `h(Transition)` - it's not a native tag.

**Comment by Hades-li** [comment]
> Hello!
> 
> If there is no default slot, `ctx.slots.default` will not be defined, and you get this error. I was able to reproduce it in your project, too.
> 
> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/19196536/88386593-110cfe80-cdf4-11ea-8efa-edd8327db19b.png">
> 
> I think you just need to do `ctx.slots.default && ctx.slots.default()`. Also, for `<transition>`, you need to do `import { Transition } from 'vue'` and do `h(Transition)` - it's not a native tag.

I create simple component for test。
![image](https://user-images.githubusercontent.com/12124478/88481287-0a65bf00-cf8d-11ea-8e67-01179148f322.png)
![image](https://user-images.githubusercontent.com/12124478/88481334-70eadd00-cf8d-11ea-8d53-720ffa83d4d0.png)
render is ok。but test is fail.

project git: [https://github.com/Hades-li/element-next.git](https://github.com/Hades-li/element-next.git)

**Comment by lmiller1990** [comment]
How are you rendering `<Test />` in the browser? You shared `test.vue`, but not the usage.

You can provide `slots` using the mounting option: https://vuejs.github.io/vue-test-utils-next-docs/api/#slots.

```js
const wrapper = mount(Test, {
  slots: {
    default: 'Testing'
  }
})
```

You will always need to check if `ctx.slots.default` exists before calling it.

**Comment by Hades-li** [comment]
> How are you rendering `<Test />` in the browser? You shared `test.vue`, but not the usage.
> 
> You can provide `slots` using the mounting option: https://vuejs.github.io/vue-test-utils-next-docs/api/#slots.
> 
> ```js
> const wrapper = mount(Test, {
>   slots: {
>     default: 'Testing'
>   }
> })
> ```
> 
> You will always need to check if `ctx.slots.default` exists before calling it.

sorry, i forget add slots option。but, render is fail too when i add slots option. 
![image](https://user-images.githubusercontent.com/12124478/88555739-c2ad6900-d05a-11ea-965d-5049905ca6f1.png)

**Comment by lmiller1990** [comment]
Odd. We have this exact test:

https://github.com/vuejs/vue-test-utils-next/blob/c3e2673b3be49b6065d82aa18ab2529889698235/tests/mountingOptions/slots.spec.ts#L12

I will try reproduce using your repo.
