### ISSUE TITLE
Ensure rc.5 doesn't break things

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#165]
Some breaking changes for us. Relevant: https://github.com/vuejs/vue-next/commit/a75b8a268fca800a49c7d772b4a290b4435e85b9

**Comment by lmiller1990** [comment]
So it does, this line mainly https://github.com/vuejs/vue-test-utils-next/blob/c3e2673b3be49b6065d82aa18ab2529889698235/src/utils/find.ts#L45

We can no longer find un-named components, so this fails: https://github.com/vuejs/vue-test-utils-next/blob/c3e2673b3be49b6065d82aa18ab2529889698235/tests/findComponent.spec.ts#L85

I am not sure how to fix this yet. Or if we can.

**Comment by lmiller1990** [comment]
These four fail too, not sure why yet: https://github.com/vuejs/vue-test-utils-next/blob/c3e2673b3be49b6065d82aa18ab2529889698235/tests/setValue.spec.ts#L205

**Comment by lmiller1990** [comment]
One fix for using find with `shallowMount` would be to require users to specify a `name` on their components.

**Comment by cexbrayat** [comment]
@lmiller1990 I pushed a PR that should fix all the issues. See #167 when you have some time
The test has a weird name, but we try to find a component without a name based on its name in the parent registration (on Evan suggestion) ;)

**Comment by lmiller1990** [comment]
It's out!
