### ISSUE TITLE
How to check v-show is true  ?

### ISSUE THREAD

**Issue by leo-acrossb** [vuejs/vue-test-utils-next#169]
I couldn't find Wrapper.isVisible() method..
how can i find method like isVisible?

**Comment by leo-acrossb** [comment]
sorry, i found document.

**Comment by afontcu** [comment]
Hi! Thanks for filling this in.

isVisible is deprecated in VTU 1 and won't be available in VTU 2. [See here for docs](https://vue-test-utils.vuejs.org/upgrading-to-v1/#isvisible).

This made me think, though, that we should explain that bit in [Conditional Rendering](https://vuejs.github.io/vue-test-utils-next-docs/guide/conditional-rendering.html) 🤔

**Comment by lmiller1990** [comment]
Good idea, we should update conditional rendering in the docs.

Are you using jest @leo-acrossb? If so, try the library linked in the docs. If you are using something else (webpack-mocha + chai combo) you could use the jquery-chai plugin which has [`to.be.visible`](https://devhints.io/chai#chai-with-jquery).

**Comment by afontcu** [comment]
I'm going to close this issue up and track any progress on docs here: https://github.com/vuejs/vue-test-utils-next-docs/issues/47 :) 

Thanks!
