### ISSUE TITLE
Why the clientWidth of wrapper is 0?

### ISSUE THREAD

**Issue by Ryan2128** [vuejs/vue-test-utils-next#186]
I used vue-test-utils-next to test my componnet, but a use case always could not pass test, so I printed the clientWidth of the wrapper and found it to be 0.

Version:
2.0.0-beta.2

Code: 
```
it('step', done => {
    const wrapper = mount({
      template: `
        <div style="width: 200px;">
          <slider v-model="value" :min="0" :max="1" :step="0.1"></slider>
        </div>
      `,
      components: { Slider },
      data() {
        return {
          value: 0,
        }
      },
    })
    // Because the clientWidth is 0, so Slider component can't get right sliderSize.
    console.log(wrapper.element.style.width)
    console.log(wrapper.element.clientWidth)
    console.log(wrapper.element.clientHeight)
    console.log(wrapper.element.clientLeft)
    console.log(wrapper.element.clientTop)
})
```

Behavior:
![image](https://user-images.githubusercontent.com/33176053/90981824-c1a62380-e595-11ea-9d58-314a37d1549f.png)

**Comment by Ryan2128** [comment]
I turned a mistake. This is a jsdom problem. Using jest's mock can simulate specific data.

**Comment by archiewx** [comment]
> I turned a mistake. This is a jsdom problem. Using jest's mock can simulate specific data.

Could you send in your solution? I have the same problem as you
