### ISSUE TITLE
Global config options does not support partial config

### ISSUE THREAD

**Issue by AtofStryker** [vuejs/vue-test-utils-next#189]
While tackling https://github.com/vuejs/vue-test-utils/issues/1503, I ran into some issues while adding a `global.config` option to my component. The below error occured when running the following code:

`TypeError: Cannot assign to read only property 'isNativeTag' of object '#<Object>'`

``` async.test.ts
// @ts-ignore
import TestComponent from "./TestComponent.vue";
import { shallowMount } from "@vue/test-utils";
import { createApp } from "vue";

describe("Test Error Handler Vue 3", () => {
  it("Mounts a global errorhandler without issue", async (done) => {
    const app = createApp({});
    app.config.errorHandler = (err: any, vm, info) => {
      if (info.includes("beforeMount")) {
        expect(err.message).toBe("test");
      }
      done();
    };

    shallowMount(TestComponent, {
      global: {
        /// the below causes the exception `Cannot assign to read only property 'isNativeTag' of object '#<Object>'`
        config: app.config,
        // the below also has problems. It looks the the type is Pick<> with almost all the values of the config. Should this be a Partial type?
        // config: {
        //   errorHandler: app.config.errorHandler
        // }
      },
    });
  });
});

```

I put a reproduction link [here](https://github.com/AtofStryker/vue-test-utils-next-sandbox/tree/bug/config_typings). This is my first time using `Vue 3` and `VTU 2.x` so it is likely I am doing something incorrect and have no idea what I am doing :laughing:. Hopefully I am using this API correctly while https://github.com/vuejs/vue-test-utils-next-docs/issues/49 is completed.

**Comment by cexbrayat** [comment]
@AtofStryker Thank you for this detailed repro! You're right, it should accept a partial config without complaining. I think I fixed it in #195 , you should be able to give it a try when we emrge and release this
