### ISSUE TITLE
Cannot access document inside a test

### ISSUE THREAD

**Issue by AnnaYuS** [vuejs/vue-test-utils-next#193]
I'm migrating an application from Vue 2 to Vue 3 and updating the tests. There is a test for creating a download link and simulating a click on it. This part used to work:

```
const link = document.querySelectorAll('[download]')[0]

expect(link.getAttribute('download')).toBe('File name')
expect(link.getAttribute('href')).toBe('url')
```
But now the `document` seems to be empty.

The whole test looks something like this:

```
const AppDialog = {
  name: 'AppDialog',
  template: '<div><slot name="buttons"/><slot/><slot name="default"/></div>'
}

it('downloads a file', async () => {
    // Given
    const wrapper = mount(Dialog, {
      global: {
        stubs: {
          AppDialog: AppDialog
        }
      },
      data () {
        return {
          form: {
            field_1: '1234567890',
            field_2: 'AB123456789'
          }
        }
      },
      props: {
        id: 2,
        isShowing: true
      }
    })

    axios.post = jest.fn(() => Promise.resolve({ data: { name: 'File name' } }))

    window.URL.createObjectURL = jest.fn(() => 'url')

    // When
    await wrapper.find('form').trigger('submit')

    await flushPromises()

    const link = document.querySelectorAll('[download]')[0]

    // Then
    expect(link.getAttribute('download')).toBe('File name')
    expect(link.getAttribute('href')).toBe('url')

    expect(wrapper.emitted().close).toHaveLength(1)
  })

```

The error is: `TypeError: Cannot read property 'getAttribute' of undefined`.

Is there a reason why the `document` is empty? Is there a way to access it?

**Comment by lmiller1990** [comment]
I believe this should have been the case in VTU v1 by default as well? You will need to specify `attachTo`: https://vuejs.github.io/vue-test-utils-next-docs/api/#attachto to actually mount your component on the DOM.

As an aside, let me know (make issues!) of any inconsistencies you find between V1 and V2. I would like to make the migration experience as seemless as possible.

**Comment by AnnaYuS** [comment]
Thanks for your help, it works now 👍 I'll keep you posted. 
Somehow the test was successful with VTU v1 and Vue 2 🤷‍♀️. There was an error coming from jsdom (`Error: Not implemented: navigation (except hash changes)...`) but the test passed.

**Comment by lmiller1990** [comment]
Not sure about the jsdom warning, but glad it's passing. Is your project OSS? I'd love to check it out.

**Comment by AnnaYuS** [comment]
Nope, it's private.
