### ISSUE TITLE
mounting options: slots/scoped slots

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#2]
Slots are a pain point in VTU beta. We should make sure there are tests for all the cases, and they all work as expected.

Ref: slots specs in VTU beta: https://github.com/vuejs/vue-test-utils/blob/dev/test/specs/mounting-options/slots.spec.js

We should port the ones that are relevant to this codebase.

NOTE: slots and scoped slots are now the same thing in Vue 3.

**Comment by lmiller1990** [comment]
@dobromir-hristov is there anything else we need to look into for slots? I believe you made a PR around this already.

**Comment by dobromir-hristov** [comment]
Yeah, helpers at most.
