### ISSUE TITLE
Warning: "Avoid app logic that relies on enumerating keys on component instance" during snapshot tests

### ISSUE THREAD

**Issue by brandonwoz** [vuejs/vue-test-utils-next#209]
Test Utils console logs warning message during snapshot testing.

### Steps to Reproduce
```
    it('should render correctly', () => {
      const wrapper = mount(Foo);
      expect(wrapper).toMatchSnapshot();
    });
```

### Actual Behavior
Test passes/fails as expected, but test Utils console logs warning message during snapshot testing.

```
console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
      [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.
```
### Expected Behavior
Test should pass/fail as appropriate without warning message.

**Comment by WebDevEtc** [comment]
Shouldn't it be `expect(wrapper.html()).toMatchSnapshot();` instead of the whole `wrapper` object?

(especially in a test described as 'it should render correctly')

Then you are snapshotting just the html and that warning does not appear.

**Comment by lmiller1990** [comment]
`wrapper` is a complicated class with a ton of un-serializable things, such as the circular dependencies Vue creates in it's vdom tree.

I'd recommend doing what is suggested above. You want to match against the `html`, right? Either way, this is not a VTU specific issue; Vue is telling you not to enumerate keys on the instance.

**Comment by brandonwoz** [comment]
Yes. This was simply an oversight by me. Thank you and I apologize.

**Comment by lmiller1990** [comment]
No need to apologize!! Good luck 👍
