### ISSUE TITLE
Programatically accessing a slot in a test always returns null for children

### ISSUE THREAD

**Issue by lewishowles** [vuejs/vue-test-utils-next#221]
I've been having a weird issue with migrating out component library over to Vue 3's options API (for now), with the intention to eventually moving each component to use the composition API.

I have a helper function that can be used to show or hide sections of a component depending on whether a given slot exists and has content. In trying to update that I noticed that in Vue Test Utils, accessing `$slots.default()` always has `children: null`, even if that slot has content, and even if that content is rendered in the test.

For example, a simple sample component such as

```html
<template>
  <div class="super-simple-component">
    <slot />
  </div>
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'super-simple-component',
});
</script>
```

and a test such as

```javascript
import { mount } from '@vue/test-utils';

import SuperSimpleComponent from '@/components/super-simple-component';

test('Slot content example', () => {
  const wrapper = mount(SuperSimpleComponent, {
    slots: {
      default: 'Default slot content',
    },
  });

  console.log({ html: wrapper.html(), programatic: wrapper.vm.$slots.default() });
});
```

outputs

```
{
  html: '<div class="super-simple-component">Default slot content</div>',
  programatic: [{
    __v_isVNode: true,
    __v_skip: true,
    type: [Object],
    props: null,
    key: null,
    ref: null,
    scopeId: null,
    children: null,
    component: null,
    suspense: null,
    ssContent: null,
    ssFallback: null,
    dirs: null,
    transition: null,
    el: null,
    anchor: null,
    target: null,
    targetAnchor: null,
    staticCount: 0,
    shapeFlag: 4,
    patchFlag: 0,
    dynamicProps: null,
    dynamicChildren: null,
    appContext: null
  }]
}
```

I'm not sure if I'm missing a setup stage?

**Comment by lmiller1990** [comment]
Interesting. This (might) by related to [wrapping everything in a "Parent" component](https://github.com/vuejs/vue-test-utils-next/blob/dd780f8504c3107608d211b4a797af2d01f97548/src/mount.ts#L190) which allows us to accomplish various things.

I tried for about 30m to find the textNode which I know exists somewhere, but no luck, despite knowing the vdom structure relatively well.

I have to ask what the use case is here - if you want to assert that something is rendered in a slot, can you just assert against `html` or something? What do you intend on doing with `slots.default()` once you can access it? 

If this is a common use case, maybe we need a more first class way to test it (eg, using `vm` basically means you were unable to test your component with the features included in Vue Test Utils - if you just want to do things with `vm`, you don't even need Vue Test Utils).

Fine-grained access to implementation details is not really a specific goal of this library.

**Comment by lmiller1990** [comment]
Edit: this works:

```js
import { h } from 'vue';
import { mount } from '../src'

import SuperSimpleComponent from './super-simple-component.vue';

test('Slot content example', () => {
  const wrapper = mount(SuperSimpleComponent, {
    slots: {
      default: h('span', 'blah blah')
    },
  });

  console.log({ html: wrapper.html(), programatic: wrapper.vm.$slots.default() });
});
```

Output:

```
console.log
    {
      html: '<div class="super-simple-component"><span>blah blah</span></div>',
      programatic: [
        {
          __v_isVNode: true,
          __v_skip: true,
          type: 'span',
          props: null,
          key: null,
          ref: null,
          scopeId: null,
          children: 'blah blah',
          target: null,
```

There are several things that we need to explore:

1. why is using `h` working, but not raw text?
2. can we do some tricky stuff internally to handle raw text
3. maybe we should simplify the API for slots mounting options

The previous questions I asked still stands; let me know your use case, and what you think. I think we should let the use-cases drive development, as opposed to just supporting everything under the sun.

**Comment by lewishowles** [comment]
Thanks for taking a look. I’m not actually testing or asserting anything with slots.default(), it just means that my helper function (which checks that a slot has children) doesn’t work at all when running vue-test-utils, so parts of a component don’t render when they should.

The helper function allows me to have a slot, but also wrap it in some boilerplate HTML, css classes etc, which is all removed with a v-if in the case that slot isn’t there.

e.g. in its simplest form

```
<h2 v-if=“slotDefined(this, ‘title’)”><slot name=“title” /></h2>
```

Then it means the consumer doesn’t need to add the title tag, or care about what css is applied to it, but if there’s no title, there’s no empty title tag.

We could just use props, but slots always feels nicer.

**Comment by lmiller1990** [comment]
Can you share a test with the full helper? I am guessing this worked in Vue 2... I wonder if this is something Vue has changed, or something we have changed.

**Comment by lewishowles** [comment]
Yeah it did work in Vue 2. As I say I'm not sure if there's a better way to do it (I've never liked using `this` in the template), and if it ends up needing to be extra boilerplate used in tests that's fine.

Hopefully this covers everything. This is a bit long as the helper uses some of our other helpers, so for completeness I've just moved them all over so that it's as comparable as possible. The following does work when used inside a component, the title tag appears and disappears based on the title slot.

**Sample component:**
```vue
<template>
	<div>
		<p>Some primary content.</p>

		<div>
			<h2 v-if="slotDefined(this, 'title')" data-test="title">
				<slot name="title" />
			</h2>

			<p>Some sidebar content.</p>
		</div>
	</div>
</template>

<script>
// import { slotDefined } from '@/js/helpers/vue';

export default {
	name: 'sample-component',
	setup() {
		function slotDefined(instance, slotNames) {
			if (!instance || !isNonEmptyObject(instance.$slots)) {
				return false;
			}

			// Standardise the method of checking arrays versus strings
			if (typeof slotNames === 'string') {
				slotNames = [slotNames];
			}

			return slotNames.some(slotName => {
				// Slots are referenced by name in the $slots object.
				const slotReference = instance.$slots[slotName];

				if (!slotReference) {
					return false;
				}

				// Slots have to be called as functions to return their contents,
				// which is listed under children, regardless of whether the content is
				// text or other elements.
				let slot = slotReference();

				if (slot) {
					slot = slot[0];

					return !isEmpty(slot.children);
				}
			});
		}

		function isNonEmptyObject(object) {
			return objectLength(object) > 0;
		}

		function objectLength(object) {
			if (!isObject(object)) {
				return 0;
			}

			return Object.keys(object).length;
		}

		function isObject(variable) {
			return variable !== null && !Array.isArray(variable) && typeof variable === 'object';
		}

		function isEmpty(term) {
			return (
				['', undefined, null].includes(term) ||
				Array.isArray(term) && term.length === 0 ||
				isObject(term) && Object.keys(term).length === 0
			);
		}

		return { slotDefined };
	},
};
</script>
```

**Test file:**

```javascript
import { mount } from '@vue/test-utils';
import SampleComponent from '@/components/sample-component';

describe('sample-component', () => {
	describe('Initialisation', () => {
		test('A Vue instance is initialised', () => {
			const wrapper = mount(SampleComponent, {
				slots: {
					title: 'This is a title slot',
				},
			});

			console.log(wrapper.html());
			expect(wrapper.find('[data-test="title"]').element).toBeVisible();
		});
	});
});
```

In the test, the console.log prints out

```html
<div><p>Some primary content.</p><div><!--v-if--><p>Some sidebar content.</p></div></div>
```

**Comment by lmiller1990** [comment]
Oh, I fixed it: https://github.com/vuejs/vue-test-utils-next/pull/277
