### ISSUE TITLE
Testing components with Ava as test runner

### ISSUE THREAD

**Issue by vinayakkulkarni** [vuejs/vue-test-utils-next#226]
I'm trying to run tests using [Ava](https://ava.li), but I am getting this error

```sh
2:17 vinayak@Vinayaks-MacBook-Pro /Users/vinayak/Development/Personal/vue/v-ava
% nrt

> v-ava@0.1.0 test /Users/vinayak/Development/Personal/vue/v-ava
> ava


  Uncaught exception in specs/todo.spec.js

  specs/todo.spec.js:3

   2: import test from 'ava';
   3: import TodoApp from '../src/components/TodoApp.vue';
   4:

  /Users/vinayak/Development/Personal/vue/v-ava/src/components/TodoApp.vue:1
  <template>
  ^

  SyntaxError: Unexpected token '<'

  › SyntaxError: Unexpected token '<'
  › Object.<anonymous> (specs/todo.spec.js:3:1)

  ✖ specs/todo.spec.js exited with a non-zero exit code: 1
  ─

  1 uncaught exception
npm ERR! Test failed.  See above for more details.
```

Demo repo: https://github.com/vinayakkulkarni/v-ava

**Comment by afontcu** [comment]
Hi! 

This is interesting – we're using and suggesting Jest as the test runner to run Vue Test Utils, because [vue-jest](https://github.com/vuejs/vue-jest) makes it quite easy to set up the env.

Have you used ava with Vue Test Utils 1.X? If so, how did you handle the set up? We might have an answer from there.

Thank you!

**Comment by vinayakkulkarni** [comment]
> Hi! 
> 
> This is interesting – we're using and suggesting Jest as the test runner to run Vue Test Utils, because [vue-jest](https://github.com/vuejs/vue-jest) makes it quite easy to set up the env.
> 
> Have you used ava with Vue Test Utils 1.X? If so, how did you handle the set up? We might have an answer from there.
> 
> Thank you!

Yep. I have an example repo using ava + nuxt

https://github.com/vinayakkulkarni/nuxt-ava-e2e-unit-testing

Maybe we can have a similar repo like vue-jest called vue-ava for folks who want to avoid jest & facebook.

**Comment by afontcu** [comment]
Seems like the fix was quite simple? https://github.com/vuejs/vue-test-utils-next/issues/130#issuecomment-633801258 (haven't tested 😇)

**Comment by lmiller1990** [comment]
Let me know if the fix above isn't working. Anyway, I think this is probably a config issue, not a problem in VTU. Happy to help if you need it, but I will close the issue since this is for tracking VTU specific issues. Thanks!

**Comment by vinayakkulkarni** [comment]
@afontcu: I've tried that solution in the comment, doesn't work, I updated the source here - https://github.com/vinayakkulkarni/v-ava/blob/main/tests/setup.js

@mesqueeb: can you please share the reproducible repo?
