### ISSUE TITLE
Mocking Transitions

### ISSUE THREAD

**Issue by Ghitu** [vuejs/vue-test-utils-next#227]
Updating to from rc5 to rc7 break our test for the components that use transitions. How can we mock transitions or use transitionStub ?
Currently the documentation https://vue-test-utils.vuejs.org/v2/guide/transitions.html is empty for transitions.

Regards

**Comment by afontcu** [comment]
hi! Could you share your test so we can reproduce the issue? 🙌

**Comment by lmiller1990** [comment]
In beta 7 we mock transitions by default - I am a little confused by your issue.

I will write some docs for transitions before the end of the month.

You can opt out of the default transition stub, [see here](https://github.com/vuejs/vue-test-utils-next/blob/c3bee1853101fc6cb4180302c36fcede7a3f80fe/tests/mountingOptions/stubs.global.spec.ts#L330). You can also do this globally with `config`.

**Comment by lmiller1990** [comment]
Hi - any update on this?

**Comment by Ghitu** [comment]
@lmiller1990 We switch back to beta 5 for now. You can close it and I will write here again if necessary. Thank you!

**Comment by em2046** [comment]
> In beta 7 we mock transitions by default - I am a little confused by your issue.
> 
> I will write some docs for transitions before the end of the month.
> 
> You can opt out of the default transition stub, [see here](https://github.com/vuejs/vue-test-utils-next/blob/c3bee1853101fc6cb4180302c36fcede7a3f80fe/tests/mountingOptions/stubs.global.spec.ts#L330). You can also do this globally with `config`.

It works for me

---

jest.config.js
```js
  setupFiles: ['./tests/setup.ts']
```
tests/setup.ts
```typescript
import { config } from '@vue/test-utils';

config.global.stubs.transition = false;
```

---

https://next.vue-test-utils.vuejs.org/guide/advanced/transitions.html
Doc may need update

**Comment by DannyFeliz** [comment]
@em2046 Thank for your comment, it helped a lot 🥳

**Comment by deepansh96** [comment]
What worked for me was this
jest.config.js
```js
setupFiles: ["<rootDir>/jest.init.js"],
```

jest.init.js
```js
const transition = {
  template: "<div></div>",
}

config.global = {
 plugins: ..., //your plugins go here,
 mocks: ..., //your mocks go there,
 directives: ..., //your directives go here,
 stubs: {
   ...,
   ...,
   transition: transition,
  }
}
