### ISSUE TITLE
setData

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#228]
Ref: https://github.com/vuejs/vue-test-utils-next/pull/52

We should implement `setData` to minimize breaking changes from v1 -> v2.

**Comment by afontcu** [comment]
I'd like to tackle that :) It's been a while since I've added some lines here! 🚀

**Comment by lmiller1990** [comment]
First in first served 🚀 

I'll go ahead and assign you anyway :D

**Comment by afontcu** [comment]
Quick question – is this the expected behavior of `setData` when ran against a Composition API-based component?

```js
const Component = defineComponent({
  template: `<div>Count is: {{ count }}</div>`,
  setup: () => ({ count: ref(1) })
})
const wrapper = mount(Component)

expect(wrapper.html()).toContain('Count is: 1')

await wrapper.setData({ count: 2 })

expect(wrapper.html()).toContain('Count is: 2')
```

**Comment by brianboyko** [comment]
This issue is probably the main thing preventing our adoption of the Vue Composition API at my workplace.  Please keep me updated on this.  

I will say that the way that the way you've described setData working in the comment above is how I would expect it to work, yes.

**Comment by lmiller1990** [comment]
What, no, this is definitely *not* expected behavior. `setData` sets data in the `data` option (thus the name).

I don't think there is any way to access the value of ref/reactive inside of `setup`. 

Furthermore, why would you *want* to do this? Under what scenario can you arbitrarily assign variables to values assigned inside of `setup`?

**Comment by pikax** [comment]
> 2\. Figure out how best to support Composition API users:

For the composition-api you probably want to batch changes and await for the render.

```ts
function setSetupState(vm, state){
  merge(vm.$setupState, state)
  return Promise.resolve();
}
```

> * `setRef` and `setReactive`. Explicit, but a larger API surface (but I like this better, `setData` sets data, `setRef` sets a ref etc...

I would stay away from such APIs, this looks like when people try to mock `ref/reactive`.

---

Other way would be introducing a general method to change the `vm` properties and return a render promise. This method would update `$data` and `setup`

**Comment by lmiller1990** [comment]
Haven't seen `$setupState`, thanks. I wonder if there is any technical blockers, or is it as as simple as updating values on `$setupState`? Also, how about the `data` mounting option - that needs to work the same as `setData` to be consistent, which might be difficult since the `dataMixin` will not be called until after `setup` is processed.

I am still unsure of the best approach here. Feels like this is outside the scope of `setData` (to me). I wonder what everyone else thinks.

**Comment by afontcu** [comment]
Thanks all for your thoughts! Given the fact that `setData` is being ported here mostly to minimize breaking changes, here's a proposal (based on Lachlan's last comment suggestions):

- Implement `setData` to update `data()` as it happens in Vue 2.
- Make sure it does not update anything setup-related. It doesn't make much sense – starting with the method name.

We can then discuss about the fit for `setSetup` or any similar method, which is beyond the scope.

**Comment by brianboyko** [comment]
Ultimately, whether it's setData, setReactive, setRef, setSetupState, or whatever, this really is key functionality, that... well, I just don't know how to do.  That's the main thing - without a clear way to access (read & set) what's returned from setup() in the test suite, it's going to be hard to test things going forward. 

I think that what the Vue and the Test-Utils/Vue team need to coordinate on is documenting exactly how to upgrade tests based on the Options API to the composition API.

**Comment by ddzy** [comment]
Any progress?

**Comment by lmiller1990** [comment]
`setData` exists and works the same as in Vue Test Utils v1.

Are you asking for progress on the class components? Please open a new issue with your minimal reproduction if you think you found a bug. No need to bump up old issues - don't be afraid to open a new one if you think there's a problem in the library.
