### ISSUE TITLE
vue.defineComponent is not a function

### ISSUE THREAD

**Issue by federicomichela** [vuejs/vue-test-utils-next#231]
after installing @vue/test-utils@next and vue-jest@next, everytime I run a unit test I get the error 'vue.defineComponent is not a function' coming from node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2361:26.

**MyComponent.vue**
```vue
<template>
    <div>hello</div>
</template>

<script lang="ts">
export default {
    name: 'MyComponent'
}
</script>
```

**MyComponent.test.ts**
```js
import { mount } from "@vue/test-utils";
import MyComponent from '@/components/MyComponent/MyComponent.vue';

describe('MyComponent', () => {
    it('mounts', () => {
        const wrapper = mount(MyComponent);
        console.log(wrapper.html());
    });
})
```

**Comment by lmiller1990** [comment]
Can you please provide a reproduction?

This is a working example: https://github.com/lmiller1990/vtu-next-demo

**Comment by lmiller1990** [comment]
Hey, any update on this?

**Comment by lmiller1990** [comment]
Going to close this for inactivity. I am sure this is a config error, happy to help out if you have a repo.

**Comment by almost-no-one** [comment]
It's happened when i use
```
"vue": "^2.5.16",
"@vue/test-utils": "^2.0.0-rc.6",
```

```
TypeError: vue.defineComponent is not a function

    > 1 | import { shallowMount } from "@vue/test-utils";
        | ^
      2 | import EmailVerifyMessage from "@components/EmailVerifyMessage";
      3 | 
      4 | describe("EmailVerifyMessage.test.js", () => {

      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7939:26)
      at Object.<anonymous> (src/components/EmailVerifyMessage/EmailVerifyMessage.test.js:1:1)
```

**Comment by cexbrayat** [comment]
@almost-no-one Vue Test Utils v2 is for Vue v3 and won't work with Vue 2. You'll have to use VTU v1 if you want to keep using Vue 2, or use Vue 3.

**Comment by ksnyde** [comment]
> @almost-no-one Vue Test Utils v2 is for Vue v3 and won't work with Vue 2. You'll have to use VTU v1 if you want to keep using Vue 2, or use Vue 3.

@lmiller1990 I'm getting this with Vue3

**Comment by ksnyde** [comment]
Ok the problem was I was using `happy-dom` and not `jsdom` but it would be nice if could work in both

**Comment by jahangirQ** [comment]
I am using the  "vue": "^2.6.14", when I run this comond npm run watch can give the this type of errors.

[webpack-cli] Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- C:\xampp\htdocs\laratest\node_modules\vue-loader\dist\index.js
- C:\xampp\htdocs\laratest\node_modules\laravel-mix\src\components\Vue.js
- C:\xampp\htdocs\laratest\node_modules\laravel-mix\src\components\ComponentRegistrar.js 
- C:\xampp\htdocs\laratest\node_modules\laravel-mix\src\Mix.js
- C:\xampp\htdocs\laratest\node_modules\laravel-mix\setup\webpack.config.js
- C:\xampp\htdocs\laratest\node_modules\webpack-cli\lib\webpack-cli.js
- C:\xampp\htdocs\laratest\node_modules\webpack-cli\lib\bootstrap.js
- C:\xampp\htdocs\laratest\node_modules\webpack-cli\bin\cli.js
- C:\xampp\htdocs\laratest\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)        
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\xampp\htdocs\laratest\node_modules\vue-loader\dist\index.js:8:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\xampp\\htdocs\\laratest\\node_modules\\vue-loader\\dist\\index.js',
    'C:\\xampp\\htdocs\\laratest\\node_modules\\laravel-mix\\src\\components\\Vue.js',   
    'C:\\xampp\\htdocs\\laratest\\node_modules\\laravel-mix\\src\\components\\ComponentRegistrar.js',
    'C:\\xampp\\htdocs\\laratest\\node_modules\\laravel-mix\\src\\Mix.js',
    'C:\\xampp\\htdocs\\laratest\\node_modules\\laravel-mix\\setup\\webpack.config.js',  
    'C:\\xampp\\htdocs\\laratest\\node_modules\\webpack-cli\\lib\\webpack-cli.js',       
    'C:\\xampp\\htdocs\\laratest\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\xampp\\htdocs\\laratest\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\xampp\\htdocs\\laratest\\node_modules\\webpack\\bin\\webpack.js'

**Comment by cexbrayat** [comment]
@jahangirQ This is the repository for the test utils for Vue 3. If you are using Vue 2,  this won't work and you need to use the test utils v1, which are there https://github.com/vuejs/vue-test-utils
