### ISSUE TITLE
Mocking useRouter and useRoute

### ISSUE THREAD

**Issue by Stijn98s** [vuejs/vue-test-utils-next#242]
currently you can get the router and current route with `useRouter` and `useRoute` functions and are not accessible with `$router` and `$route` functions. The docs are therefor outdated with Vue 3 (https://vue-test-utils.vuejs.org/v2/guide/vue-router.html#using-a-mock-router). Is there a way to mock the router?

```
<script lang="ts">
import { defineComponent, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';

export default defineComponent({
  setup() {
    const router = useRouter();
    const route = useRoute();
  },
});
```

**Comment by cexbrayat** [comment]
Hi @Stijn98s 

I'm currently doing something like:

```ts
const mockRouter = createRouter({ history: createWebHistory(), routes: [] });
// fake router params
mockRouter.currentRoute.value.params = {
  userId: '12'
};
const wrapper = mount(User, {
  global: {
    plugins: [mockRouter],
    stubs: {
      RouterLink: RouterLinkStub
    }
  } as GlobalMountOptions
});
```

We spoke about having some kind of utils though.
cc @posva

**Comment by Stijn98s** [comment]
Thanks, that will definitely help!

Would be nice to just mock both :grin: to also easily assert that a specific route has been pushed and not to have to add all routes.

**Comment by cexbrayat** [comment]
I agree.
To check that a route has been pushed, I usually spy on `push`:

```ts
jest.spyOn(mockRouter, 'push').mockResolvedValue();
// ...
expect(mockRouter.push).toHaveBeenCalledWith(...);
```

**Comment by lmiller1990** [comment]
I am also using the mock strategy, either making a simple router myself with jest.fn or `jest.mock('vue-router', .....)`. 

We are working on a mock router, but it is not ready for usage yet.

**Comment by posva** [comment]
Working on something but still not released: https://github.com/posva/vue-router-mock

**Comment by Stijn98s** [comment]
Thanks for the Example!

i am using this for now.
```
const routerPushMock = jest.fn();

jest.mock('vue-router', () => ({
  useRouter: () => ({
    push: routerPushMock,
  }),
}));

describe('test', () => {
  beforeEach(() => {
    jest.resetAllMocks();
  });

  it('test router pushes, async () => {
    const wrapper = mount(Test);

    expect(routerPushMock).toBeCalledWith({ name: 'dashboard' });
  });
});
```

**Comment by lmiller1990** [comment]
Looks good. I'll close this one for now - no action needed. Keep an eye on https://github.com/posva/vue-router-mock

**Comment by friasmariano** [comment]
@cexbrayat That worked for me! Thanks, bro!
