### ISSUE TITLE
functionalComponentEmits not be used

### ISSUE THREAD

**Issue by gzponline** [vuejs/vue-test-utils-next#247]
new VueWrapper<T>(app, vm, setProps, **functionalComponentEmits**) functionalComponentEmits is aways **{}** and not change,
so I try to delete functionalComponentEmits, then run the test case, it is successful, so I want to ask the purpose of **functionalComponentEmits**.
whether we lose the test case for functionalComponentEmits?

**Comment by cexbrayat** [comment]
It looks like since this https://github.com/vuejs/vue-test-utils-next/commit/84d41efaf06313424ddcbacb480e5540cb425cd5 from @lmiller1990 it might not be necessary indeed.

@gzponline You can open a pull request to remove it if you want and we'll review it :)

**Comment by lmiller1990** [comment]
Good catch... we don't need this anymore, since we catch emits by wrapping functional components and intercepting the emits (see here https://github.com/vuejs/vue-test-utils-next/blob/951c5018698363d91e37fcadcef1f59d994c604b/src/mount.ts#L251)

Yep, a PR removing this would be great. Thanks!

**Comment by gzponline** [comment]
@cexbrayat  OK I will pull a request 😄 I tried to understand the purpose, but discover it is not used

**Comment by lmiller1990** [comment]
It's purpose is to be deleted 👍
