### ISSUE TITLE
mount causes "Cannot read property 'created' of undefined"

### ISSUE THREAD

**Issue by cyberb** [vuejs/vue-test-utils-next#250]
Test utils: @vue/test-utils": "^2.0.0-beta.9
Vue: "vue": "^3.0.0"

Calling mount causes "Cannot read property 'created' of undefined".
Calling shallowMount() works fine.

https://github.com/syncloud/platform/blob/98bf6a15da825533248df78b46d8b0ac9787de35/www/tests/unit/VueApp.spec.js

**Comment by cexbrayat** [comment]
Thank you for opening an issue.

Can you try to make a small reproduction of this problem so we can investigate it? It's hard to tell what's going on in a full application 🙂

**Comment by cyberb** [comment]
Ok, I am just learning, when you use mount you need to do something with components, I have a Menu component.
Setting this fixed the issue:
```
mount(VueApp, {
    global: {
      stubs: {
        Menu: true
      }
    }
  })
```
