### ISSUE TITLE
Vue tsx component type definition 'any' in typescript project issue when unit-testing.  

### ISSUE THREAD

**Issue by vutran6853** [vuejs/vue-test-utils-next#251]
**Problem**: I create vue 3 TSX project with default selection from vue cli, typescript, jest. When testing my component, it not show type define on my component in vs code intellisense. It show up as `any`. It not right since I am use typescript.

This issue just recently like 1 week or 2. Like 2 week ago, I create vue 3 typescript with jest enable. And it work and show up type define component on my IDE then. Now I just create new project vue 3. it not show type define on my component on my IDE. 

![Imgur](https://imgur.com/S0aTjW3.png)

**Reproducible Case**
- vs code IDE
- Create new vue 3 project with vue cli 
- select typescript, jest

Sample code with typescript, jest enable. create App.tsx and in example.spec.ts file with follow code:
```js
// App.tsx
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'App',
  data() {
    return {
      timer: null
    }
  },
  methods: {
    handleSendMessage() {
      console.log('handleSendMessage()')
    }
  },
  render() {
    return (
      <div>
        App component in tsx
      </div>
    )
  }
})
// example.spec.ts
import { shallowMount } from '@vue/test-utils'
import App from '@/App' // same problem if use relative import like ../../scr/App

describe('App.vue', () => {
    it('testing', () => {
      const wrapper = shallowMount(App)
      wrapper.vm.  // <--- after . my IDE would show all property on this component like all methods, data, etc. It do not show up here.
    })
})
```

Side note: it did work before on vue 3 project. I also test on vue 2 tsx project. it work fine there.

**Comment by cexbrayat** [comment]
Hi @vutran6853 

Thank you for opening this issue.

It is sadly complicated to have everything work with TypeScript, and we're trying to improve the support.

Can you try to update the `shims-vue.d.ts` file in your project with:

```diff
declare module '*.vue' {
  import type { DefineComponent } from 'vue'
+ const component: DefineComponent
- const component: DefineComponent<{}, {}, any>
  export default component
}
```

That may help to fix it, but you may have other issues.

**Comment by vutran6853** [comment]
> Hi @vutran6853
> 
> Thank you for opening this issue.
> 
> It is sadly complicated to have everything work with TypeScript, and we're trying to improve the support.
> 
> Can you try to update the `shims-vue.d.ts` file in your project with:
> 
> ```diff
> declare module '*.vue' {
>   import type { DefineComponent } from 'vue'
> + const component: DefineComponent
> - const component: DefineComponent<{}, {}, any>
>   export default component
> }
> ```
> 
> That may help to fix it, but you may have other issues.

Thank for reply. I try this code snippet. It does not help at all.

I did check recent change log in this repo out. I notice at mount.d.ts type change here. I thinking it something to do with this file. Not sure if relevant to the probelm? 
```js
export declare function mount(originalComponent: VueConstructor, options?: MountingOptions<any>): VueWrapper<ComponentPublicInstance<any>>;

```
if I change it to this
```js
export declare function mount(originalComponent: ComputedOptions, options?: MountingOptions<any>): VueWrapper<ComponentPublicInstance<any>>;

```
This happen:
![Imgur](https://imgur.com/DaDdYcR.png)

**Comment by cexbrayat** [comment]
Interesting. I think `VueConstructor` is for the support of component classes, right @lmiller1990 ?
Maybe adding this override first broke something, but that should have been caught by our tests 🤔
@pikax do you have an opinion on this?

**Comment by lmiller1990** [comment]
Yes, I added that for class components. Looks like I broke everything, rip.

I should have added a test but I am not sure why this wasn’t caught in the existing suite. We should fix this, good detective work OP.

**Comment by lmiller1990** [comment]
I am not getting this problem (using this actual code-base to test):

![Uploading image.png…]()

**Comment by vutran6853** [comment]
I recreate your example on another computer I have. I can't reproduce from your example too. It still have same problem. I taken fews screenshot might help track this issue.

![Imgur](https://imgur.com/zaOSV3n.png)
![Imgur](https://imgur.com/Gy0m86J.png)
![Imgur](https://imgur.com/GXAJQqo.png)

**Comment by lmiller1990** [comment]
Can you post your reproduction as a GH repo I can pull down?

**Comment by vutran6853** [comment]
Sure. Here is repo link: https://github.com/vutran6853/vue3-jest-issue

**Comment by lmiller1990** [comment]
I downgraded to beta.9, it works fine. You are right - I broke this in beta.10 with my class component typings. 

I will look into it.

**Comment by pikax** [comment]
You can fix this by running: `npm i vue-class-component@8.0.0-beta.4` 

The cause is that dependency is not shipped with `vue-test-utils`, I'll have a look on the types

**Comment by lmiller1990** [comment]
Right, that makes sense... derp. Thanks for picking this up @pikax.

We will fix the types and remove the class component dependency in the next release.
