### ISSUE TITLE
How to test Vue Plugins with custom options?

### ISSUE THREAD

**Issue by Duncank** [vuejs/vue-test-utils-next#255]
In VTU 1 I can use a global plugin with custom options:
```js
// install plugins as normal
localVue.use(MyPlugin, { options })
```

How can I do that with VTU2, as the documentation only shows to install a plugin by using `globals`:
```js
mount(Component, {
    global: {
      plugins: [Plugin]
    }
 })
```

**Comment by lmiller1990** [comment]
The docs need to be updated. You can pass an array with options, [see this test for an example](https://github.com/vuejs/vue-test-utils-next/blob/412c83fb52a0dc0c6bdce085dd4eb13f232e6505/tests/mountingOptions/global.plugins.spec.ts#L47).

Let me know if this is not working for you.
