### ISSUE TITLE
Error when mounting a single component

### ISSUE THREAD

**Issue by ferencbeutel4711** [vuejs/vue-test-utils-next#258]
Hello there,

when mounting a single component, as done previously using the vue2 setup, I now get the following exception logged when trying to call the html() method on the wrapper:

TypeError: Cannot read property 'parentElement' of null

The behaviour is equivalent for the text() method.

When I am mounting my whole app, and not just the component, the issue is gone.

Could you explain if this is desired behaviour and how to test a component in isolation now?

my component:

```
<template>
  <div>
    <span>Pls render me..</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'AsyncSetup',
  async setup() {
    return {};
  },
});
</script>

<style lang="scss" scoped></style>
```
and a simple test case:
```
describe('AsyncSetup.vue', () => {
  it('should text as expected', async () => {
    const wrapper = mount(AsyncSetup);
    await nextTick();
    await flushPromises();
    expect(wrapper.html()).toMatchSnapshot(); // exception happens here, during the hmtl() call
  });
});
```

Thanks & Best Regards

**Comment by ferencbeutel4711** [comment]
ah, please do note that the component has an async setup block - that is causing the issue. When I remove the 'async' keyword (and the aync call ofc) everything works as expected.

**Comment by cexbrayat** [comment]
@ferencbeutel4711 Thanks for the precision.

So this is probably simply an async problem: you need to use `flushPromises()` as explained in the docs, see https://vue-test-utils.vuejs.org/v2/guide/async-suspense.html#resolving-other-asynchronous-behavior

Let us know if that solves your issue :)

**Comment by ferencbeutel4711** [comment]
Hi and ty for your blazing fast response! I have tried to use nextTick() since I was under the impression that the Promise of the setup method should be known to vue since it is created inside of the framework, but it did not solve the issue. I have just tried flushPromises, but also with that, the issue still prevails.
I have updated the test to better reflect these tries.

**Comment by cexbrayat** [comment]
Ha yes OK, I understand now.

If your component has an async setup, you probably need to mount it in a "fake" async wrapper that has a `Suspense` (like you do in your real application I guess).

Something like:

```ts
const AsyncWrapper = defineComponent({
  components: { AsyncSetup },
  template: `<Suspense><AsyncSetup/></Suspense>`
});
```

And then `mount(AsyncWrapper)`

I agree that this is a bit tricky, and we were thinking of providing a `mountAsync` function, that would basically do that.
Does that help?

**Comment by ferencbeutel4711** [comment]
yes, this does indeed, when combined with a flushPromises() or nextTick() call (both work), lead to the desired result.

Would be def great to get support from the testing-utils for this, however I understand the current situation with the non-final Suspense api etc.

For now I have created this util class, maybe it might help someone else too:

```
export default class AsyncWrapper {
  static wrap(component) {
    return defineComponent({
      components: { [component.name]: component },
      template: `
        <Suspense>
        <${component.name} />
        </Suspense>`,
    });
  }
}
```

Thanks again for your support. This issue can be closed imo until you have decided on a way to move forward concerning async setup + Suspense

**Comment by cexbrayat** [comment]
Happy to hear your test works.

We are definitely waiting for Suspense to stabilize a bit before making a decision, so we are all currently doing the same thing.
Maybe we'll add a built-in function or add it in a plugin, we'll see.
