### ISSUE TITLE
Does not register eagerly emitted event

### ISSUE THREAD

**Issue by taigabrew** [vuejs/vue-test-utils-next#259]
## Describe the bug

`wrapper.emitted()` does not register an emitted event if it was called by `watch` with `immediate: true` option

## Reproduction

https://github.com/taigabrew/vue-test-utils-bug-48cb54ce

## System Info

- Operating System: macOS Catalina 10.15.7
- Node version: v14.15.1
- yarn version: 1.22.4
- Installed `vue-jest` version 5.0.0-alpha.6
- Installed `@vue/test-utils` 2.0.0-beta.10

**Comment by lmiller1990** [comment]
I investigated this. I thought it might be related to `setProps`, but this works:

```
  it('works with watch immediate: true', async () => {
    const Comp = defineComponent({
      props: {
        foo: {
          type: Number,
          default: 0,
        },
      },
      emits: ['update'],
      setup(props, { emit }) {
        watch(() => props.foo, val => {
          emit('update', val)
        }, { immediate: true })
      },
    })
    const wrapper = mount(Comp)
    await wrapper.setProps({ foo: 1 })
    console.log(wrapper.emitted()) // contains update with 1 as the payload
  })
```

But actually the problem is we are using a mixin that uses the `beforeCreate` lifecycle hook, which is AFTER `setup`: https://github.com/vuejs/vue-test-utils-next/blob/0b4f762790dc20e386ac69c8cb13f5bea43871f3/src/mount.ts#L401

If you do something like:

```js
setup(_, { emit }) {
  onMounted() {
    emit('update')
  }  
}
```

It will capture it. That could be a good work around. 

I cannot think of a good way to capture events from `setup` right now 🤔

**Comment by lmiller1990** [comment]
I am sure we have explored this before and I don't think there is any way to override `emit` in `setup` before the `beforeCreated` hook, so as far as I know this is not something we can currently solve.

Another work-around would be wrapping your component and using a mock function:

```js
  it.only('works with watch immediate: true', async () => {
    const Comp = defineComponent({
      props: {
        foo: {
          type: Number,
          default: 0,
        },
      },
      emits: ['update'],
      setup(props, { emit }) {
        watch(() => props.foo, val => {
          emit('update', val)
        }, { immediate: true })
      }
    })
    const onUpdate = jest.fn()

    const Wrap = {
      render() {
        return h(Comp, { onUpdate })
      }
    }

    const wrapper = mount(Wrap)
    // await wrapper.setProps({ foo: 1 })
    expect(onUpdate).toHaveBeenCalled()
  })
```

I think this is probably the best option right now, unless we can find a way to override `emit` and capture events in `setup` (before the `beforeCreate` lifecycle is executed and we can start tracking emitted events).

We might want to add this to the docs somewhere, I don't expect to solve this any time soon. At least there is a workaround.

**Comment by taigabrew** [comment]
Ok. I understood. Thank you for fast reply!
I think information about lifecycle hooks gotchas of `setup` use would help.

For now I am stick with workaround.
Once again, 
Thank you!
