### ISSUE TITLE
Sequence of .setValue(true) on multiple checkboxes is not stacking inputs checked state

### ISSUE THREAD

**Issue by taigabrew** [vuejs/vue-test-utils-next#261]
## Describe the bug

Sequence of `.setValue(true)` on multiple `input[type="checkbox"]`
is not stacking inputs checked state. It works kind of like inputs are of `type="radio"`

## Reproduction

https://github.com/taigabrew/vue-test-utils-bug-247ab5c2

## System Info

- Operating System: macOS Catalina 10.15.7
- Node version: v14.15.1
- yarn version: 1.22.4
- Installed `vue-jest` version 5.0.0-alpha.6
- Installed `@vue/test-utils` 2.0.0-beta.10

**Comment by lmiller1990** [comment]
Hi! Thanks for the reproduction, that was very useful.

This is *not* going to work, and here's why - there is no parent component listening for `update:modelValue` in this scenario. Normally you would have something like `<multiselect v-model="checkedItems" />` or something. In this case, there is no parent - `<Multiselect />` is at the top of the component hierarchy. It's like if you did

```js
import { createApp } from 'vue
const app = createApp(Multiselect)
```

Basically, `mount` is a very fancy `createApp`.

Here are some useful tricks you might like, that hopefully help you and also show off some of the cool features of Vue Test Utils. I can write you tests using the "wrapper" strategy (like I showed you in another issue).

Note it's also possible to get the emitted events of *any* component using `getComponent` not just the top level wrapper. Pretty cool. Note I renamed `<Multiselect>` to `<issue-261>` when I was debugging, but I used your exact source code.

```js
    it(''works!, async () => {
      const options = [
        { id: 'a', name: 'AAA' },
        { id: 'b', name: 'BBB' },
      ];
      const Wrapper = {
        components: { Issue261 },
        data() {
          return {
            options,
            checked: []
          }
        },
        template: `<issue-261 :options="options" v-model="checked" />`
      }

      const wrapper = mount(Wrapper)

      await wrapper.findAll('input')[0].setValue(true);

      // this is pretty cool
      expect(wrapper.getComponent(Issue261).emitted()['update:modelValue'][0][0]).toEqual(['a']);
      await wrapper.findAll('input')[1].setValue(true);
      expect(wrapper.getComponent(Issue261).emitted()['update:modelValue'][1][0]).toEqual(['a', 'b']);
      // grab `checked` from within `data` using `.vm`
      console.log(wrapper.vm.checked) // ['a', 'b']
    })
```

**Comment by taigabrew** [comment]
Oh! I get it! `getComponent` is pretty neat.
Thank you!
