### ISSUE TITLE
Not working with Vue 3.0.3 and latest <script setup>

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#263]
Related: https://github.com/vuejs/vue-jest/issues/304

Seems 3.0.3 breaks test utils. The return value either [here](https://github.com/vuejs/vue-test-utils-next/blob/ea21eb1dbfe292bf2c5215bece13a6189caeb519/src/mount.ts#L427) and [here](https://github.com/vuejs/vue-test-utils-next/blob/ea21eb1dbfe292bf2c5215bece13a6189caeb519/src/mount.ts#L429) are different to normal.

I am not sure if we should fix this right now, or wait for the `<script setup>` to stop been so experimental. It's important to let people try the latest features, but I am not sure `<script setup>` is meant for production yet - thoughts?

**Comment by lmiller1990** [comment]
Here is my analysis:

- new `<script setup>` introduced in 3.0.3. It breaks things.

Using `vue@3.0.2` and the same version of compiler-sfc with this component works:

```html
<script setup lang="ts">
// imported components are also directly usable in template
import { ref } from 'vue'

// write Composition API code just like in a normal setup()
// but no need to manually return everything
export const count = ref(0)
export const inc = () => { count.value++ }
</script>

<template>
  <button @click="inc">{{ count }}</button>
</template>
```

To make this work with the new `<script setup>` you just need to remove `export` from `count` and `inc` - those are automatically exposed. Doing that, then upgrading to `vue@3.0.3` breaks things.

If you do a log [here](https://github.com/vuejs/vue-test-utils-next/blob/ea21eb1dbfe292bf2c5215bece13a6189caeb519/src/mount.ts#L427) on `vue@3.0.2` you get:

```
vm { __emitted: {} }
```

And [here](https://github.com/vuejs/vue-test-utils-next/blob/ea21eb1dbfe292bf2c5215bece13a6189caeb519/src/mount.ts#L429):

```
App { count: [Getter/Setter], inc: [Getter/Setter], __emitted: {} }
```

With `vue@3.0.3`:

```
vm { __emitted: {} }
```

and:

```
App {}
```

Seems [this line](https://github.com/vuejs/vue-test-utils-next/blob/ea21eb1dbfe292bf2c5215bece13a6189caeb519/src/mount.ts#L429) is where things break. `vm.$refs[MOUNT_COMPONENT_REF]` is *not* returning the expected `vm`.

**Comment by martinszeltins** [comment]
> Related: [vuejs/vue-jest#304](https://github.com/vuejs/vue-jest/issues/304)
> 
> Seems 3.0.3 breaks test utils. The return value either [here](https://github.com/vuejs/vue-test-utils-next/blob/ea21eb1dbfe292bf2c5215bece13a6189caeb519/src/mount.ts#L427) and [here](https://github.com/vuejs/vue-test-utils-next/blob/ea21eb1dbfe292bf2c5215bece13a6189caeb519/src/mount.ts#L429) are different to normal.
> 
> I am not sure if we should fix this right now, or wait for the `<script setup>` to stop been so experimental. It's important to let people try the latest features, but I am not sure `<script setup>` is meant for production yet - thoughts?

I am actually using the new `<script setup>` syntax in a production app already. So I think we should fix it now. The RFC was well discussed and approved by the community.

**Comment by afontcu** [comment]
new `<script setup>` implementation is literally listed under "Experimental Features" on release docs: https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#experimental-features

**Comment by lmiller1990** [comment]
While I prefer to be conservative generally, I think the right move is to support this RFC as soon as possible. If people cannot try it out, it'll be difficult for Evan and co. to get feedback. Some people might get surprised when they update from 3.0.2 to 3.0.3 and things break... well, that is the cost of using an experiemental feature. 🤷‍♂️ #264 should not impact anyone using the regular options or composition APIs.

**Comment by lmiller1990** [comment]
Users wanting to use this feature should install the latest `vue-jest`: https://github.com/vuejs/vue-jest/releases/tag/v5.0.0-alpha.7. Run `yarn add vue-jest@next`.

**Comment by lmiller1990** [comment]
They are both out.

- vue-jest: https://github.com/vuejs/vue-jest/releases/tag/v5.0.0-alpha.7
- test-utils: https://github.com/vuejs/vue-test-utils-next/releases/tag/v2.0.0-beta.12

@martinszeltins give this a try and see how you go. It works for the basic example given in the RFC, I do not have a large code-base using `<script setup>` to test this more thoroughly.

**Comment by afontcu** [comment]
> I think the right move is to support this RFC as soon as possible

Agree on that! Just wanted to point out that these are, in fact, experimental features, so even if we decide to provide support as soon as possible, people need to be aware what's the current situation with them, and expect some breaking changes from time to time 😉 

Nice work tracking down the issue!

**Comment by chojnicki** [comment]
@lmiller1990 Are You sure this is 100% fixed? I'm missing something?

I was not able to use/mock custom store build with composition api. No matter what I did, my store was undefined, but it works on live. So I just did `console.log('wrapper.vm')`. And my store does not exist in component vm even that my IDE/TS correctly autocomplete it.

So I added just dummy consts data, and they also do not show up. Then I changed my component to standard exported setup() and voila - it works. So for me there is still problem with `<script setup>` syntax.

I'm missing some simple option on mount() or something? I spend literally hours trying to debugging this and find solution in issues, docs etc.


Reproduction code:

```
import { mount } from '@vue/test-utils'
import Model from '@/components/Demo.vue'

it('demo', () => {
  const wrapper = mount(Model)
  console.log(wrapper.vm)
})
```

This works:
```
<script lang="ts">
export default {
  setup() {
    const demo = () => {
      console.log('demo')
    }
    const demo2 = 'demo2'

    return {
      demo, demo2,
    }
  },
}
</script>
```
```
  console.log
    {
      demo: [Getter/Setter],
      demo2: [Getter/Setter],
      hasOwnProperty: [Function (anonymous)]
    }
```


This does not:

```
<script setup lang="ts">
const demo = () => {
  console.log('demo')
}
const demo2 = 'demo2'
</script>
```


```
  console.log
    { hasOwnProperty: [Function (anonymous)] }
```

**Comment by lmiller1990** [comment]
I think this is an intended part of the `<script setup>` RFC. It's worded quite confusingly, but [see this part](https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md#closed-by-default).

> ... therefore a component using <script setup> will be closed by default. That is to say, its public imperative interface will be an empty object ...

Follow up question: if you do `console.log(wrapper.html())`, does it show the HTML?

**Comment by chojnicki** [comment]
Yes, it does. Ok so I guess I'm using `expect()` with `<script setup>` wrong?

`expect(wrapper.vm.demo).toHaveBeenCalled()`

It of course works fine without setup.

**Comment by lmiller1990** [comment]
You are definitely not the first person to try this: https://github.com/vuejs/vue-test-utils-next/issues/435

Slight tangent, it feels like a bit of a code smell if you need to `expose` internals for testing - you cannot make an assertion based on the DOM state?
