### ISSUE TITLE
Expose typings for Plugins

### ISSUE THREAD

**Issue by posva** [vuejs/vue-test-utils-next#269]
I think it would be helpful to expose the `Instance` type so plugins can type the argument (https://vue-test-utils.vuejs.org/v2/guide/plugins.html#writing-a-plugin) as well as adapting the `install` function to infer the options parameter:

```ts
    install(handler: (instance: Instance) => Record<string, any>, options?: Record<string, any>): void;
```

Similar to https://github.com/vuejs/vue-next/pull/2758

**Comment by lmiller1990** [comment]
Oh cool, this is a good idea. I will give this one at try.

**Comment by lmiller1990** [comment]
Just to confirm @posva, are you referring to 

- `plugins` as in `app.use`, so basically just do the same as #2758 
- as opposed to the plugin system that only exists in VTU for extending `wrapper`? (I don't see what you mean if you are referring to VTU plugins, which we should probably rename `extensions` to avoid confusion with Vue `plugins`

**Comment by lmiller1990** [comment]
Edit: Seems VTU plugins was not actually working properly in the first place, fixed: https://github.com/vuejs/vue-test-utils-next/pull/276

Are you using this for the mock router? Sorry I did not have time to work on that lately... :(

**Comment by posva** [comment]
> the plugin system that only exists in VTU for extending wrapper (which you linked to)?

Yes!
Specifically, one should be able to do something like this:

```ts
function myPlugin(wrapper: Instance, options: { n: number }) {}

// @ts-error
config.plugins.VueWrapper.install(myPlugin, {n: true})

```

That's why I was referring to https://github.com/vuejs/vue-next/pull/2758/files

**Comment by lmiller1990** [comment]
Cool, I can update the typings on top of #276.

No problem, I will try test the mock router soon (or have a hack on it if it's not ready yet).

**Comment by posva** [comment]
Sorry for the delay! I submitted a PR
I'm finishing up an initial 0.0.1 version for the mock but at the end I don't think I need even need the plugin API. But It could be useful in the future to add functions to the wrapper or even the router!
