### ISSUE TITLE
setValue() is not work well 

### ISSUE THREAD

**Issue by HomyeeKing** [vuejs/vue-test-utils-next#270]
### Subject of the issue

Describe your issue here.
```js
	it("should bind value to input by v-model", async () => {
		const textInput = wrapper.find('input[type="text"]');
		await textInput.setValue("some value");
		expect(textInput.element.innerHTML).toBe("some value");
	});
```
### Steps to reproduce
1. run the test
2. throw the error message to console shows:  
![image](https://user-images.githubusercontent.com/49113249/101888415-0f907700-3bd9-11eb-963b-72b9bb8261a5.png)
![image](https://user-images.githubusercontent.com/49113249/101888498-29ca5500-3bd9-11eb-92eb-d04cb7aae008.png)

![image](https://user-images.githubusercontent.com/49113249/101888480-23d47400-3bd9-11eb-9023-c7ac7de7ea69.png)

Tell us how to reproduce this issue. Please provide a working and simplified example.

### Expected behaviour
pass the test 
What should happen?

### Actual behaviour
throw error as you can see 
What happens instead?

### Possible Solution
maybe the API  is deprecated but the official doc is not updated, all of above is from doc example
What are the alternative solutions? Please describe what else you have considered?

**Comment by cexbrayat** [comment]
Hi @HomyeeKing 

You should use `element.value` and it will work.
To make TS happy, you need to indicate that the input is of type `HTMLInputElement`:

```ts
it("should bind value to input by v-model", async () => {
  const textInput = wrapper.find<HTMLInputElement>('input[type="text"]');
  await textInput.setValue("some value");
  expect(textInput.element.value).toBe("some value");
});
```

Let us know if that fixes your test

**Comment by HomyeeKing** [comment]
@cexbrayat  I've update the VTU to the lastest version which is @^2.0.0-beta.12, still not work, here is the console 

![image](https://user-images.githubusercontent.com/49113249/101926954-da068080-3c0e-11eb-8ea7-eebf5cf0e8fe.png)
![image](https://user-images.githubusercontent.com/49113249/101927000-ec80ba00-3c0e-11eb-84d6-8b74adb66cbe.png)

**Comment by cexbrayat** [comment]
I think the issue is not with `setValue` here? 
We use it in pretty much all our Vue 3 projects with latest VTU and we have no issue, but we don't use TSX.

I'm not even sure the TSX support for Vue 3 in the Vue CLI is ready. Are you using ButtonTSX somewhere in your application? Does it work without error at runtime? I wouldn't be surprised if that was throwing the same error at runtime.

**Comment by HomyeeKing** [comment]
@cexbrayat   em..  actuallly  it's been a while since I  work on vue3 with tsx, TSX is support for vue3? Yes and u can verify in the repo above(you can pull the lastest code), it works fine in App.vue as child compoent ,  

since vue with TS is a trend , I think it necessary to make VTU work well with TSX,   

also it's wired that the IDE can infer the api correctly but throw an error in the runtime

**Comment by cexbrayat** [comment]
Happy to hear that TSX is already working (I was under the impression that jsx-next was still a WIP).

If I checkout your master branch, and serve the app, I see the exact same error at runtime when I enter a value in your input:
```
Uncaught TypeError: el._assign is not a function
    created runtime-dom.esm-bundler.js:879
```

So this is not a problem with VTU-next, but with either:
- the TSX/JSX support (most likely)
- Vue core

I suggest you open an issue on jsx-next maybe?

**Comment by HomyeeKing** [comment]
@cexbrayat  it works now , all of a sudden ...   it' necessary to update the 1.x doc to give a tip to redirect to beta version  (plus I've send a PR)
![image](https://user-images.githubusercontent.com/49113249/102053712-25917800-3e23-11eb-943b-34ce541de15b.png)

**Comment by lmiller1990** [comment]
Seems like this is fixed?

**Comment by ddzy** [comment]
Any progress?

**Comment by lmiller1990** [comment]
Do we even have a problem? It looks like this was resolved and closed.

If you have a problem with `setValue`, please open a new issue with your reproduction. Thanks!
