### ISSUE TITLE
Can not import component which using 3rd library

### ISSUE THREAD

**Issue by HomyeeKing** [vuejs/vue-test-utils-next#280]
I'm using Ant-Design-Vue in my project, I want to do some test about it , but can't even run it .

here is the repo：  https://github.com/HomyeeKing/learn-test

steps to reproduction:
- clone the repo
- yarn && yarn test:unit ant

you will see an error about can't  import component's css file

`SyntaxError: Cannot use import statement outside a module`

**Comment by lmiller1990** [comment]
The problem is related to ant-design and how it is set up. Jest does *not* know about es modules (eg, `import` and `export` by default - only commonjs, which is the `require` syntax. Ideally ant-design should be building a commonjs module. 

Anyway, this can be worked around, let me try and configure it for you.

**Comment by lmiller1990** [comment]
Ok, here you go: https://github.com/HomyeeKing/learn-test/pull/1

This should work.

Problem is config, not test utils. ANT team should provide a cjs build for node.js.

**Comment by HomyeeKing** [comment]
@lmiller1990  thanks for your time

**Comment by HomyeeKing** [comment]
@lmiller1990  there's a problem, I have two files with same name , one is `Button.vue` ,another is`Button.tsx`
I import it to `Button.spec.ts` as `import Button from 'xx/Button'`
 when click the file path, it jump to the `tsx` one , but the tested one is `Button.vue`

**Comment by lmiller1990** [comment]
I am not sure but I don't have time to fix your configuration right now, sorry. You could just type the full path, such as `xx/Button.tsx`.
