### ISSUE TITLE
TypeError: Object(...) is not a function with Karma Testrunner

### ISSUE THREAD

**Issue by Botz** [vuejs/vue-test-utils-next#288]
I am trying to migrate a vue library to vue3. But i have a problem with the tests. The Library works with nbw and karma as testrunner.

If i try to import `mount` and mount a component i get the following error.

```
  TypeError: Object(...) is not a function
      at Context.<anonymous> (webpack:///tests/index.test.js:17:1 <- tests/index.test.js:68921:80)
```

https://github.com/Botz/vue-konva/tree/feature/vue3-tests

I am not sure if it is a configuration problem or not

**Comment by lmiller1990** [comment]
It looks like it is using the browser build by default (where VueTestUtils is an iife). It looks like your toolchain is loading the [browser build](https://github.com/vuejs/vue-test-utils-next/blob/master/package.json#L6) by default. How does this toolchain work? I do not see a webpack config, for example, but importing the [es bundler build](https://github.com/vuejs/vue-test-utils-next/blob/0887d4364a71ea9a1ae3258e95bc84f444cff066/package.json#L9) seems to work correctly.

I changed the import to `import { mount } from '@vue/test-utils/dist/vue-test-utils.esm-bundler';` and it gets further. It says:

```
TypeError: Cannot read property 'getStage' of undefined
```

I think it could not find `const stage = wrapper.vm.$refs.stage`.

**Comment by Botz** [comment]
I am not very familar with this kind of toolchain. 
But the tests are running now. 
I also had to use the esm-bundler version from the vue package.

thx for helping me out
