### ISSUE TITLE
docs: Plugins section jumps into Wrappers without explaining them before

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next#303]
I noticed that [Plugins](http://localhost:8080/vue-test-utils-next-docs/guide/plugins.html#plugins) is the first time in docs where we mention `VueWrapper`, `WrapperAPI` and so on. 

Should they be mentioned before, in a standalone section? Should we explain them here? Should we just link to somewhere, and assume anyone reading Plugins is an advanced-enough user?

**Comment by lmiller1990** [comment]
This should be okay for now: https://github.com/vuejs/vue-test-utils-next/commit/fdb25812f273d5605092df10f4c9b31a9aaf7150
