### ISSUE TITLE
Jest is no longer able to spy on methods

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-test-utils-next#309]
I think the wrapper no longer exposes methods on the prototype or something, because when I want to spy on a method (e.g. `wrapper.vm.send`) with `jest.spyOn(wrapper.vm, 'send')` Jest throws a type error: `TypeError: object.hasOwnProperty is not a function`.

This makes it impossible to test some component internals (like methods that format data and send it off to a state machine, in this case).

**Comment by cexbrayat** [comment]
Hi there! Thank you for opening an issue.

That's weird, I have similar code in all my apps, and it does work well for me 🤔

Can you provide us a small reproduction so we can investigate?

**Comment by TheDutchCoder** [comment]
Sure!
I use state machines (xstate) in my components which is a composable that exposes a send method like so:

```js
setup (props) {
    const { send, state } = useMachine(assetsMachine)

    const doThing = () => {
      send('hello')
    }

    return {
      send,
      doThing,
    }
```

However, trying to spy on send yields that error, even though `wrapper.vm.send` logs as a function.
I have a feeling the issue lies with composable functions.

**Comment by cexbrayat** [comment]
Can you push your repro on a Githup repo please? We'll need to know how your project is set up.

Ideally just a small component like this one, and a failing unit test with the error 👍

**Comment by TheDutchCoder** [comment]
I'll try to create a codesandbox, it would take hours extracting this from my project.

**Comment by TheDutchCoder** [comment]
That's not going to work. CodeSandbox can't even run Jest at the moment.

The issue seems to be that wrapper.vm is a Proxy object and jest.spyOn can't find the method on wrapper.vm as it doesn't have a `hasOwnProperty` method.

**Comment by cexbrayat** [comment]
I managed to repro your issue, but I don't have an obvious fix right now. This may need some thinking.

**Comment by TheDutchCoder** [comment]
Thanks a ton, it's driving me up the wall haha!

**Comment by per-toyra-stratsys** [comment]
We're having the same issue. Is there a time plan when this fix will be released?

**Comment by cexbrayat** [comment]
I have a fix but it's blocked by a change we need in Vue itself (https://github.com/vuejs/vue-next/pull/3105).
So we need Evan to take a look at that PR and merge it, which should hopefully happen in the next weeks.
We can then land the fix and cut a release shortly after.
