### ISSUE TITLE
Code suggestions

### ISSUE THREAD

**Issue by nandi95** [vuejs/vue-test-utils-next#369]
I have couple suggestions I would like to propose to improve developer experience when contributing:

 -  [x] I noticed that `VueWrapper` has all the methods of `DOMWrapper`? Why not introduce an interface so it's clear they share functionality or perhaps a base wrapper to share logic eg.: `attributes()` has the same signature and vue wrapper don't have to use the dom wrapper as it has the same element getter.
 - [x] turn on strict options in tsconfig
 -  [x] go beyond the prettier's typescript rules. There are lot of extra [rules](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules) that promote consistency and better code quality that isn't utilised at the moment. eg: enforce consistent type imports

**Comment by cexbrayat** [comment]
Hi @nandi95 

Sure, I think we all want that and just lacked the time to improve the codebase as we were trying to fix all the issues incoming and being ready for v2 stable release. You can definitely experiment with a shared interface and we'll see. Strict config has been on my personal todolist for a while. Turning it on in one single PR requires many changes, so I was fixing one file at a time and opening a PR with the changes. But I haven't been through all the code, so your help is definitely welcome here! Same for eslint! Thank you for offering your help.

**Comment by nandi95** [comment]
Yes, I can help.
As for the eslint and strict options. What would be the best way to go about this?
One pull request per option/rule? Or one PR with separate commits per option/rule?

Have you got preferences on eslint rules? Or shall I just turn them on as I see fit, then they can be discussed in the PR?

**Comment by cexbrayat** [comment]
I think separate PRs are a good way to go, so we can merge them as soon as they're reviewed.

And yes, turn the option as you see fit, or if you want to check first, you can add a list here and we can discuss. Whatever you prefer!

**Comment by lmiller1990** [comment]
We had a shared interface at one point but it was removed - I don't remember why exactly but there was some complexity that either couldn't be solved or made the code much more complex. If you can find a way to have a shared interface, I think that's be fine. 

Personally I am more focused on actual big fixes but general improvements, as well as the quest for strict mode, are always welcome.
