### ISSUE TITLE
Plugins one time setup

### ISSUE THREAD

**Issue by nandi95** [vuejs/vue-test-utils-next#373]
I'm working on a component library that sets some global config on the `globalProperties`.
At the moment I have set this config in every mount option so it's available in the component.

Is there currently a way to set up this global config 1 time before all tests?
I guess this also applies if I were to use lets say a vue plugin that adds a global directive and doesn't have to be imported in the components.

In the docs there's an example for the [router](https://vue-test-utils.vuejs.org/v2/guide/vue-router.html#with-a-real-router) and vuex using the `global.plugins` but that's still has to be set up at every mount. (altough those 2 are might meant to be specific to the tested component so they make more sense...)

**Comment by afontcu** [comment]
Hi!

I think this was fixed on https://github.com/vuejs/vue-test-utils-next/pull/365

**Comment by nandi95** [comment]
That is exactly what I was looking for. Thanks!
Side question does the config [global](https://github.com/vuejs/vue-test-utils-next/blob/master/src/config.ts#L7) has to be `Required<GlobalMountOptions>` ? can we not keep it partial?
@afontcu

**Comment by afontcu** [comment]
>  Side question does the config [global](https://github.com/vuejs/vue-test-utils-next/blob/master/src/config.ts#L7) has to be `Required<GlobalMountOptions>` ? can we not keep it partial?

Yeah, I'd say we could (should?) keep it partial 🤔
