### ISSUE TITLE
Enforce commit message format

### ISSUE THREAD

**Issue by nandi95** [vuejs/vue-test-utils-next#383]
Husky has already been set up which can be used in the `pre-commit` hook to lint the commit messages. With that an automated solution should be added to ensure commit consistency.

For example:
https://github.com/conventional-changelog/commitlint

This down the line perhaps can work in conjunction with some automated release process.
https://semantic-release.gitbook.io/semantic-release/
I'm mentioning this because if this is planned then the commit lint should validate to match the semantic release's requirements

context: https://github.com/vuejs/vue-test-utils-next/pull/372#issuecomment-778218116

**Comment by afontcu** [comment]
Hi! My two cents:

I'm quite in favor of setting a tool such as semantic-release, but not sure about commitlint because it creates a burden for contributors. Instead, I'd simply set a squash&merge strategy for the repository, and let maintainers choose the right final commit message.

**Comment by lmiller1990** [comment]
I agree with @afontcu - many code-bases I've worked on have had strict commit messages formats, I think it introduces more problems (burders everyone) than problems it solves (none, really).
