### ISSUE TITLE
How to assign value in compositionAPI correctly?

### ISSUE THREAD

**Issue by linkscope** [vuejs/vue-test-utils-next#402]
I didn't find any good way to assign value in compositionAPI, now I konw that this is a async task

### pass
```js
const wrapper = shallowMount(App)
wrapper.vm.undoList = [1, 2, 3]
setTimeout(() => {
    const count = wrapper.find('[data-test="undoListCount"]')
    expect(count.text()).toBe('3')
    done()
}, 1000)
```
### fail
```js
const wrapper = shallowMount(App)
wrapper.vm.undoList = [1, 2, 3]
const count = wrapper.find('[data-test="undoListCount"]')
expect(count.text()).toBe('3')
```

does it have anthor more elegant solution? 
I'm really not sure waht the significance is setData and initial data in Vue3

**Comment by cexbrayat** [comment]
You can check out the documentation about async behavior [here](https://next.vue-test-utils.vuejs.org/guide/advanced/async-suspense.html#a-simple-example-updating-with-trigger)

You'll need to call `await nextTick()` after setting `undoList`.
Let us know if that fixes it.

**Comment by linkscope** [comment]
> You can check out the documentation about async behavior [here](https://next.vue-test-utils.vuejs.org/guide/advanced/async-suspense.html#a-simple-example-updating-with-trigger)
> 
> You'll need to call `await nextTick()` after setting `undoList`.
> Let us know if that fixes it.

Thanks your answer
