### ISSUE TITLE
Add event union type to trigger method

### ISSUE THREAD

**Issue by nandi95** [vuejs/vue-test-utils-next#415]
This will give us nice, typehints of the possible values.

The dom-event-type already includes the keys that can be triggered.
would `as const` and `keyof` work to extract the keys from that package?

Are some of it needs to be filtered out?

**Comment by cexbrayat** [comment]
That sounds like a nice idea, go ahead with a PR 👍

**Comment by nandi95** [comment]
[Linked issue](https://github.com/eddyerburgh/dom-event-types/issues/14)

**Comment by lmiller1990** [comment]
We can probably inline the entire dom-event-types lib? No real point having a static list of events as a dependency, and then we can improve the types and the such. What do you think?

**Comment by nandi95** [comment]
That would work as a quick fix for sure. My preference that it's a dependency that others can pull in too. However that library doesn't seem to be active anymore so I'm not sure.

**Comment by lmiller1990** [comment]
That lib is actually by one of the original maintainers of Test Utils and has moved on from the front-end world - I don't expect it will see an update or release.
