### ISSUE TITLE
data override in the mount function

### ISSUE THREAD

**Issue by yinqunbo** [vuejs/vue-test-utils-next#421]
**question**
when I use reactive to define data, the data defined by the option in the mount function cannot overwirte the data in the component, Is there something wrong with the way I use it?

**code**
```javascript
// WChild Component
<div class="data2">{{data2}}</div>
setup() {
    const state = reactive({
        data1: '1',
        data2: '2'
    })
    return {
        ...toRefs(state)
    }
}
// test.spec.ts
const wrapper = mount(WChild, {
    data() {
        return {
            data2: '3'
        }
    }
})
console.log(wrapper.find('.data2').text())    // data2 is still 2
```

**Comment by yinqunbo** [comment]
Overriding data seems to work only with options API

**Comment by cexbrayat** [comment]
Hi @yinqunbo 

`data` works only if you use `data` in your component.
If you use the composition API, you need to do something like this https://github.com/vuejs/vue-test-utils-next/discussions/346#discussioncomment-333847
