### ISSUE TITLE
Using findComponent on a functional component yields an empty-ish VueWrapper

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next#427]
From #408.

```js
const Foo = () => h('div')

const wrapper = mount(Foo)

console.log(wrapper.findComponent(Foo))
/*
yields

    VueWrapper {
      wrapperElement: undefined,
      __app: null,
      rootVM: undefined,
      componentVM: null,
      __setProps: undefined
    }

*/
```

and then any method that relies on `vm` or similar fails (being that `exists()` or `text()` or…).

This (might) be an expected limitation... no instance, so `findComponent` won't work.

**Comment by lmiller1990** [comment]
I think this is a limitation we will need to live with. Might be good to document it.

**Comment by lmiller1990** [comment]
Docs: https://github.com/vuejs/vue-test-utils-next/commit/a6146a8c91a7ce5aa7fac716a4e0f8387bc95429
