### ISSUE TITLE
emitted() not catching component events

### ISSUE THREAD

**Issue by nekosaur** [vuejs/vue-test-utils-next#436]
Using `vue@3.0.2` and `@vue/test-utils@2.0.0-beta.8`, the following works fine.

```ts
import { mount } from '@vue/test-utils'
import { defineComponent, h } from 'vue'

const Foo = defineComponent({
  name: 'Foo',
  emits: ['foo'],
  setup (_, ctx) {
    return () => h('div', {
      onClick: () => {
        ctx.emit('foo', 'bar')
      },
    }, 'hello world')
  }
})

test('uses mounts', async () => {
  const wrapper = mount(Foo)

  await wrapper.trigger('click')

  console.log(wrapper.emitted())

  expect(wrapper.emitted('foo')).toHaveLength(1)
})
```

```bash
PASS  src/App.spec.ts
  ✓ uses mounts (21 ms)

  console.log
    { foo: [ [ 'bar' ] ] }

      at src/App.spec.ts:21:11

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.29 s
Ran all test suites.
```

But using `vue@3.0.7` and `@vue/test-utils@2.0.0-rc.2` results in this

```bash
 FAIL  src/App.spec.ts
  ✕ uses mounts (18 ms)

  ● uses mounts

    expect(received).toHaveLength(expected)

    Matcher error: received value must have a length property whose value must be a number

    Received has value: undefined

      21 |   console.log(wrapper.emitted())
      22 |
    > 23 |   expect(wrapper.emitted('foo')).toHaveLength(1)
         |                                  ^
      24 | })
      25 |

      at src/App.spec.ts:23:34
      at fulfilled (src/App.spec.ts:5:58)

  console.log
    { click: [ [ [MouseEvent] ] ] }

      at src/App.spec.ts:21:11

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.307 s
Ran all test suites.
```

A cursory investigation seems to point to the fact that this call https://github.com/vuejs/vue-test-utils-next/blob/master/src/emit.ts#L33 gets made _before_ this one https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/renderer.ts#L442 which results in the test utils value being overwritten by `undefined`.

**Comment by lmiller1990** [comment]
Good detective work. Are you interested in taking a stab at fixing this? Both rc-1 and rc-2 had some changes around capturing events, fixing some bugs, but also introducing others.

This seems like a super basic use case, I am really surprised we do not have a test around this.

**Comment by lmiller1990** [comment]
This was broken by Vue 3.0.7.

**Comment by lmiller1990** [comment]
Seems to fix it: https://github.com/vuejs/vue-test-utils-next/pull/437

@nekosaur if you can quick review and/or try it out in your app to see if it fixes your problem?
