### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by AtishaGarinMchd** [vuejs/vue-test-utils-next#441]
```
$ yarn pack @vuejs/vue-test-utils-next
yarn pack v1.22.5
warning package.json: No license field
```

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue-test-utils-next/blob/9e8d0b2da1c4141ddb0887933e598dd52c046929/package.json#L4

???

**Comment by AtishaGarinMchd** [comment]
Indeed the field is provided - implemented npm check and its warn message is wrong (similar issue [here](https://github.com/enzymejs/enzyme/issues/1729)).
For reasons my legal department prefers having a proper license file. 
Having a license such as v1.0 is preferrable https://github.com/vuejs/vue-test-utils/blob/dev/LICENSE. 
I suppose it will populate Github Code page right hand side 'About' field too.

**Comment by LinusBorg** [comment]
That's a valid point, this is an oversight on our part and we'll add it. 

Thanks!
