### ISSUE TITLE
emitted Collect content that should not be collected

### ISSUE THREAD

**Issue by cuixiaorui** [vuejs/vue-test-utils-next#444]
```js  
it.only('should does not have click', async () => {
    const Foo = defineComponent({
      name: 'Foo',
      emits: ['click', 'foo'],
      setup(_, ctx) {
        return () =>
          h(
            'div',
            {
              onClick: () => {
                ctx.emit('foo', 'bar')
              }
            },
            'hello world'
          )
      }
    })

    const wrapper = mount(Foo)
    await wrapper.trigger('click')
    console.log(wrapper.emitted()) //  { foo: [ [ 'bar' ] ], click: [ [ [MouseEvent] ] ] }
    expect(wrapper.emitted('foo')).toHaveLength(1)
  })
```
The example of the above

expect return **{foo:[['bar']]}** when call emitted()

but actual return  **{ foo: [ [ 'bar' ] ], click: [ [ [MouseEvent] ] ] }**

This may be related to the version of the vue, because do not have this problem when 3.0.4 version

version：
vue: v3.0.7
vtu: 2.0.0-rc.3

**Comment by lmiller1990** [comment]
Actually this was added in rc.2. [See this PR](https://github.com/vuejs/vue-test-utils-next/pull/394).

Native events (like `click`) will "bubble" up - this is something some people like to test, so we now record native events, too, not just custom events. An example would be testing a component using the `compositionstart` event (for example, Japanese/Chinese input components). See [this issue](https://github.com/vuejs/vue-test-utils-next/issues/391) for an example a user discovered.

Do you think we should *not* record native events? Why not?

**Comment by cuixiaorui** [comment]
Oh, I understand

There is no problem logging native events

But this change breaks the previous behavior

Take the following test

```js
      it('when disabled prop is equal to true', () => {
        const wrapper = mount(Link, {
          props: {
            disabled: true
          }
        })
        wrapper.trigger('click')
        expect(wrapper.emitted('click')).toBeFalsy()
      })
```
```js
const Link = {
   emits: ['click'],
   setup(props, { emit }) {
   ……
    const handleClick = (event) => {
      if (props.disabled) return
      if (props.href) return

      emit('click', event)
    }
  ……
  }
}

```
Link wanted to get the component's custom click event, not the native click event, but it did, so the test failed

> Versions prior to RC2 are fine

---

Can we do further processing based on component-defined emits

For example, in the example above,

Click is defined in the component's emits

Then I don't want to get native click in emitted

If I didn't define click in Emits

Then I can get native click in emitted

I think this also corresponds to the behavior of the component emit [rfcs-emits-option](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0030-emits-option.md#fallthrough-control)

How do you think about it?

**Comment by lmiller1990** [comment]
Ahhhh @aethr we forgot the use case for a component custom event that is the same as a native event 🤦 

Good point @cuixiaorui... I am unsure how common (or if it is a good idea) to use a native event name as a custom event name, but this is definitely confusing. We could try your idea of pre-processing `emits`... but what about the use case where a component has a `<button @click>` *and* it does `emit('click')`? What do we do here?

**Comment by cuixiaorui** [comment]
@lmiller1990 

I am so understand

```js
<template>
  <div>
    <button @click="handleClick">click</button>
  </div>
</template>

<script>
export default {
  setup(props, { emit }) {
    const handleClick = () => {
      emit("click");
    };
    return {
      handleClick,
    };
  },
};
</script>

<style></style>
```

If the user writes it that way

calling emitted function gives you the data -> '{click: [custom click, MouseEvent]}'

If the user has defined 'emits'

```js
<template>
  <div>
    <button @click="handleClick">click</button>
  </div>
</template>

<script>
export default {
  emits: ["click"],
  setup(props, { emit }) {
    const handleClick = () => {
      emit("click");
    };
    return {
      handleClick,
    };
  },
};
</script>

<style></style>

```
Then call emitted  it will only receive click:[custom click]

---

This behavior is consistent with Vue

If emits:["click"] is not defined in Vue,

The component will emit two events, a custom event and a native event

**Comment by aethr** [comment]
Good catch @cuixiaorui , and thanks for the link to the emits rfc:

> If, however, click is declared as a custom event by using the emits option, it will then only be triggered by custom events and will no longer fallthrough as a native listener.

So if a component has a native event defined in its `emits` we should stop propagation before it's collected by `emitted`. Weird that Vue itself doesn't take care of this for us if that's the in-browser behaviour. Perhaps it's because we're attaching listeners to the root DOM node **inside** the component.

Sorry, I've been on holiday but I'll see if I can whip up a PR for this in the next day or so.

**Comment by aethr** [comment]
Sorry that took me so long. I have a PR up that hopefully addresses this.

@cuixiaorui would you please review the new test here and check that it should test against the behaviour in this ticket? https://github.com/vuejs/vue-test-utils-next/pull/521/files#diff-bca53c828786d5bd8dbc5a6ef967a8a28d8601dc4fb603bf218baab718a59469

**Comment by lmiller1990** [comment]
Thank you!
