### ISSUE TITLE
Use the Element-Plus unit test to prompt Vue Warn

### ISSUE THREAD

**Issue by yinqunbo** [vuejs/vue-test-utils-next#450]
When I was developing with Element-Plus, there were a bunch of [vue warn] for every `npm run test`, as shown below
```
  console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
    [Vue warn]: Failed to resolve component: el-button
      at <PlanAndCompose>
      at <KeepAlive>
      at <SampleAndSchedule ref="VTU_COMPONENT" >
      at <VTUROOT>

  console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
    [Vue warn]: Failed to resolve component: el-badge
      at <PlanAndCompose>
      at <KeepAlive>
      at <SampleAndSchedule ref="VTU_COMPONENT" >
      at <VTUROOT>

  console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
    [Vue warn]: Failed to resolve component: el-popover
      at <PlanAndCompose>
      at <KeepAlive>
      at <SampleAndSchedule ref="VTU_COMPONENT" >
      at <VTUROOT>
```
I get alerts for any `Element-plus` component I'm referring to, and when I call a method, I can't call any of the methods in elment.I think it is because I did not introduce `Element-plus` in the test?But how to introduce it, I don't know. `createLocalvue()` has seen a vue2 for several times

**Comment by cexbrayat** [comment]
Hi @yinqunbo 
You can find the documentation for VTU 2 here https://next.vue-test-utils.vuejs.org
You're probably looking into how you can register global components: https://next.vue-test-utils.vuejs.org/api/#global

**Comment by whosyourlaowang** [comment]
Does this need to be set for each ?

**Comment by afontcu** [comment]
> Does this need to be set for each ?

Yes – but you can create a function that does it for you, so you don't need to repeat yourself

**Comment by geewhizbang** [comment]
This helps with the larger error, but I still get elementPlus not finding "customParseFormat":

  Diyou mean to import  dayjs/plugin/customParseFormat.js?

**Comment by Zecat** [comment]
@geewhizbang  About `Did you mean to import dayjs/plugin/customParseFormat.js?` 
Try this https://github.com/element-plus/element-plus/issues/4923#issuecomment-1023514728
