### ISSUE TITLE
[question] How can we access slot props of scoped slots

### ISSUE THREAD

**Issue by yakobe** [vuejs/vue-test-utils-next#452]
In VTU 1 it was possible to access the variables passed into slots using the `scopedSlots` mounting option (https://vue-test-utils.vuejs.org/api/options.html#scopedslots)

In VTU 2 this is no longer an option and scoped slots are combined with the `slots` mounting option. However it does not seem to be possible to access the the slot props.

`listItem` is passed in to the template via slots like this (as described in the [docs](https://v3.vuejs.org/guide/component-slots.html#scoped-slots)):

```
<template>
  <ul>
    <template v-for="(listItem, index) in items">
      <slot :listItem="listItem"></slot>
    </template>
  </ul>
</template>
```

It used to be possible to do something like this:
```js
  it('renders a list of modified items', () => {
    expect(mount(AppList, {
      props: {
        items: ['a', 'b', 'c']
      },
      slots: {
        default: '<li><span class="font-bold">{{ props.listItem }}</span></li>'
      }
    }).html()).toMatchSnapshot()
  })
```

Hewever, i dont seem to be able to access the `listItem` and the [documentation](https://next.vue-test-utils.vuejs.org/api/#slots) does not cover how it should be done. Is it still possible and, if so, what is the syntax?

Many thanks

**Comment by afontcu** [comment]
Hi! Here you have some examples on how to destructure props from a scoped slot:

https://github.com/vuejs/vue-test-utils-next/blob/9d3c2a6526f3d8751d29b2f9112ad2a3332bbf52/tests/mountingOptions/slots.spec.ts#L124-L167

It is true, though, that we might want to feature an example on docs, possibly on `slots` API section!

**Comment by yakobe** [comment]
Thank you soooooooo much! That provides a ton of info that helped.

**Comment by lmiller1990** [comment]
@yakobe would you be able to make a PR adding some more info on this to the docs?

**Comment by yakobe** [comment]
Sure! I'll take a look and try to knock something together. It's just the md files in this repo huh? Is there a detailed procedure or just make a PR. 

Short question:Those tests are great because they show multiple scenarios that help. I don't want to bloat the docs with too many examples (maybe 1 or 2). What do you think about adding links to test cases in the docs? They show real code examples and are automatically expanded with new scenarios as they arise. It might also help with contributions as more people would be aware of the tests scenarios and what they relate to.

**Comment by lmiller1990** [comment]
Just update the md files in this repo!

I think a few examples in the docs + some links to source code is fine.

**Comment by adi518** [comment]
How do we access it with a plain render function?

**Comment by lmiller1990** [comment]
Please share the component and test you are having problems with @adi518.

**Comment by adi518** [comment]
You can check it out here: https://github.com/adi518/vue-facebook-login/blob/next/packages/vue-facebook-login-component-next/tests/unit/FacebookLogin.spec.js#L142

Previously (Vue 2) I could do this: https://github.com/adi518/vue-facebook-login/blob/next/packages/vue-facebook-login-component/tests/unit/FacebookLogin.spec.js#L122

I described my use case here: https://github.com/vuejs/vue-test-utils-next/issues/577

**Comment by lmiller1990** [comment]
Neat, I had no idea you could do that (even in VTU v1). Hidden feature - it's definitely not documented, as far as I know. It would be good to support that here, too.

I made an issue to track it: https://github.com/vuejs/vue-test-utils-next/issues/578. I have no idea if/how to implement this off the top of my head.

**Comment by adi518** [comment]
I was too, surprised that hack actually worked, but it's not pretty, so I hope we can go back to the template literal when it's fixed. I did try all of the suggestions in https://github.com/vuejs/vue-test-utils-next/issues/452#issuecomment-795685869, but it made the test throw ambiguous warnings, see below:
```js
  console.warn ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
    [Vue warn]: Property undefined was accessed during render but is not defined on instance. 
      at <Anonymous key=0 idle=true working=true  ... > 
      at <FacebookLoginButton scope= {
      idle: true,
      working: true,
      hasError: true,
      connected: true,
      disconnected: true
    } ref="VTU_COMPONENT" > 
      at <VTUROOT>
```

**Comment by lmiller1990** [comment]
Oh - I thought you *wanted* to use a render function. Do we still have a bug with template literals?

**Comment by lmiller1990** [comment]
Ok. Maybe related: https://github.com/vuejs/vue-test-utils-next/issues/549

If you'd like to open a new issue with your exact reproduction, that's the best way to ensure this doesn't get forgotten - since we are discussing in a closed issue, it's easy for this to get swept under the rug.
