### ISSUE TITLE
Mocked (vuex) store doesn't show up inside setup method of composition API

### ISSUE THREAD

**Issue by irongollem** [vuejs/vue-test-utils-next#457]
**Versions:** 
Vue: 3.0.5
@vue/test-utils: 2.0.0-rc.3 
jest: 26.6.3,

**Problem:**
When using the composition API I get a store.x => cannot get property x of undefined.
When using the option API using the same test there is no issue

**example:**

```javascript
// comp.spec.ts
const store = {
    state: {
      blocks: [],
    },
    dispatch: jest.fn(),
  };

const wrapper = shallowMount(Comp, {
  global: {
    mocks: [store]
  },
});
```

```javascript
// comp.vue working example

// ...
setup() {
  const store = useStore();
  return { store }; 
},
computed: {
  getSomething() { this.store.state.thing },
},
// ...

// OR

// comp.vue not working composition api example

// ...
setup() {
const store = useStore{};
const getSomething = computed(() => store.state.thing);
// ...
}
```

**Expected**
Mocked state should be available inside the setup method

**Comment by lmiller1990** [comment]
I don't think this should work; you are not passing a plugin (which should have an `install` method), you are just passing a plain object.

See this example: https://github.com/vuejs/vue-test-utils-next/blob/84f875fbb6120ffaa597d7a702732e4f79be363d/tests/features/vuex.spec.ts#L15

**Comment by Blackfaded** [comment]
You could also mock the store like so:

```ts
jest.mock('@/libs/store', () => {
  return {
    useStore: () => createStoreMock(),
  };
});
```
Just adjust the importpath and write a createStoreMock function like so:
```ts
import { cloneDeep } from 'lodash';
import { createStore } from 'vuex';

import { RootStore } from '@/libs/store';
const { modules } = jest.requireActual('@/libs/store');

export const createStoreMock = () => {
  return createStore({
    modules: cloneDeep(modules),
  }) as RootStore;
};

```

**Comment by irongollem** [comment]
ah tnx guys, I will try these solutions! Would be nice we get some descriptor of this in the docs so people are made aware (even though you answer seems locical). It depends where you come from I guess, but since it was possible in the past I assumed it still should be :P

**Comment by irongollem** [comment]
Not sure if this is really a bug or just some config or whatever on my side, but I tried both suggested solutions, and neither did the trick. 
* `jest.mock('@/store, () => ...)` didn't seem to do anything (I have the store in root) (i didnt clone the story as your example but tried created a very minimal one on the fly)
* The global.plugins also didn't seem to work.

@lmiller1990 I noticed you changed your answer to the provide method. I'll try and have a go with that solution as I haven't used global.provide yet at all

**Comment by lmiller1990** [comment]
@irongollem Can you make a PR improving the docs? That will help other people with the same question as you.

If you are providing something like this:

```js
const store = {
    state: {
      blocks: [],
    },
    dispatch: jest.fn(),
};
```


Please post **exactly** what you have tried. Just saying it didn't seem to work is not actionable.

You probably want something like:

```js
mount(Foo, {
  global: {
    provide: {
      store: mockStore
    }
  }
})
```

`global.plugins` expects something that matches the plugins API - eg, a class with a static install function, etc (this is how Vuex works).

**Comment by Blackfaded** [comment]
> Not sure if this is really a bug or just some config or whatever on my side, but I tried both suggested solutions, and neither did the trick.
> 
> * `jest.mock('@/store, () => ...)` didn't seem to do anything (I have the store in root) (i didnt clone the story as your example but tried created a very minimal one on the fly)
> * The global.plugins also didn't seem to work

I had to clone the store with lodash, otherwise it did not work also ;)
I dont know why either ^^

**Comment by irongollem** [comment]
Sure I will have a look. If I can resolve it I can update the readme (but as long as the issue eludes me it makes no sense), it's tricky to share to code as its not mine to share, and the 'interpreted' version I already shared. I'll have to retry using the replies after me previous post.

**Comment by lmiller1990** [comment]
Try and make a minimal reproduction, you should be able to do it based on the info in this post.
