### ISSUE TITLE
Can't mount components in version 2.0.0-rc3

### ISSUE THREAD

**Issue by manuelmazzuola** [vuejs/vue-test-utils-next#465]
Bumping @vue/test-utils from `2.0.0-rc.1` to `2.0.0-rc.3` I get that issue
vue version 3.0.5

```
● icon › should render the bell icon

    TypeError: 'set' on proxy: trap returned falsish for property 'hasOwnProperty'

       6 |     expect.assertions(1);
       7 | 
    >  8 |     const wrapper = mount(Icon, {
         |                     ^
       9 |       props: {
      10 |         name: 'bell',
      11 |       },

      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2348:24)
      at Object.<anonymous> (tests/unit/specs/components/icon.spec.ts:8:21)
```

**Comment by afontcu** [comment]
Hi!

Probably related to these lines: https://github.com/vuejs/vue-test-utils-next/blob/bb8023fc2dd1757f0358d3a8f2967a1064019540/src/mount.ts#L448-L451

Can you share your failing test (with your component)? Is it possible that it is a functional component?

**Comment by cexbrayat** [comment]
Make sure you're using Vue 3.0.6 or 3.0.7 if you're using the latest VTU release candidates.

That should solve your issue.

See https://github.com/vuejs/vue-test-utils-next/issues/439

**Comment by afontcu** [comment]
Didn't even notice about Vue's version :) Closing as this seems to have a clear fix. Feel free to reopen if the problem persist after updating Vue!

Thanks
