### ISSUE TITLE
 Clarification: Adding hyphenated Directives through global

### ISSUE THREAD

**Issue by NovaLogicDev** [vuejs/vue-test-utils-next#477]
I know that we now have to add directives through the new Global mounting property, however I have small problem with this,
in my tests I register a directive like this
`localVue.directive('web-content', webContent(configuration.env.name));`

But because the Global prop is an Object I can't use `-` based names anymore, what's the solution, I'm probably missing something super obvious, but I can't figure it out. the directive is used like this in components:
` v-web-content:my-content`

**Comment by afontcu** [comment]
Hi! I guess you could do something like the following?

```js
  const wrapper = mount(Component, {
    global: {
      directives: {
        'web-content': YourDirective
      }
    }
  })
```

**Comment by NovaLogicDev** [comment]
ah yes, that would do the trick! like I figured I just missed something very obvious, thanks
