### ISSUE TITLE
It can't be tested when a library is dynamically loaded through the script tag.

### ISSUE THREAD

**Issue by zouyaoji** [vuejs/vue-test-utils-next#481]
Hi~

My component uses the following way to load a JS library:

```js
// part of HelloWorld.vue
setup () {
    console.log('Cesium loading~ ')
    const $script = document.createElement('script')
    document.body.appendChild($script)
    $script.src = 'https://unpkg.com/cesium/Build/Cesium/Cesium.js'
    const createPromise = new Promise((resolve, reject) => {
      $script.onload = () => {
        console.log('Cesium loaded~ ')
        resolve(true)
      }
    })

    return {
      createPromise
    }
  }
```

and the test code is:
```js
//example.spec.js
import { shallowMount, mount } from '@vue/test-utils'
import HelloWorld from '@/components/HelloWorld.vue'

describe('HelloWorld.vue', () => {
  test('renders props.msg when passed', async () => {
    const msg = 'new message'
    const wrapper = shallowMount(HelloWorld, {
      props: { msg }
    })
    console.log(wrapper.vm.createPromise)
    // It can pass in a few seconds in the browser, but it will always time out during testing.
    await wrapper.vm.createPromise
    expect(wrapper.text()).toMatch(msg)
  }, 25000)
})
```

In my case, the business logic was processed after $script.onload. But I found that this logic cannot be tested with @vue/test-utils. Is it not supported or am I using it incorrectly? The attachment can reproduce the problem I described.

[test.zip](https://github.com/vuejs/vue-test-utils-next/files/6215391/test.zip)

Best wish

**Comment by nandi95** [comment]
I'm not sure if that is supported in your choice of dom implementation.
I think it would be odd if a unit test is downloading some script from outside.
Check the documentation of your dom environment. One of the most common one is [jsdom](https://github.com/jsdom/jsdom)

This doesn't sounds like it has anything to do with the test utils.

**Comment by zouyaoji** [comment]
well, the reason is that from the beginning of the [project](https://github.com/zouyaoji/vue-cesium/blob/dev/packages/viewer/src/useViewer.ts#L885), the js library was introduced through script tag, instead of NPM, I have other considerations.

I think the [render](https://vue-test-utils.vuejs.org/api/#render) api  in version 2 seems to meet my needs, but version 3 does not seem to have this api?

**Comment by zouyaoji** [comment]
@lmiller1990 
Hello, I just  try it in a more minimal environment of jsdom. According to the test result, I think it works in jsdom.

```
import { shallowMount } from '@vue/test-utils'
import HelloWorld from '@/components/HelloWorld.vue'

const jsdom = require('jsdom')
const { JSDOM } = jsdom

describe('HelloWorld.vue', () => {
  test('renders props.msg when passed', async () => {
    const dom = new JSDOM(
      `
    <body>
      <script src="https://unpkg.com/cesium/Build/Cesium/Cesium.js"></script>
    </body>`,
      { runScripts: 'dangerously', resources: 'usable' }
    )
    console.log(dom.window.Cesium) // undefined
    setTimeout(() => {
      console.log(dom.window.Cesium.VERSION) // 1.80
    }, 5000)
    const msg = 'new message'
    const wrapper = shallowMount(HelloWorld, {
      props: { msg }
    })
    console.log(wrapper.vm.createPromise)
    // It can pass in a few seconds in the browser, but it will always time out during testing.
    await wrapper.vm.createPromise
    expect(wrapper.text()).toMatch(msg)
  }, 10000)
})
```
![image](https://user-images.githubusercontent.com/24430116/113957192-5d4c8180-9851-11eb-8ba8-82864435b6a0.png)

**Comment by zouyaoji** [comment]
I studied the documentation of jsdom and found that adding this option in jest.config.js then the CesiumJS loaded successfully.
```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest',
  transform: {
    '^.+\\.vue$': 'vue-jest'
  },
  testEnvironmentOptions: {
    resources: 'usable'
  }
}
```

But I encountered a new problem, jsdom does not support webgl...

**Comment by zouyaoji** [comment]
I have tested almost all testEnvironment of jest, and finally only [`jest-electron`](https://github.com/hustcc/jest-electron) can meet my testing needs, hoping to help people with similar needs.
