### ISSUE TITLE
Using find after findallcomponents will return dom elements that do not meet expectations

### ISSUE THREAD

**Issue by llllllllllx** [vuejs/vue-test-utils-next#484]
The problem is shown in the picture
![2](https://user-images.githubusercontent.com/29992752/112786330-96823600-9088-11eb-98e9-fe6b21d1b397.jpg)

In vue-test-utils 1.x, it returns as expected
![1 (1)](https://user-images.githubusercontent.com/29992752/112786999-1d83de00-908a-11eb-882b-cc766cc0fc09.jpg)

By looking at the code, the find or findAll method of VueWrapper is searched in this.parentElement, that is, in the el-form, so the first matching Input tag is always returned in the sample code

I think `this.parentElement` in `find` and `findAll` methods should be replaced with `this.element`

**Comment by cexbrayat** [comment]
Hi @llllllllllx 
That does look like an issue.

Would you like to open a pull-request to fix it?

**Comment by llllllllllx** [comment]
I have fixed this issue in #494
