### ISSUE TITLE
wrapper.html() formatting

### ISSUE THREAD

**Issue by tbuteler** [vuejs/vue-test-utils-next#498]
I've got a bunch of tests that do something like this:

```js
it('matches snapshot', () => {
    const wrapper = shallowMount(ExampleComponent)
    expect(wrapper.html()).toMatchSnapshot()
})
```

I've been trying out v2 and the snapshots all fail now because they were generated using v1, so my snapshotted HTML is all pretty-printed, whereas the `wrapper.html()` calls with v2 are not.

I was wondering if this was a regression, or if v2 is moving away from pretty-printing HTML (i.e. I should update my snapshots).

**Comment by lmiller1990** [comment]
Your snapshots will likely have some differences, but this seems like a regression. We should match v1 as closely as possible.

Would you like to make a PR fixing this?
