### ISSUE TITLE
Nested slots causes a warning

### ISSUE THREAD

**Issue by matthewjmink** [vuejs/vue-test-utils-next#512]
When passing a child component with default slot content into the default slot for the mounted component, a warning appears in the terminal.

```javascript
const Parent = {
    template: '<div class="parent"><slot /></div>'
};
const Child = {
    template: '<div class="child"><slot /></div>'
};

it('has a default slot', () => {
    const myText = 'Testing 123';
    const cmp = mount(Parent, {
        slots: {
            default: h(Child, myText),
        },
    });
    expect(cmp.html().includes(myText)).toBeTruthy();
});
```

The test passes, but the following warning appears in the terminal:
```
  console.warn
    [Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance. 
      at <Anonymous> 
      at <Anonymous ref="VTU_COMPONENT" > 
      at <VTUROOT>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
      at normalizeVNodeSlots (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2795:9)
      at initSlots (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2816:13)
      at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6388:5)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4112:9)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4088:17)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3716:21)
```

**Relevant version info:**
```json
{
    "@vue/compiler-sfc": "^3.0.7",
    "@vue/test-utils": "^2.0.0-rc.4",
    "jest": "^25.5.4",
    "jest-serializer-vue": "^2.0.2",
    "vue": "^3.0.7",
    "vue-jest": "^5.0.0-alpha.8"
}
```

**Comment by cexbrayat** [comment]
Thank you for opening an issue @matthewjmink 

I think this is an issue with Vue itself, not really with VTU.
Try doing the same in your application and let us know if you have the warning in the browser.
If so, make sure you are using the latest Vue version (3.0.10 right now).

If the warning is still there, this is probably an issue for the vue-next repo

**Comment by matthewjmink** [comment]
You are correct. My apologies. The [Vue docs](https://v3.vuejs.org/guide/render-function.html#slots), while arguably unclear on this point, do explain the expected syntax for component vnodes:

> For component VNodes, we need to pass the children to h as an object rather than an array. Each property is used to populate the slot of the same name:
> ```javascript
> render() {
>   // `<div><child v-slot="props"><span>{{ props.text }}</span></child></div>`
>   return h('div', [
>     h(
>       resolveComponent('child'),
>       null,
>       // pass `slots` as the children object
>       // in the form of { name: props => VNode | Array<VNode> }
>       {
>         default: (props) => h('span', props.text)
>       }
>     )
>   ])
> }
> ```

So, if I make the following change, the warning goes away.
```diff
     const myText = 'Testing 123';
     const cmp = mount(Parent, {
         slots: {
-            default: h(Child, myText),
+            default: h(Child, null, { default: () => myText }),
         },
     });
     expect(cmp.html().includes(myText)).toBeTruthy();
```
