### ISSUE TITLE
Wrapper's `.html()` output is different depending on whether **parent** component has multiple root fragments

### ISSUE THREAD

**Issue by wolfgangwalther** [vuejs/vue-test-utils-next#563]
Take the following test-cases:

```javascript
// this works fine
it('get component without root fragments', () => {
  const RegularComponent = {
    name: 'RegularComponent',
    template: '<span>hello world</span>'
  }
  const ComponentWithoutRootFragments = {
    name: 'ComponentWithoutRootFragments',
    template: '<div><regular-component /><div>bye bye</div></div>',
    components: { RegularComponent }
  }
  const wrapper = mount(ComponentWithoutRootFragments)
  const regular = wrapper.getComponent(RegularComponent)

  expect(regular.vm.$options.name).toBe('RegularComponent')
  expect(regular.html()).toMatchInlineSnapshot(`<span>hello world</span>`)
})

// this does not
it('get component from within root fragments', () => {
  const RegularComponent = {
    name: 'RegularComponent',
    template: '<span>hello world</span>'
  }
  const ComponentWithRootFragments = {
    name: 'ComponentWithRootFragments',
    template: '<regular-component /><div>bye bye</div>',
    components: { RegularComponent }
  }
  const wrapper = mount(ComponentWithRootFragments)
  const regular = wrapper.getComponent(RegularComponent)

  expect(regular.vm.$options.name).toBe('RegularComponent')
  expect(regular.html()).toMatchInlineSnapshot(`
    <span>hello world</span>
    <div>bye bye</div>
  `)
})
```

The first test-case works as expected - `regular.html()` is just the DOM element that is actually rendered in `RegularComponent`. However, once the surrounding `<div>` in the outer component is removed, `regular.html()` suddenly shows its sibling DOM element (`<div>bye bye</div>`), too.

The first expect in each test proves, that `getComponent` returns the right wrapper. But the wrapper itself returns too many DOM nodes.

**Comment by wolfgangwalther** [comment]
It's this check that is going wrong:

https://github.com/vuejs/vue-test-utils-next/blob/fe701dcb6da2bd5d22c461460f50e7faafe3783d/src/vueWrapper.ts#L106-L109

Because `ComponentWithRootFragments` and `RegularComponent` have the same `.parentElement` this is triggered.

**Comment by cexbrayat** [comment]
I agree that this is weird indeed. Your root cause analysis is probably right.

Would you mind opening a PR with the fix and a similar repro test? I would gladly review it and merge it.

**Comment by wolfgangwalther** [comment]
If I had any idea how a fix could look like, I would do that. But I don't.

**Comment by cexbrayat** [comment]
I usually start by adding the test repro to the codebase, and then debug what's going on until I have a pretty good idea of what a fix would look like. 

Would you like to give it a try?

**Comment by lmiller1990** [comment]
Seems this is fixed? https://github.com/vuejs/vue-test-utils-next/pull/1169

**Comment by wolfgangwalther** [comment]
I can confirm it now works fine with the latest version in my local project, where I first observed the problem, too. Thanks!
