### ISSUE TITLE
Unable to add modifiers to triggered event

### ISSUE THREAD

**Issue by blacksonic** [vuejs/vue-test-utils-next#57]
I was trying to alter the keyup event as with the old version, but the new API doesn't have an options argument yet.

Here is a link to the source code, you can reproduce it by removing `.skip`
https://github.com/blacksonic/todomvc-vue-composition-api/blob/master/src/components/header/header.spec.js#L15

**Comment by lmiller1990** [comment]
Yep, looks like a bug. If you don't destructure the `{ emit }` arg, and do `ctx.emit` instead, it works. 

I will investigate this.

**Comment by lmiller1990** [comment]
This is a very easy (I think) first issue. Just port from VTU beta:

- trigger source in VTU beta is [here](https://github.com/vuejs/vue-test-utils/blob/f102a9a35e280f7afe6c1b62a5df7090ebdd6f98/packages/test-utils/src/wrapper.js#L676)
- you can steal most of this [this code](https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/create-dom-event.js) for the event keycodes: 
- [this](https://github.com/vuejs/vue-test-utils/blob/f102a9a35e280f7afe6c1b62a5df7090ebdd6f98/test/specs/wrapper/trigger.spec.js#L60) is the relevant test

**Comment by SergiCL** [comment]
I'll probably have some time off in the next few days, if it's okay with you @blacksonic, I can try to solve this.

**Comment by blacksonic** [comment]
@SergiCL go for it, I'll have time only on the weekend

**Comment by lmiller1990** [comment]
Fixed in #77 by @SergiCL
