### ISSUE TITLE
Demo from documentation fails

### ISSUE THREAD

**Issue by cyberalien** [vuejs/vue-test-utils-next#571]
I've tried testing demo from https://next.vue-test-utils.vuejs.org/guide/#what-is-vue-test-utils

```js
import { mount } from '@vue/test-utils';

// The component to test
const MessageComponent = {
	template: '<p>{{ msg }}</p>',
	props: ['msg'],
};

test('displays message', () => {
	const wrapper = mount(MessageComponent, {
		props: {
			msg: 'Hello world',
		},
	});

	// Assert the rendered text of the component
	expect(wrapper.text()).toContain('Hello world');
});
```

That demo fails with this error:

```
  ✕ displays message (6ms)

  ● displays message

    TypeError: Right-hand side of 'instanceof' is not an object

       8 |
       9 | test('displays message', () => {
    > 10 |      const wrapper = mount(MessageComponent, {
         |                      ^
      11 |              props: {
      12 |                      msg: 'Hello world',
      13 |              },

      at normalizeContainer (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1313:19)
      at Object.app.mount (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1248:27)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7916:18)
      at Object.<anonymous> (tests/demo.test.js:10:18)
```

Packages:
```
@vue/test-utils@2.0.0-rc.6
vue-jest@5.0.0-alpha.8
vue@3.0.11
```

**Comment by cexbrayat** [comment]
Thanks for opening an issue.

It's hard to see what's the issue here. What are you using to set up and run your tests? Vue CLI? Jest directly? Something else? 
I recommend trying with Vue CLI: you'll have a project correctly configured, and your test should succeed.

**Comment by cyberalien** [comment]
I'm using jest directly: `npx jest tests/demo.test.js`

**Comment by cexbrayat** [comment]
What's your jest config?

**Comment by cyberalien** [comment]
```js
module.exports = {
	verbose: true,
	moduleFileExtensions: ['js', 'json', 'vue'],
	transform: {
		'.*\\.(vue)$': 'vue-jest',
		'^.+\\.js$': '<rootDir>/node_modules/babel-jest',
	},
	collectCoverage: false,
};
```

**Comment by cyberalien** [comment]
Fixed it by following these steps:

1. Created basic demo project with unit tests for Vue 3.
2. Copied `jest.config.js` from it.
3. Installed `@vue/cli-plugin-unit-jest` as dependency.

Thanks a lot for help! Hint about Jest config got me in right direction.

My setup worked before with older versions of dependencies, so something has changed in last few months in one of dependencies that broke it. I'll continue debugging it to see what exactly in that config was causing issues.

**Comment by cexbrayat** [comment]
👍 great, feel free to open an issue if you find something weird.

Closing as this is not an issue with VTU

**Comment by cyberalien** [comment]
If anyone else is having the same issue, add this line to your Jest config:
```
testEnvironment: 'jest-environment-jsdom-fifteen',
```
and install `jest-environment-jsdom-fifteen` as dev dependency.

Or just use preset from `@vue/cli-plugin-unit-jest`, which is much easier!
