### ISSUE TITLE
Upgrading to Vue 3.0.7 breaks test with emitted events

### ISSUE THREAD

**Issue by vuesomedev** [vuejs/vue-test-utils-next#575]
I have a component with a single prop and emitted event

```javascript
export default defineComponent({
  props: ['percent'],
  emits: ['redeem'],

  setup(props, { emit }) {
    const percent = ref(props.percent);
    const useCoupon = () => emit('redeem', percent.value);

    return { percent, useCoupon };
  }
});
```

and I have a test that checks for the event when clicking the button:

```javascript
it('should trigger coupon percent on button click', () => {
  const wrapper = mount(Coupon, { props: { percent: 10 } });

  wrapper.find('.btn').trigger('click');

  expect(wrapper.emitted().redeem).toHaveLength(1);
  expect(wrapper.emitted().redeem[0]).toEqual([10]);
});
```

The test passes with Vue version 3.0.6 , but after upgrading all the above versions break the test by not showing emitted events. `wrapper.emitted().redeem` becomes `undefined`.
I have no idea what is going on. Adding `await wrapperwm.$nextTick()` doesn't solve the issue.

I'm not sure if its an issue with Vue core or Test Utils.

The issue can be reproduced in my repository if you upgrade the Vue version from 3.0.6
https://github.com/vuesomedev/vue-3-playground

**Comment by cexbrayat** [comment]
Hi @vuesomedev 
Thank you for opening an issue.

Can you try with the most recent Vue and VTU releases (3.0.11 and 2.0.0-rc.6 I think)?

**Comment by vuesomedev** [comment]
Upgrading test utils also fixed the issue, thanks
