### ISSUE TITLE
Scoped slots with render function not working like in V1

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#578]
Context:

VTU v1 (unofficially?) supported this:

```js
test('scoped-slots', async () => {
    const wrapper = mount(Button, {
      slots: {
        logo: scope => h('div', { class: 'logo' }, JSON.stringify(scope))
      }
    })
    expect(wrapper.html()).toMatchSnapshot()
  })
```

But it's not working in this lib.

While this feature was not documented, so it's not technically a breaking change to the public API, it'd be good to match the original behavior as much as possible.

Originally described in more detail: https://github.com/vuejs/vue-test-utils-next/issues/452#issuecomment-835969505

**Comment by dobromir-hristov** [comment]
What do you mean, you have access to the scope props when you pass a function, from what I know
```
let assertProps

const wrapper = createWrapper({
      slots: {
        button: (props) => {
          assertProps = props;
          return h('button', { class: 'buttonSlot' }, 'Foo');
        },
      },
    });
```

**Comment by lmiller1990** [comment]
Hey, long time no talk.

Does this mean the snippet I posted already works? I assumed it did not, based on this [discussion here][(https://github.com/vuejs/vue-test-utils-next/issues/452#issuecomment-835969505).

**Comment by dobromir-hristov** [comment]
I use it and it works. I even remember working on it hehe

**Comment by lmiller1990** [comment]
Neat. Might be good to add this to the docs somewhere with an example.
