### ISSUE TITLE
Destructure `{ emit }` doesn't work with `emitted`

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#58]
Repro: https://github.com/blacksonic/todomvc-vue-composition-api/blob/63f763c5df3bc162351f73ea30acdcf1fd8fbfe7/src/components/item/item.spec.js#L26

If you don't destructure the `{ emit }` from `ctx`, and do `ctx.emit` instead, it works. destructured emit won't capture the events in `wrapper.emitted()`. It call the original `emit`, not the one we override in the mixin.

Failing test: https://github.com/vuejs/vue-test-utils-next/commit/1acd0e4dd6b0e7859c01307bf1691608741f572c

**Comment by lmiller1990** [comment]
needed a fix in core for this, evan did it here vuejs/vue-next@5968cff so this should be good when the next vue 3 alpha comes out. will leave this issue open until then to track it.

**Comment by afontcu** [comment]
nice catch

**Comment by lmiller1990** [comment]
If someone knows evan's change fixes (or should fix) this problem please explain it to me :| why does destructruring make the `get` not return the modified emit function?

**Comment by lmiller1990** [comment]
Fixed by alpha 13
