### ISSUE TITLE
Unable to inspect triggered events

### ISSUE THREAD

**Issue by blacksonic** [vuejs/vue-test-utils-next#59]
When triggering events in the component with the new `emit` method, they don't appear on the wrappers `emitted` method

Here is a link to the source code, you can reproduce it by removing `.skip`
https://github.com/blacksonic/todomvc-vue-composition-api/blob/master/src/components/item/item.spec.js#L35

**Comment by blacksonic** [comment]
Closing as it's a duplicate of https://github.com/vuejs/vue-test-utils-next/issues/58

**Comment by lmiller1990** [comment]
needed a fix in core for this, evan did it here https://github.com/vuejs/vue-next/commit/5968cff3a8acc82657cd051c504265835eaac7a2 so this should be good when the next vue 3 alpha comes out.
