### ISSUE TITLE
Plugin functionality (vue-next-rx) not working 

### ISSUE THREAD

**Issue by p-v-d-Veeken** [vuejs/vue-test-utils-next#601]
Hi,

I originally opened issue #592, which I got some very friendly and helpful feedback on. Unfortunately, I was not able to get the test to succeed.

I'm trying to test an rxjs observable which is derived from a variable in `data()` and which _should_ fire every time the variable is updated. I can observe the correct behaviour in the browser, but not in the test unfortunately.

Example.vue
```Vue
<template>
    <div>
        <input v-model="input" />
        <span>{{ result$ }}</span>
    </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
import { map, pluck } from 'rxjs/operators';

export default defineComponent({
    name: 'Example',
    data() {
        return {
            input: '',
        };
    },
    subscriptions() {
        return {
            result$: this.$watchAsObservable('input').pipe(
                pluck('newValue'),
                map((input) => `Foo${input}`),
            ),
        };
    },
});
</script>
```
Example.spec.ts
```Typescript
import { mount } from '@vue/test-utils';
import Example from './Example.vue';
// @ts-expect-error
import VueRx from '@nopr3d/vue-next-rx/dist/vue-next-rx';

describe('Example', () => {
    it('should work', async () => {
        const wrapper = mount(Example, {
            global: {
                plugins: [VueRx],
            },
        });
        await wrapper.find('input').setValue('Bar');

        expect(wrapper.vm.$data).toMatchObject({ input: 'Bar' }); // succeeds
        expect(wrapper.find('span').text()).toContain('FooBar'); // fails
    });
});
```

Once again any help or pointers would be greatly appreciated! :)

**Comment by cexbrayat** [comment]
There is probably some asynchronous code going on in the observable.
Try to add `await nextTick()` or `await flushPromises()` after setting the value, that might do the trick.
See https://next.vue-test-utils.vuejs.org/guide/advanced/async-suspense.html#resolving-other-asynchronous-behavior

**Comment by p-v-d-Veeken** [comment]
Hmm, no luck for: 
```Typescript
import { flushPromises, mount } from '@vue/test-utils';
import Example from './Example.vue';
import VueRx from '@nopr3d/vue-next-rx';
import { nextTick } from 'vue';

describe('Example', () => {
    it('should work', async () => {
        const wrapper = mount(Example, {
            global: {
                plugins: [VueRx],
            },
        });
        await wrapper.find('input').setValue('Bar');
        await nextTick();
        await flushPromises();
        await nextTick();

        expect(wrapper.vm.$data).toMatchObject({ input: 'Bar' }); // succeeds
        expect(wrapper.find('span').text()).toContain('FooBar'); // fails
    });
});
```
I've checked out the [implementation of `$watchAsObservable`](https://github.com/NOPR9D/vue-next-rx/blob/main/src/methods/watchAsObservable.js) and it uses a component instance's `$watch` function under the hood.

Does this get me any further, or should I maybe try something less unorthodox? 😛

**Comment by cexbrayat** [comment]
OK this was a tricky one, took me some time to figure it out 😅

`watchAsObservable` is using `setTimeout` (see https://github.com/NOPR9D/vue-next-rx/blob/main/src/methods/watchAsObservable.js#L20). That means this code is never executed in a unit test.

With jest, you can use fake timers.
So the following should work:
```ts
it('should work', async () => {
  jest.useFakeTimers();
  const wrapper = mount(HelloWorld, {
      global: {
          plugins: [VueRx]
      },
  });
  jest.runAllTimers();
  await wrapper.find('input').setValue('Bar');
  expect(wrapper.vm.$data).toMatchObject({ input: 'Bar' }); // succeeds
  expect(wrapper.find('span').text()).toContain('FooBar'); // succeeds
});
```

Closing, as this is not an issue in VTU.

**Comment by p-v-d-Veeken** [comment]
Awesome, thanks so much!!
