### ISSUE TITLE
Cannot mount mock router with composition API

### ISSUE THREAD

**Issue by loocurse** [vuejs/vue-test-utils-next#611]
Hello,

I seem to be struggling with the same issue as this user in [stackoverflow](https://stackoverflow.com/questions/65592988/vue-test-utils-with-vue-router4-and-vue3-composition-api). 

Specs: Vue 3 | Vuex 4 | VTU 2 

I followed the [VTU 2 documentation](https://next.vue-test-utils.vuejs.org/guide/advanced/vue-router.html#using-a-mocked-router) but it uses the `$router`. However, I am using the `setup()` function 
###### Component.vue file
```{javascript}
<script>
import { useStore } from "vuex";
...
export default {
    ...
    setup() {
        const store = usestore() 
        store.dispatch(..., route.params.id); // TypeError: Cannot read property 'params' of undefined
        ...
    }
}
</script>
```

###### Component.test.ts
```{javascript}
test("Form data binding works", async () => {
  const $route = {
    params: {
      id: 100,
    },
  };
  const $router = {
    push: jest.fn(),
  };
  const wrapper = mount(Event, {
    data() {
      return {
        ...
      };
    },
    global: {
      mocks: {
        $route,
        $router,
      },
      plugins: [store],
    },
  });
  expect ...
}
```

#### Desired outcome
To be able to inject the mock store into the code when doing unit test on the component
#### Outcome
The code errors out by saying that the router object has no parameters. In other words, the router object was not injected into the test.

**Comment by cexbrayat** [comment]
@loocurse In your component, where does `route` come from? Are you using the composition API with `useRoute()`?

**Comment by loocurse** [comment]
Yes correct

**Comment by cexbrayat** [comment]
In that case using `global.mocks` won't help you.

You can use https://github.com/posva/vue-router-mock and set route and the params to whatever you want.
Hope this helps.

Closing as this is not a VTU issue.
