### ISSUE TITLE
Reference native UI elements in a test with vue 3 & vue test utils without adding attributes to a UI element

### ISSUE THREAD

**Issue by MENtechmedia** [vuejs/vue-test-utils-next#615]
**Question: How can you reference native UI elements in vue 3 and vue test utils without adding extra attributes to that UI element?**

When testing vue components with vue 3 and vue test utils, I noticed that there wasn't really an elegant way to find UI elements. Since Vue 3, Vue Test Utils does not provide a way to use the ref attribute anymore (maybe I'm wrong, but the docs don't mention it) on a native UI element like a button for example.

I know about these solutions:

`<button data-test="button" ></button> or <button class="button"> </button>`

But adding extra attributes or classes to the component just for the sake of testing the component doesn't feel like a solution. Also the error that the test throws is not very descriptive. For example when testing events Error: Cannot call trigger on an empty DOMWrapper.

**Comment by lmiller1990** [comment]
For `findComponent`, you can use `ref`. [See here](https://next.vue-test-utils.vuejs.org/api/#findall).

What is a native UI element? Do you mean HTML elements, like `<button>` and `<div>`? For those, you can do `wrapper.find('button')`. `find` is basically just `querySelector`.

I am not clear on why adding a `ref` would be more elegant than adding a `data-test` selector (both require you to add some  additional code).

**Comment by MENtechmedia** [comment]
Thanks for your response.

You can't target `ref` on native UI elements (HTML elements like `<button>` and `<div>`) right?

I'm not a fan of adding ref either. But I think it's better and more intuitive than adding data-test, since it's something vue provides. I think you could also test if the ref exists and that it's not empty (or atleast contains a HTML element)? 

Anyway, wrapper.find('button') might work in simple use cases. But what if you have multiple buttons? Or what if you would like to target a nested `div` (say nested three deep) ? It those cases you will have to add some kind of reference to the element like `data-test`, `id="nestedDiv"` or anything along those lines. 

Thus you come back to the same problem I mentioned. Adding extra attributes, ids or classnames to the HTML structure, for the sake of testing just doesn't feel like a proper solution to me.

**Comment by lmiller1990** [comment]
I think `data-test` is a bit better in this case.  It's something the DOM provides, and it already works out of the box.

I definitely understand your pain. I usually just add specific `data-test` attributes for a specific element. 

I think what you might be looking for is something like [Testing Library](https://testing-library.com/docs/vue-testing-library/intro/). It has Vue integration (which uses Test Utils under the hood - the mounting options are all the same). Furthermore, it has much more expressive queries. You might like [getByText](https://testing-library.com/docs/queries/bytext). You can write code like this:

```js
const btn = findByText('My button')
fireEvent.click(btn)
```

Alternatively, you could try out the awesome new Cypress component testing, which supports [both Vue 2 and Vue 3](https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/). Then you can write:

```js
```

**Comment by MENtechmedia** [comment]
Thanks for coming back to me with an answer so quickly!

I will take a look at those Libraries and try them out. For now I will stick to `data-test` when referencing specific elements.
