### ISSUE TITLE
Setchecked reported TS error [ts(2341)] in use

### ISSUE THREAD

**Issue by liuzaijiang** [vuejs/vue-test-utils-next#618]
the test is:
```
test('checked(v-model) work', async () => {
    const checked = ref(true)
    const wrapper = mount({
      template: `<input type="checkbox" v-model:checked="checked" />`,
      setup() {
        return { checked }
      },
    })

    await wrapper.find('input[type="checkbox"]').setChecked(false); 
    expect(checked.value).toBe(false)
  })
```
the error is :  `Property 'setChecked' is private and only accessible within class 'DOMWrapper<ElementType>'.ts(2341)`

this version is: `@vue/test-utils": "^2.0.0-rc.6"`

**Comment by cexbrayat** [comment]
@liuzaijiang I think this is intended: you're suppose to simply use `setValue(false)` instead.

See https://next.vue-test-utils.vuejs.org/api/#setvalue
