### ISSUE TITLE
We can't use isVisible in vueWrapper ?

### ISSUE THREAD

**Issue by YutamaKotaro** [vuejs/vue-test-utils-next#629]
Sorry... this is not issue, just feature request 🙇🏻 

I wrote the detail about this feature request in PR ( #628 ).

In short, I'd like to use isVisible in vueWrapper 🙇🏻

**Comment by lmiller1990** [comment]
Hi! Posted some questions in your PR.

I don't remember the specific reason for not having `isVisible` on `VueWrapper`. @afontcu might have some recollection?

**Comment by YutamaKotaro** [comment]
@lmiller1990 Thanks for your kindness !!

FYI:
That pull request doesn't work in multiple root due to #629.
So, I'll try to fix it mean while 🙇🏻

**Comment by lmiller1990** [comment]
Merged.
