### ISSUE TITLE
Can't get emitted events with the script setup RFC

### ISSUE THREAD

**Issue by JJBocanegra** [vuejs/vue-test-utils-next#651]
[The script setup RFC](https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md) is a proposal for Vue 3 that introduce a new script type in Single File Components: `<script setup>`, which exposes all its top level bindings to the template.

Using this, I can't catch any events emitted from the mounted component in the tests.

**NewSetupComponent.vue**
```vue
<script setup lang="ts">
import { onMounted, defineEmit } from 'vue';

const emit = defineEmit(['foo']);

onMounted(() => emit('foo', 'mounted'));
</script>
```

**NewSetupComponent.spec.ts**
```ts
import { mount } from '@vue/test-utils';
import NewSetupComponent from './NewSetupComponent.vue';

describe('NewSetupComponent', () => {
  it('should emit foo', () => {
    const wrapper = mount(NewSetupComponent);

    expect(wrapper.emitted('foo')).toBeTruthy();
  });
});
```

This always returns `undefined` in the test.

------------------------------

If I use the usual composition API syntax, it works as expected.

**SetupComponent.vue**
```vue
<script lang="ts">
import { defineComponent, onMounted } from 'vue';

export default defineComponent({
  emits: ['foo'],

  setup(_props, { emit }) {
    onMounted(() => emit('foo', 'mounted'));
  },
});
</script>
```

**SetupComponent.spec.ts**
```ts
import { mount } from '@vue/test-utils';
import SetupComponent from './SetupComponent.vue';

describe('SetupComponent', () => {
  it('should', () => {
    const wrapper = mount(SetupComponent);

    expect(wrapper.emitted('foo')).toBeTruthy();
  });
});
```

Here the test pass.

-------------------------

I tried using `async/await`, using the [old `<script setup>` RFC syntax](https://github.com/vuejs/rfcs/blob/script-setup/active-rfcs/0000-script-setup.md), and nothing works.

Am I doing something wrong? If not, would you support this?

Thanks!

**Comment by lmiller1990** [comment]
Interesting. Definitely a bug. 

I will investigate this. We should definitely have more coverage around `<script setup>` - still experimental, but I'd like to support is as best we can.

**Comment by lmiller1990** [comment]
I am going to work on this now. I did some digging, I *can* capture a `click` event. The problem is unique to custom events. I'll keep debugging.

**Comment by lmiller1990** [comment]
I fixed this. This fix probably breaks something, I don't know why it works, but it's a start. https://github.com/vuejs/vue-test-utils-next/pull/663

I have not used `expose`, I am not sure what the current implementation is, either.
