### ISSUE TITLE
Expose Better Global Config API

### ISSUE THREAD

**Issue by micDropper** [vuejs/vue-test-utils-next#684]
We create a Vue 3 app like this:
```
// main.js
import { createApp } from 'vue';
import { setup } from './setup';

const app = createApp(App);
setup(app);
app.mount('#app');
```

Why not make the vue-test-utils global configuration for the `mount` method similar so we can share the same setup function?
```
// jest.setup.js
import { app } from '@vue/test-utils'
import { setup } from './setup';

setup(app);
```

Where `setup` is a function that might look like this:
```
// setup.js
export function setup(app) {
  installIcons(app);
  setupI18n(...).install(app);
  app.use(createPinia());
}
```

**Comment by lmiller1990** [comment]
I don't fully understand your proposal. What API are you suggesting?

**Comment by scvnc** [comment]
Came here with similar desire.. I found [some other docs][0] mentioning what we might need. I don't think the official vue-test-utils-next docs mention  how to precisely configure globals.


    // setup.jest.js
    import { config } from "@vue/test-utils"


    config.global.mocks = {
      mock: "Default Mock Value"
    }

[0]: https://lmiller1990.github.io/vue-testing-handbook/v3/mocking-global-objects.html#settings-default-mocks-using-config

**Comment by afontcu** [comment]
Hi! We do, although they might be hard to find:

https://next.vue-test-utils.vuejs.org/api/#config-global

Really open to suggestions on how to improve docs! 🙌

**Comment by lmiller1990** [comment]
Does the above docs solve the problem @scvnc and @micDropper?

**Comment by TheJaredWilcurt** [comment]
@afontcu 
> Really open to suggestions on how to improve docs!
That example is basically unreadable. Any way it could be converted to either JavaScript or English

**Comment by afontcu** [comment]
not sure if passive agressive or real feedback 🤔 You mean that the example on how to mock `$t` globally is unreadable?

**Comment by TheJaredWilcurt** [comment]
Sorry, was referring to the signature. The `Component.vue` and `Component.spec.js` are fine.

**Comment by micDropper** [comment]
I was thinking rather than exposing a global config API unique to vue-test-utils, just extend Vue 3's app configuration API. I'm sure there is a typescript interface somewhere defining exactly what Vue 3's `createApp()` method returns. Vue-test-utils could extend that interface and add some of it's own config options, maybe add methods like `app.mock(<something>)`. This would allow Vue 3 and vue-test-utils to share the same Vue configuration by using the exact same `setup(app)` function (see original post). Additional setup specific to vue-test-utils could take place before or after the shared Vue configuration happens. 

Now, I am assuming it's desirable to have the exact same Vue root-app configuration in unit tests as in production, but I may be wrong on that. But even if I am, this API doesn't have to be shared. It could be configured completely separately. I think it would make more sense to developers already familiar with the Vue 3 application config API.

**Comment by lmiller1990** [comment]
Yep, `createApp` returns an `App` type. 

Back on the original post, I haven't seen this before:

```ts
// main.js
import { createApp } from 'vue';
import { setup } from './setup';

const app = createApp(App);
setup(app);
app.mount('#app');
```

Either way, I think the challenge people are facing is Vue separates the config setup from mount. For example:

```ts
// create
const app = createApp()

// setup
app.use(...)

// mount
app.mount('#app')
```

But VTU does all of these in one go. We use `global` to install plugins, mixins, etc.

We cannot change the existing behavior, but we could make the internals more modular, which might help. We almost have what you want... `createWrapper`, which receives an `app` argument and returns the `VueWrapper` with all the fun APIs like `setProps`, `get`, etc. [That's here](https://github.com/vuejs/vue-test-utils-next/blob/master/src/mount.ts#L497). As you can see it receives a few extra arguments like `$vm`, so we'd probably need to move a few things around. This would be a kind of "low level" API, since you'd need to deal with installing plugins yourself, you wouldn't have access to any of the mounting options, etc.

Does this sound like what people are asking for? It's not as straight-forward to just export this method, we need to consider what else needs to be handled (eg, do you want to use `stubs`? If so, how do you think those should be applied? How should the API look?)

**Comment by scvnc** [comment]
Firstly, thanks for your attentiveness to this issue.

Perhaps the docs have been updated or else I am reading the docs better now that I no longer hastily trying to figure this out while getting some tested features refactored.  It seems clear now.

I see a useful example illustrating that test-utils exports a 'global' config object as depicted by the imports in the example. I could not see it immediately and I thought the signature was referring to `MountingOptions.global` on the `mount` interface, which caused me to make a wrapped `mount` for my project which all tests must use.


## Verbiage of 'global configuration' in the mount function

possible confusion point

![image](https://user-images.githubusercontent.com/885196/127793280-b4b2ac77-91a1-45a8-a721-129bd06c9d0d.png)

## New clarity in the docs

Now I scroll down and see this helpful example, perhaps I missed it last time.

![image](https://user-images.githubusercontent.com/885196/127793491-32f17f1c-bdb9-4e92-82b4-a9d497dbb55c.png)

**Comment by lmiller1990** [comment]
That is very confusing. It should be something like "accepts a second parameter that defines the component's state and configuration. It also accepts a `global` key <insert link to global: https://next.vue-test-utils.vuejs.org/api/#global > that defines default configuration".

We should also have a simple example there, something like:

```js
const wrapper = mount(Component, {
  props: {
    msg: 'world'
  },
  global: {
    plugins: [vuex]
  }
})
```

That would make it more clear. A PR would be welcome!

Also, still happy to explore a better separation between config and mounting.

**Comment by scvnc** [comment]
I'd be glad to PR for some clarity.  As I see how the markdown is rendered, I suspect part of the issue is how title anchors are used and possibly conflict.  I almost need to make a flowchart in reading to untangle it because I get into a path of confusion when clicking through the anchor links.
