### ISSUE TITLE
docs: Migration findAll.at(0) => findAll[0]

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-test-utils-next#693]
The migration guide should make it obvious that `.at(0)` has been removed from `.findAll`

* **Before:**
  * `wrapper.findAll('[data-test="token"]').at(0)`
* **After:**
  * `wrapper.findAll('[data-test="token"]')[0]`

* * *

The new API docs for `.findAll` should include an example of selecting a specific item.

```js
const wrapper = mount(BaseTable);
const thirdRow = wrapper.findAll('tr')[2];
```

**Comment by afontcu** [comment]
Hi! Yeah, that makes sense! Fancy to open up a PR? 😃

**Comment by lmiller1990** [comment]
Should we also support the `at` syntax (with a deprecation warning)?

That might help with migration, too.

**Comment by TheJaredWilcurt** [comment]
If the source was JavaScript I would create a PR for it. Since it's TS, I guess the notes in the docs are good enough.
