### ISSUE TITLE
QUESTION: Any better way to do this?

### ISSUE THREAD

**Issue by noah-friedman** [vuejs/vue-test-utils-next#694]
I'm trying to write a jest test with typescript. Is there any way to do what I'm trying to do with better typing?

```typescript
describe("example", () => {
  let w: VueWrapper<any>; // I'd like this not to be 'any'
  beforeEach(() => {
    w = shallowMount(component);
  })
})
```

The issue is that I cannot declare the `w` variable within the `beforeEach` callback and have the variable be accessible in the scope of the tests. However, this means I can't use type inference when declaring `w`. Is there anything I can put in place of `VueWrapper<any>` in order to have better type guarding?

**Comment by afontcu** [comment]
Hi! Please let us know if this helps 😄: https://github.com/vuejs/vue-test-utils-next/discussions/297

**Comment by lmiller1990** [comment]
What is component? If it is imported from a `vue` file, then I don't think this is something supported (yet). It might be in the future via something like [Volar](https://github.com/johnsoncodehk/volar) and some work.

If you are using TSX, you should be able to get better typing just by doing:

```ts
const wrapper = shallowMount(component)
```

**Comment by lmiller1990** [comment]
Maybe:

```ts
import yourComponent from './somewhere.vue'

describe("example", () => {
  let w: VueWrapper<typeof yourComponent>; // I'd like this not to be 'any'
  beforeEach(() => {
    w = shallowMount(yourComponent);
  })
})
```

I don't see any action to be taken in VTU at this point, so I will close this. Happy to reopen if we need to change some code here.
