### ISSUE TITLE
order of attributes on rendered html

### ISSUE THREAD

**Issue by eunjae-lee** [vuejs/vue-test-utils-next#706]
Hi there,
I'm working on Vue 3 support in [Vue InstantSearch](https://github.com/algolia/vue-instantsearch).
The goal is to support both Vue 2 and 3 in a single code base.

So I'm setting up

- test on Vue 2 with vue-test-utils@1
- test on Vue 3 with vue-test-utils@2

However I'm seeing difference in rendered html:

```vue
<template>
  <div>
    <button :class="className" :title="title">click</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      className: "hello",
      title: "this is a button",
    };
  },
};
</script>
```

```js
const wrapper = mount(Test);
expect(wrapper.html()).toMatchInlineSnapshot(
`"<div><button title=\\"this is a button\\" class=\\"hello\\">click</button></div>"`
);
```

↑ vue-test-utils@1

```js
const wrapper = mount(Test);
expect(wrapper.html()).toMatchInlineSnapshot(
    `"<div><button class=\\"hello\\" title=\\"this is a button\\">click</button></div>"`
);
```

↑ vue-test-utils@2

On the same component, the order of attributes are different between the test util v1 and v2.

Do you see any way to keep single set of snapshots in both versions? Either we update vue-test-utils@2 to output html the same as it did in v1, or we could expose an option in html() function to specify its behavior.

These are the reproductions. You can see `Test.spec.js` in each repo to see the different results.

- https://github.com/eunjae-lee/vue-test-utils-snapshot-1
- https://github.com/eunjae-lee/vue-test-utils-snapshot-2

Let me know if I can help.

**Comment by xanf** [comment]
Hi @eunjae-lee
Same task here, same problem. 
What I think - this should not be a VTU job. Instead we should use serializer, which (for example) sorts props when making snapshot

so the code will be the same: `expect(wrapper).toMatchInlineSnapshot(...)` (note missing ".html()") part. 
Exposing additional configuration object might be confusing and does not protect us from future changes in order

**Comment by eunjae-lee** [comment]
Hey @xanf, yeah after creating this issue and talking to my colleague, I think I can use a serializer to make my tests pass.
However, I'm still curious, there must be some logic somewhere (in VTU, vue template compiler, or idk, somewhere) to generate that HTML string. And that has changed over time. If that's happened inside VTU, we could consider reverting it to have consistent output. Especially this next version hasn't hit the stable release, so there's still room to discuss.

**Comment by xanf** [comment]
@eunjae-lee from what I know (sorry, don't have proof right away) this is coming from Vue core, not VTU

**Comment by eunjae-lee** [comment]
Okay it makes sense. I'm closing this since there's no further action that can be taken here.
