### ISSUE TITLE
isVisible() always returns true for cloned nodes

### ISSUE THREAD

**Issue by gabrielthomasjacobs** [vuejs/vue-test-utils-next#720]
### Subject of the issue

isVisible() always returns true, even when it shouldn't.

### Steps to reproduce

edit: see next comment by me for new/improved repro steps.

Create a div (use either):
`<div id="foo" v-show="false" />`

`<div id="foo" style="display: none" />`

in unit test:
` const fooItem = wrapper.get('#foo'); `
`expect(fooItem.isVisible()).toBe(false);`

### Expected behaviour

fooItem.isVisible() should return false and above example test should pass.

### Actual behaviour

Test fails because isVisible() returns true.

logging the html, I get:
`"<div id="ex" style="display: none;"></div>"`

so the display is set to none and isVisible() should be reporting false.

### Possible Solution

I have also tried placing an element inside the div and checking if the child isVisible() while the parent has v-show set to false, but this also always returns true.

A work-around is manually grabbing the elements attributes and checking if it contains "display: none"...    
  
From the [documentation](https://next.vue-test-utils.vuejs.org/guide/essentials/conditional-rendering.html#checking-elements-visibility)  
   

> isVisible() gives the capacity to check for hidden elements. In particular isVisible() will check if:
> - an element or its ancestors have display: none, visibility: hidden, opacity :0 style

  
### Environment  
  
Using @vue/test-utils@next (currently 2.0.0-rc.9, but I was able to repro this on 2.0.0-rc.6 as well)
Using vue@next (currently 3.1.2)

**Comment by afontcu** [comment]
Hi! just wrote the following test and it passes as expected:

```js
  it('returns false when element is hidden', () => {
    const wrapper = mount({
      template: `<div id="foo" style="display: none" />`
    })
    const fooItem = wrapper.get('#foo')
    expect(fooItem.isVisible()).toBe(false)
  })
```

is it possible that your real world case scenario is somewhat more complex? Do you think you could share a reproduction gist or repo?

**Comment by gabrielthomasjacobs** [comment]
Yes, that is possible... 
Do you mind trying this and seeing if it reproduces the error?   
If not, I'll try to do another repro outside of my environment:  
  
```typescript
it('tests the isVisible command', () => {
    const fooComponent = defineComponent({
       render: () => h('div', { style: "display: none", id: "foo" })
    });
    const fooWrapper = mount(fooComopnent);
    expect(fooWrapper.get('#foo').isVisible()).toBe(false);
  })
})
```

**Comment by gabrielthomasjacobs** [comment]
Alright, I was able to download/run this repro and modify the example test. Unfortunately (for me), the test worked with the code I provided... My environment is a bit more complex, so I will have to do some digging; I will just close this out and re-open later if I can track the issue down to something test-utils is causing.

**Comment by gabrielthomasjacobs** [comment]
@afontcu Ok, after some more digging, it seems that my issue is stemming from the getComputedStyle call at vue-test-utils.esm-bundler.js:6658

Specifically, `var _a = getComputedStyle(element)` where element is `<div id="foo" style="display: none;"></div>`

from the browser console, `element.style.display` is equal to the string `"none"` but `getComputedStyle(element)` produces a cssStyleDeclaration object where every value is an empty string. 

This sort of stuff starts to get above my head, but I think it has to do with the node being cloned and the computedStyles getting wiped as a result. I could be off-base here, but if you check out the[ w3 link here](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_node_clonenode) and then modify it to be:
<details>

```
<!DOCTYPE html>
<html>
<body>

<ul id="myList1" ><li>Coffee</li><li>Tea</li></ul>

<ul id="myList2"><li>Water</li><li style="display: block">Milk</li></ul>

<p>Click the button to copy an item from one list to another.</p>

<button onclick="myFunction()">Try it</button>

<p>Try changing the <em>deep</em> parameter to false, and only an empty LI element will be cloned.</p>

<script>
function myFunction() {
  var itm = document.getElementById("myList2").lastChild;
  console.log('original display:', itm.style.display)
  var cln = itm.cloneNode(true);
  console.log('node clone display:', window.getComputedStyle(cln).display);
  document.getElementById("myList1").appendChild(cln);
}
</script>

</body>
</html>
```

</details>
You can hit run, open the console, then click the button to see the issue that I'm experiencing.

This might be a vite-related change to handle the cloning of the nodes better, but would it be possible to expand the check (at :6658/6659) to include element.style.display directly?

**Comment by gabrielthomasjacobs** [comment]
I think the components I'm trying to test are being tossed into a transition, which is why my tests are always returning true... I'll need to do more reading on how those work and are tested, so I'm just going to close this out for now.
