### ISSUE TITLE
Master build is broken

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#733]
Check out master
Yarn install
Run tests
Failures.

I am not sure why, yet.

**Comment by xanf** [comment]
@lmiller1990 Hmm, just tried with latest commit 6ca7884 and works for me both on Windows & Lines

**Comment by lmiller1990** [comment]
I deleted the project, re-cloned and everything is working. 

No idea what was going wrong. Anyway, it's green, so it's good.

**Comment by lmiller1990** [comment]
Edit @xanf try running `yarn test:build`.
