### ISSUE TITLE
VTU 2 is unable to find stubbed component with findAllComponents

### ISSUE THREAD

**Issue by marina-mosti** [vuejs/vue-test-utils-next#734]
When I stub out a component and try to `findAllComponents(stub)` like this:

```js
const linkStub = {
  template: '<a/>'
}

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const msg = 'new message'
    const wrapper = shallowMount(HelloWorld, {
      props: { msg },
      global: {
        stubs: {
          BaseLink: linkStub
        }
      }
    })

    const links = wrapper.findAllComponents(linkStub)
    expect(links).toHaveLength(1)
  })
})
```

VTU can not find any. If I add a name property to the `linkStub`:

```js
const linkStub = {
  template: '<a/>',
  name: 'LinkStub'
}
```

Then it works, I'm guessing because something is checking for a `name` to exist and then identifying it as an actual component. Its not a problem, but I don't think/havent found this documented anywhere if is working as intended.

Stubbing out the component and then finding it is "odd" but (I have found) necessary when trying to check for the contents of a slot in a v-for loop of components that have non-default slots for example.

**Comment by standbyoneself** [comment]
Check out the `findAllComponents()` signature:

```
findAllComponents(selector: { name: string } | string): VueWrapper<T>[]
```

It takes an object with `name` key or a string

Also API Reference provides an example about stubbing:

```
test('global.stubs using a custom component', () => {
  const CustomStub = {
    name: 'CustomStub',
    template: '<p>custom stub content</p>'
  }

  const wrapper = mount(Component, {
    global: {
      stubs: { Foo: CustomStub }
    }
  })
...
```

Pay attention CustomStub also has a `name` key
