### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by moonsundong** [vuejs/vue-test-utils-next#742]
![image](https://user-images.githubusercontent.com/37856350/124835615-33237080-dfb4-11eb-88c0-50ca3a4a937b.png)

**Comment by lmiller1990** [comment]
Please provide a reproduction I can run, like a GH repository I can clone. A screenshot is not enough. The code looks fine to me.

I will reopen once I have more information to go on.
