### ISSUE TITLE
provide as a function does not work

### ISSUE THREAD

**Issue by eunjae-lee** [vuejs/vue-test-utils-next#745]
Hello, I'm passing a function that returns an object for `provide` and it doesn't seem to work.

- vue: 3.1.4
- VTU: 2.0.0-rc.10

According to [the Vue doc](https://v3.vuejs.org/guide/component-provide-inject.html) and [my test](https://codesandbox.io/s/friendly-rhodes-tglx6?file=/src/App.vue), it should work with a function.

Since only object form is documented on VTU, I assume you didn't implement it yet.

- reproduction: https://github.com/eunjae-lee/vtu-provide-function (`yarn && yarn test`, look at [example.spec.ts](https://github.com/eunjae-lee/vtu-provide-function/blob/main/tests/unit/example.spec.ts))

Let me know if I can help in any way.

**Comment by standbyoneself** [comment]
It doesn't work because of this:

`src/types.ts`
```js
export type GlobalMountOptions = {
...
provide?: Record<any, any>
...
}
```

and this:

`src/mount.ts`
```js
...
// provide any values passed via provides mounting option
if (global.provide) {
  for (const key of Reflect.ownKeys(global.provide)) {
    // @ts-ignore: https://github.com/microsoft/TypeScript/issues/1863
    app.provide(key, global.provide[key])
  }
}
...
```

It accepts only an object and handles only an object too

**Comment by LinusBorg** [comment]
The function syntax only makes sense when used within a component, as it allows to access `this`.

`app.provide` has no way of passing a funcion that would be called to get the content to be provided, as there's no `this` to access that would make sense.

Likewise, in the context of a test, that syntax isn't needed / doesn't make sense.

**Comment by eunjae-lee** [comment]
> `app.provide` has no way of passing a funcion that would be called to get the content to be provided, as there's no `this` to access that would make sense.

You're right. 

- `this` isn't there
- even if I needed something dynamic, it's anyway happening at the creation of the app, so I can do some calculation and just put the object right inside.

So it makes sense not to support a function form in `global.provide`. Thanks for clarification.
