### ISSUE TITLE
Ensure commit message consistency

### ISSUE THREAD

**Issue by nandi95** [vuejs/vue-test-utils-next#753]
I see most PRs titled in accordance with [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/)
To ensure consistency perhaps a hook can be added (`commit-msg`) to validate with commitlint following the angular or the conventional config or some custom config. Furthermore a gh action can be added to validate commits on gh side too.

This is pretty simple to set up and has the added benefit of being a step towards automated changelog generation and versioning.
I can set it up if deciding to go forward with it.

**Comment by cexbrayat** [comment]
I think that would be great 👍

**Comment by nandi95** [comment]
Duplicate of #383
