### ISSUE TITLE
QUESTION: Is there any way to override composition API `setup` data?

### ISSUE THREAD

**Issue by luucasrb** [vuejs/vue-test-utils-next#761]
The [documentation](https://next.vue-test-utils.vuejs.org/api/#setdata) says:
```
notice that setData does not modify composition API setup() data.
```

Also I've tried `global.provide`, but it only works for `provide/inject` methods. 

So, the goal here is to wrap some variables declared in the `setup()` component function (probably inside `Mount` or `shallowMount` methods) so I can test it isolated.

Appreciate any help!

**Comment by cexbrayat** [comment]
Hi @luucasrb 

There is currently no such thing in the API. Do you have a specific use case in mind? Maybe we can give you some tips based on how we test such things in our projects.

**Comment by luucasrb** [comment]
Hi @cexbrayat,

Example:

`Component.vue`

```
<template>
  <ChildComponent :class="exampleValue" />
</template>

<script>
import externalValue from '../anywhere';

export default {
  setup() {
    const exampleValue = externalValues; // some proccessing may come here

    return { 
      exampleValue;
    }
  }
}
</script>
```

So, I would like to mount the Component for testing, but using some random `exampleValue` instead of using the imported one.

Thanks.

**Comment by cexbrayat** [comment]
👍 The way I test this kind of thing in my apps is to rely on `jest.mock` https://jestjs.io/docs/mock-functions#mocking-modules, and override `externalValue` with `random-value`.

Something like:

```ts
jest.mock('../anywhere', () => 'random-value');
const ComponentWrapper = mount(Component);
expect(ComponentWrapper.vm.exampleValue).toContain('random-value');
```

This is super flexible and should cover most cases you'll encounter.
I'm going to close the issue for now. Feel free to reopen if you encounter another use case.
