### ISSUE TITLE
`setData` wrongly deep-merges

### ISSUE THREAD

**Issue by eunjae-lee** [vuejs/vue-test-utils-next#766]
`setData` wrongly deep-merges.

```js
const Comp = {
  template: `
    <div>{{state.items.join(",")}}</div>
  `,
  data() {
    return {
      state: {
        items: ['1'],
      },
    };
  },
};

it('works in an object form', async () => {
  const wrapper = mount(Comp);
  expect(wrapper.html()).toMatchInlineSnapshot(`<div>1</div>`);

  await wrapper.setData({ state: { items: ['2', '3'] } });
  expect(wrapper.html()).toMatchInlineSnapshot(`<div>2,3</div>`);
});
```

The second `expect` clause is supposed to pass, but it isn't. The actual result is `<div>1,2,3</div>`.

[The implementation of setData](https://github.com/vuejs/vue-test-utils-next/blob/52b3777310dc8037a860805e79f2b75061aec8d9/src/vueWrapper.ts#L238-L241) seems to concat all the items in the array.

## reproduction
https://github.com/eunjae-lee/vtu-set-data

```
git clone git@github.com:eunjae-lee/vtu-set-data.git
cd vtu-set-data
yarn install
yarn test
```

↑ [the test](https://github.com/eunjae-lee/vtu-set-data/blob/main/tests/unit/example.spec.ts) fails

**Comment by cexbrayat** [comment]
Thanks @eunjae-lee for opening this issue and for providing a reproduction 👍

@afontcu I think you implemented `setData` in fc49c0249af3e70e22ed12d3b0a50a284bc39d24 and it looks like arrays are indeed concatenated. Was that on purpose ou should we fix it?

**Comment by eunjae-lee** [comment]
Hello @cexbrayat,
I already opened the PR but feel free to close it if that implementation was intended.
However I think we'd better fix this, because 

`setData({ items: [1, 2, 3] });` is normally to mimic

`this.items = [1, 2, 3]` in real life. We don't normally concat it.

**Comment by cexbrayat** [comment]
I agree with you. Let's wait for Adriá's answer, but your PR LGTM 👍

**Comment by afontcu** [comment]
Hi! We simply ported SO's solution and I guess at that point we thought concatenating arrays was good enough. But yeah, I see your point and I'd expect `setData({ items: [1,2] })` to only return two elements, not one. I'll go ahead and approve&merge your PR :)

Thank you for taking the time to submit a detailed report, a simple reproduction snippet and the PR fixing the issue! ❤️
