### ISSUE TITLE
Spying on methods when using the composition api

### ISSUE THREAD

**Issue by maurer2** [vuejs/vue-test-utils-next#775]
Hello, it seems that when using the options api, it is recommended to create spies for methods before mounting to avoid issues with event handlers that don't have braces [(example 1](https://stackoverflow.com/a/62703070/1870482), [example 2](https://github.com/vuejs/vue-test-utils/issues/929#issuecomment-653500987), [example 3](https://stackoverflow.com/a/61859759/1870482)).
How would one do the same with the composition api? The following doesn't work, as methods isn't available/exposed when using the composition api?

```
const spy = jest.spyOn(ComponentName.methods, 'methodName');
// mount stuff
expect(spy).toHaveBeenCalled()
```
Thanks

Cheers

**Comment by cexbrayat** [comment]
I think you should be able to do something like:
```ts
const wrapper = mount(ComponentName);
const spy = (wrapper.vm.methodName = jest.fn());
await wrapper.get('button').trigger('click');
expect(spy).toHaveBeenCalled();
```

Feel free to reopen this issue with a concrete example if that doesn't work, but I think I've used this pattern several times with success.

**Comment by maurer2** [comment]
Hello, thanks for looking into this. I created an example project with tests to demonstrate the issue (https://github.com/maurer2/vue3-testing-question). I have two two buttons that have click event handlers. One with parentheses and one without.

```vue
 <ButtonComponent
      id="button-2a"
      @click="handleClick1"
/>
    
<ButtonComponent
      id="button-2b"
      @click="handleClick2()"
/>
```

The second click handler can be tested like so:

```ts
  it('button2 triggers counter update function when clicked', async () => {
    const spy = jest.spyOn(cmp.vm, 'handleClick2');

    await cmp.find('#button-2b').trigger('click');
    expect(spy).toHaveBeenCalled();
  });
```

This doesn't work for the first one as the following test fails:

```ts
it('button1 triggers counter update function when clicked - spied on the fly', async () => {
    const spy = jest.spyOn(cmp.vm, 'handleClick1');

    await cmp.find('#button-2a').trigger('click');
    expect(spy).toHaveBeenCalled();
  });
```

This seems to only work when performing the spying before mounting the component like so:
```ts
let cmp: any
 let spyHandleClick1: any;

 beforeEach(() => {
    spyHandleClick1 = jest.spyOn((ComponentOptionsAPI.methods as any), 'handleClick1');
    cmp = shallowMount(ComponentOptionsAPI, {});
  });

 it('button1 triggers counter update function when clicked - spied before mount', async () => {
    await cmp.find('#button-2a').trigger('click');

    expect(spyHandleClick1).toHaveBeenCalled();
  });
```
Unfortunately `ComponentName.method` doesn't seem to be available for components that are written using the composition api, so this workaround doesn't work there. What would be the equivalent to get this working other than always using parentheses for event handlers?

Cheers

**Comment by cexbrayat** [comment]
Thanks for the use-case 👍

I sadly think we can't do much, as the generated code is fundamentally different between ` @click="handleClick1"` and ` @click="handleClick2()"`.
See [here](https://vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%20%40click%3D%5C%22handleClick1%5C%22%3EHello%20World!%3C%2Fdiv%3E%5Cn%5Cn%3Cdiv%20%40click%3D%5C%22handleClick2()%5C%22%3EHello%20World!%3C%2Fdiv%3E%22%2C%22ssr%22%3Afalse%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22filename%22%3A%22Foo.vue%22%2C%22prefixIdentifiers%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22inline%22%3Afalse%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22compatConfig%22%3A%7B%22MODE%22%3A3%7D%2C%22whitespace%22%3A%22condense%22%2C%22bindingMetadata%22%3A%7B%22TestComponent%22%3A%22setup-const%22%2C%22setupRef%22%3A%22setup-ref%22%2C%22setupConst%22%3A%22setup-const%22%2C%22setupLet%22%3A%22setup-let%22%2C%22setupMaybeRef%22%3A%22setup-maybe-ref%22%2C%22setupProp%22%3A%22props%22%2C%22vMySetupDir%22%3A%22setup-const%22%7D%2C%22optimizeImports%22%3Afalse%2C%22optimizeBindings%22%3Afalse%7D%7D)

Is it really a problem to have to use parens if you want to spy on the handler?

I'll reopen in the meantime, maybe @lmiller1990 or @afontcu will have an idea on how to handle this.

**Comment by maurer2** [comment]
Hello, thanks for reopening the issue. I guess it would make sense to always use parentheses when using the composition api and set `v-on-style` from eslint-plugin-vue (https://eslint.vuejs.org/rules/v-on-style.html) to always when using the composition api to avoid flaky tests. 

I got a somewhat related question regarding the lifecycle methods. If I wanted to check if a function is called on mount, I would do it like before:

```ts
let spyRunOnMount: any;

beforeEach(() => {
    spyRunOnMount = jest.spyOn((ComponentOptionsAPI.methods as any), 'runOnMount');

    mount stuff
  });

it('run runOnMount runs on mount', async () => {
    expect(spyRunOnMount).toHaveBeenCalled();
});
```

With the composition api I would need to return runOnMount function from setup to expose it in the test, but when I register the spy the lifecycle hook has already run and the test fails:

```ts
let spyRunOnMount: any;

beforeEach(() => {
    spyRunOnMount = jest.spyOn(cmp.vm, 'runOnMount');
    mount stuff
  });

it('runOnMount runs on mount', async () => {
    expect(spyRunOnMount).toHaveBeenCalled();
  });
```

Is there some way to test this or is just not possible with components that use the composition api?

Cheers

**Comment by cexbrayat** [comment]
In that case what I usually _really_ want to check is not that the method itself was called, but rather what it does or that an external dependency was properly called. For example, if I fetch some data on mount, I'll check that the composable that does the HTTP call was properly called:

```ts
const mockRaceService = {
  list: jest.fn()
};
jest.mock('@/composables/RaceService', () => ({
  useRaceService: () => mockRaceService
}));

describe('Races.vue', () => {
  test('should display every race', async () => {
    const wrapper = mount(Races);
    await flushPromises();
    expect(mockRaceService.list).toHaveBeenCalled();
```

I hope this helps. I don't think we'll be able to allow to spy on the method as you would expect, because the model is fundamentally different. Or maybe with some hacky method, but I'm not really sure that's worth the complexity... We've been using the composition API for more than a year, and we manage to test everything in our projects.

**Comment by maurer2** [comment]
Okay, makes sense. Thanks for explanation.

**Comment by cexbrayat** [comment]
You're welcome! If you don't mind, I'll close the issue for now, and we can revisit if some other use cases come up.

**Comment by tongvantruong** [comment]
It doesn't work on my side.

MyComponent.vue
```ts
<template>
  <div @click="methodA"> </div>
</template>

<script setup lang="ts">
const methodA = () => {
  console.log("methodA");
  methodB();
};

const methodB = () => {
  console.log("methodB");
};
</script>
```

MyComponent.spec.ts
```ts
import { mount } from "@vue/test-utils";
import MyComponent from "./MyComponent.vue";

it("a", () => {
  const wrapper = mount(MyComponent);
  const spy = jest.spyOn(wrapper.vm, "methodB");
  wrapper.vm.methodA();
  expect(spy).toHaveBeenCalled();
});
```

=> Error
```
 expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

       7 |   const spy = jest.spyOn(wrapper.vm, "methodB");
       8 |   wrapper.vm.methodA();
    >  9 |   expect(spy).toHaveBeenCalled();
         |               ^
      10 | });
```

**Comment by maurer2** [comment]
Hello, have you tried adding the parentheses to the event handlers? Vue permits both syntaxes, e.g.

```
<template>
  <div @click="methodA()"> </div>
</template>
```

If that doesn't fix the issue, you could turn it into a [hook/composable](https://github.com/vuejs/test-utils/issues/1718#issuecomment-1214212360).

**Comment by sureshvv** [comment]
Why is there no way to spy on a Composition API method before mount? I am having to go on a major refactoring spree to bypass this limitation. Please don't tell me it is for my own good :)

**Comment by lmiller1990** [comment]
This is a limitation for `<script setu>`, it is closed by default unless you do `defineExpose`.

I don't understand why you need a major refactoring spree - can you elaborate? If you are only refactoring and you need to make make changes to your test code, that's probably a good indication you are testing implementation details (like spying on a specific method).

**Comment by sureshvv** [comment]
I have a component method A that calls another method B only when certain conditions are met.

I want to test that by spyOn B.

Does not work.

**Comment by lmiller1990** [comment]
What is the effect of calling `sub1`? I'd recommend asserting against that. If you do `defineExpose` are you able to spy on it?

**Comment by sureshvv** [comment]
Let me try defineExpose. Have not used it before.

**Comment by cexbrayat** [comment]
defineExpose should not change anything, as Vue Test Utils bypasses it to make tests simpler. If it does, please open an issue.

If you already mock the database, then the easiest way to test if everything work is to assert that your mocked database is properly called instead of sub1.

See my comment above https://github.com/vuejs/test-utils/issues/775#issuecomment-883189164
