### ISSUE TITLE
Wrong config property name for `renderDefaultStubSlot` into migration guide

### ISSUE THREAD

**Issue by IlCallo** [vuejs/vue-test-utils-next#787]
Package types and API mention `renderStubDefaultSlot`, while migration guide uses `renderDefaultStubSlot`.
https://next.vue-test-utils.vuejs.org/migration/#shallowmount-and-renderdefaultstubslot

Possibly a rename which has not been propagated

**Comment by cexbrayat** [comment]
Indeed, good catch 👍

Would you like to open a PR to fix it? It should be fairly straightforward.

**Comment by DominicGBauer** [comment]
@cexbrayat https://github.com/vuejs/vue-test-utils-next/pull/789
