### ISSUE TITLE
there is no types directory here

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [vuejs/vue-test-utils-next#799]
![image](https://user-images.githubusercontent.com/26108004/127272979-cedd428b-f74f-4c2d-adf2-c9548a42754a.png)

**Comment by cexbrayat** [comment]
I confirm there is a regression with the release rc.11

As a workaround, please use version `2.0.0-rc.10` for now.

**Comment by cexbrayat** [comment]
The culprit commit is https://github.com/vuejs/vue-test-utils-next/commit/85c2b1bb0453deab10bbe55199a7956509e6e6d7

By adding `types/compat.ts` it somehow broke the release. Removing this file seems to fix the package. It should have broken rc.10 as well though 🤔

**Comment by cexbrayat** [comment]
We released rc.12 which should fix the issue

**Comment by lmiller1990** [comment]
I want to find out what changed that made the `dist` directory 1) not include the types and 2) include all of `src`. Very weird. Neither `rollup.config.js` or `tsconfig.json` has changed in quite some time. Will do some more `git bisect` later on.

**Comment by cexbrayat** [comment]
@lmiller In my opinion, the commit adding compat is the root cause. We missed it in rc.10 probably because the types were still in the dist directory when the release was cut (it happened to me as well). `src` got shipped in rc.12 for the same reason probably, as if you run:
```
yarn
rm -rf dist
yarn build
ls -la dist
```
there is no `src` inside `dist`.

**Comment by lmiller1990** [comment]
Right, that would make sense.

Either way, things are working for now! We should add some tests to verify the types in `dist` are build correctly.
