### ISSUE TITLE
wrapper.emitted() in composition API do not show context.emit events like documentation say.

### ISSUE THREAD

**Issue by Davidpsj** [vuejs/vue-test-utils-next#809]
I was trying to test events emitted inside a method in setup function when a click button is triggered. The click event was catch by wrapper like expected, but the another event emitted inside the method listened by the click wasn't.

My code for example:
![Captura de Tela 2021-07-29 às 17 38 43](https://user-images.githubusercontent.com/338538/127562543-b350b814-522a-448e-aaf9-25b6a8abef2c.png)

The console.log show only click event:
![Captura de Tela 2021-07-29 às 17 39 42](https://user-images.githubusercontent.com/338538/127562672-c228705a-3df1-48d9-af88-6ba836e0598e.png)

Am I doing something wrong? Or it is an unexpected behavior?

I'm so sorry for use images, the code pasted do not showed like I expected.

Best regards.

**Comment by freakzlike** [comment]
The wrapper represent your "Component" Component and not your "Child" Component. So with `wrapper.emitted('search')` you receive the events that "Component" emitted and not "Child".

If I am not wrong you can do something like:
```
const childWrapper = wrapper.findComponent(Child)
expect(childWrapper.emitted('search')).toHaveLength(1)
```

I would test "Child" in an extra unit test, where i can check for the emitted event.
If you want to test in compination with "Component". Than it would be better to check the result of the event.
So for example:
```js
expect(wrapper.find('span').text()).toBe('Teste')
```

**Comment by Davidpsj** [comment]
Hi!

Thanks for your reply! I found other mistake that I was doing. The method in Child that I invoke was mocked with jest.fn() causing the expected event not triggering.

After changing this wrong implementations all tests passed.

Thanks.
