### ISSUE TITLE
The proper way to handle SVG

### ISSUE THREAD

**Issue by standbyoneself** [vuejs/vue-test-utils-next#814]
How should I stub/handle/precompile SVG using Vue 3 + VTU@Next + Jest?

Reproduction repository: https://github.com/standbyoneself/ws-test-client

The simple test:

```js
import User from '@/components/User.vue';
import { shallowMount } from '@vue/test-utils';

describe('User.vue', () => {
  it('should do something', () => {
    const wrapper = shallowMount(User);

    console.log(wrapper.html());
  });
});
```

For the simple component:

```js
<template>
  <div class="user">
    <img class="user__avatar" :src="user.avatar_url" />
    <animated-anchor
      :text="user.login"
      :href="user.html_url"
      class="user__name"
    /><br />
    <img :src="logoutIcon" class="user__logout" @click="logout()" />
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from '@vue/runtime-core';
import { GithubUser } from '@/types';
import AnimatedAnchor from './AnimatedAnchor.vue';
import logoutIcon from '@/assets/icons/logout.svg';
import { useRouter } from 'vue-router';
import githubService from '@/services/GithubService';

export default defineComponent({
  components: { AnimatedAnchor },
  name: 'User',
  props: {
    user: {
      type: Object as PropType<GithubUser>,
      required: true,
    },
  },
  setup() {
    const router = useRouter();

    const logout = () => {
      githubService.logout();
      router.push({ name: 'Auth' });
    };

    return { logoutIcon, logout };
  },
});
</script>
```

Causes the error:
FAIL  __tests__/unit/components/User.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token
Details:

    /Users/vishnevsky/Desktop/Projects/github.com/ws-test-client/src/assets/icons/logout.svg:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){<?xml version="1.0" encoding="iso-8859-1"?>
                                                                                      ^

    SyntaxError: Unexpected token '<'

      15 | import { GithubUser } from '@/types';
      16 | import AnimatedAnchor from './AnimatedAnchor.vue';
    > 17 | import logoutIcon from '@/assets/icons/logout.svg';
         | ^
      18 | import { useRouter } from 'vue-router';
      19 | import githubService from '@/services/GithubService';
      20 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (src/components/User.vue:17:1)

Have tried `identity-obj-proxy` and `svgTransform.js` like from vue-svg-loader instruction, but it seems to me they worked only with the previous version of Vue, and these instructions deprecated now

**Comment by LinusBorg** [comment]
> Have tried identity-obj-proxy and svgTransform.js like from vue-svg-loader instruction, but it seems to me they worked only with the previous version of Vue, and these instructions deprecated now

vue.svg-loader turns SVGs into Vue components. That's not what your app code is doing, though - it just gives you a string - a path to the svg file, which you then can put into an img's `src`.

So what you have to do it to tell jest: "when you encounter an svg import, just give me a string."

See also: https://jestjs.io/docs/webpack#handling-static-assets

```js
{
  moduleNameMapper: {
      '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/__mocks__/fileMock.js',
    }
}
```
```js
// __mocks__fileMock.js
module.exports = 'test-file-stub';
```

**Comment by standbyoneself** [comment]
It's clear now, thanks
