### ISSUE TITLE
how to trigger change event with files ?

### ISSUE THREAD

**Issue by kev1nzh37** [vuejs/vue-test-utils-next#826]
l know `trigger('change')`, but not work.

like this: 
```javascript
  await input.trigger('change', {
    target: {
      files: [{ file: 'foo.png' }],
    },
  }
// you cannot set the target value of an event. See the notes section of the docs for more details—https://vue-test-utils.vuejs.org/api/wrapper/trigger.html
```

so l tried something else.

like this: 
```javascript
   const input = wrapper.find("input[type='file']")

    let file1 = new File(['xxxxxxxxx'], 'xxx.txt')
    let file2 = new File(['yyyyyyyyy'], 'yyy.txt')

    input.element.files = [file1, file2]

    await input.trigger('change' )
// TypeError: Failed to set the 'files' property on 'HTMLInputElement': The provided value is not of type 'FileList'.
```
how to solve the question? 
 
Versions:
`"@vue/test-utils": "^2.0.0-rc.9`,
`"vue": "^3.1.1`

**Comment by standbyoneself** [comment]
According to the [documentation](https://vue-test-utils.vuejs.org/api/wrapper/#trigger), you cannot override the `target` value of the event:

> It's not possible to edit the target value of an Event object, so you can't set target in the options object.
>
> To add an attribute to the target, you need to set the value of the Wrapper element before calling trigger. You can do this with the element property.

But you can try it:

Object.defineProperty(input.element, 'files', {
  value: [new File([], 'test-file')],
});

**Comment by kev1nzh37** [comment]
> 根据[文档](https://vue-test-utils.vuejs.org/api/wrapper/#trigger)，您不能覆盖`target`事件的值：
> 
> > 无法编辑 Event 对象的目标值，因此您无法在选项对象中设置目标。
> > 要向目标添加属性，您需要在调用触发器之前设置 Wrapper 元素的值。您可以使用 element 属性执行此操作。
> 
> 但是你可以试试：
> 
> Object.defineProperty(input.element, 'files', {
> value: [new File([], 'test-file')],
> });

谢谢，我已经解决了。
```typescript
const getMockFile = (element: Element, files: File[]): void => {
  Object.defineProperty(element, 'files', {
    get () {
      return files
    }
  })
}
```
