### ISSUE TITLE
Use codepen demos in docs?

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#85]
Vue 3 docs will use codepen, I believe, for the examples, so people can try it out. I wonder if this is something we could do, too, and if that would be a good idea.

**Comment by afontcu** [comment]
I was thinking about this the other day, too. Right now, the API page looks a bit too bloated given that we always need to provide a Component + a spec file (or more). 

However, I would wait until docs team agrees on a solution to display code snippets, and then stick to it. Until then, I'd say we keep writing code snippets using markdown blocks, which I think make porting them to other platforms quite easy.

**Comment by lmiller1990** [comment]
Sounds good to me. There is still be too much going on atm on the API page... maybe we can find a cleaner way. Either way, maybe this discussion should be in the docs repo.
