### ISSUE TITLE
Having problem when import `createLocalVue`

### ISSUE THREAD

**Issue by LYNN-CHEN** [vuejs/vue-test-utils-next#859]
I write
 `import { shallowMount, createLocalVue } from '@vue/test-utils';` 
in my *.spec.ts file, and when I run the test file with jest, it report the error that 
`Module '"@vue/test-utils"' has no exported member 'createLocalVue'`

My @vue/test-utils version is `^2.0.0-rc.12`, and my jest version is `^26.6.3`, and I am using vue3.

**Comment by afontcu** [comment]
Hi! 👋 

This is because Vue Test Utils 2 no longer needs a local Vue instance, so `localVue` is removed.

Here are the docs about the change: https://next.vue-test-utils.vuejs.org/migration/#no-more-createlocalvue


Hope it helps!
