### ISSUE TITLE
Update to latest Vue (3.2.x)

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#861]
I tried updating the deps to Vue 3.2.2, but get this error when running the tests.

```sh
 FAIL  tests/docs-examples/teleport.spec.ts
  ● Test suite failed to run

    src/stubs.ts:52:3 - error TS2590: Expression produces a union type that is too complex to represent.

     52   return defineComponent({
          ~~~~~~~~~~~~~~~~~~~~~~~~
     53     name: name || anonName,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...
     56     props: propsDeclaration || {}
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     57   })
        ~~~~
```

We should find out what's going on and fix it so we can update.

**Comment by TheDutchCoder** [comment]
This might be related, but when upgrading Vue, the following errors are thrown when running jest: `Cannot find module '@vue/compiler-dom' from 'node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js'`

The latest version of seems to remove the compiler-dom from the lock file and there was a release note about conflicting compiler/runtime: https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#compatibility-notes

**Comment by lmiller1990** [comment]
Interesting. I think I bumped all the versions (including `compiler-dom`) but I'll give it another go.

**Comment by TheDutchCoder** [comment]
> Interesting. I think I bumped all the versions (including `compiler-dom`) but I'll give it another go.

As soon as 3.2.4 hit, the errors were gone, so I think it might've been a Vue issue. Thinks work for me now!

**Comment by lmiller1990** [comment]
It's done now.
