### ISSUE TITLE
NPM @next Version Out of Date

### ISSUE THREAD

**Issue by TheSeg** [vuejs/vue-test-utils-next#863]
The `@next` version of this project is out of date. Currently listing RC 11, not RC12.

I noticed this as I was installed via `@vue/test-utils@next` when it installed RC 11 and it's related TypeScript issues.

<img width="883" alt="Screen Shot 2021-08-12 at 6 30 19 PM" src="https://user-images.githubusercontent.com/246508/129292244-5fbd433b-f927-49b0-8197-9becc1cde752.png">

**Comment by lmiller1990** [comment]
Oops - I will update the tag today.

**Comment by lmiller1990** [comment]
Done.
