### ISSUE TITLE
Example code for mocking HTTP requests appears to be broken - out of scope variable for jest.mock()

### ISSUE THREAD

**Issue by meanspa** [vuejs/vue-test-utils-next#868]
Ran into trouble trying to follow the documentation's instructions for mocking HTTP requests here - https://next.vue-test-utils.vuejs.org/guide/advanced/http-requests.html

**Steps to reproduce:** 
- Create Vue CLI project with Vue 3, babel, and jest unit testing options
- Create example component and example test from [this docs page](https://next.vue-test-utils.vuejs.org/guide/advanced/http-requests.html)
- Run the test, get this error: `babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.`

**Secondary wording suggestion:**
For me, I found this sentence confusing: "Our first goal is to test this component without actually reaching the API. This would create a fragile and potentially slow test." I wasn't sure what "this" referred to until I researched it later. One alternative that I would find clearer: "Our first goal is to test this component without actually reaching the API,  _because using an external API in a test_ would create a fragile and potentially slow test."

Thanks!

**Comment by standbyoneself** [comment]
The problem here is that when you use `jest.mock()`, it is hoisted by default, so you cannot reference `fakePostList` variable. In order to get this example work you may rewrite implementation of the `axios.get()` for the specific test:

```js
import { mount, flushPromises } from '@vue/test-utils'
import axios from 'axios'
import PostList from '../../src/components/PostList.vue'

const fakePostList = [
  { id: 1, title: 'title1' },
  { id: 2, title: 'title2' }
]

// Following lines tell Jest to mock any call to `axios.get`
// and to return `fakePostList` instead
jest.mock('axios', () => ({
  get: jest.fn()
}))

test('loads posts on button click', async () => {
  jest.spyOn(axios, 'get').mockImplementation(() => fakePostList)

  const wrapper = mount(PostList)

  await wrapper.get('button').trigger('click')

  // Let's assert that we've called axios.get the right amount of times and
  // with the right parameters.
  expect(axios.get).toHaveBeenCalledTimes(1)
  expect(axios.get).toHaveBeenCalledWith('/api/posts')

  // Wait until the DOM updates.
  await flushPromises()

  // Finally, we make sure we've rendered the content from the API.
  const posts = wrapper.findAll('[data-test="post"]')

  expect(posts).toHaveLength(2)
  expect(posts[0].text()).toContain('title1')
  expect(posts[1].text()).toContain('title2')
})
```

**Comment by meanspa** [comment]
@standbyoneself That does the trick for my use case, thanks! Do you know if the docs could be updated as well to reflect this?
