### ISSUE TITLE
Lack of 'parentComponent' functionality

### ISSUE THREAD

**Issue by Akulko** [vuejs/vue-test-utils-next#883]
Hello, I have found that at the moment it's not possible to use the parentComponent functionality to set a parent component or root, I have not found any entries in the codebase. {mocks: {$root}} and none of the other options I found in the documentation or issues for vue-test-utils v1.x doesn't work. Can you tell me if there's another way to use the add parent element functionality or is it just planned?

**Comment by xanf** [comment]
@Akulko Theoretically, if you are in heavy need, you can always create wrapper around `mount` which will provide your functionality by creating own component, and doing find. Something like (pseudo-code):
```js
function mountWithParent(ChildComponent, { parentComponent: ParentComponent, ...mountOptions }) {
  const wrapperComponent = {
     inheritAttrs: false,
     components: { ParentComponent, ChildComponent },
     template: '<ParentComponent><ChildComponent v-bind="$props" /></ParentComponent>'
  }
  
  const wrapper = mount(wrapperComponent, mountOptions);
  return wrapper.findComponent(ChildComponent);
}
// ...
mountWithParent(Child, { ..., parentComponent: Map });
```
 (please take a note that proper implementation might also require passing slots to ChildComponent to work for all cases)

**Comment by Akulko** [comment]
Ok, thank you so much!

**Comment by marr** [comment]
@matthew-dean did you ever figure this out? I am trying to emulate a `parentComponent` with my test wrapper. Since I'm testing lots of components that use vuetify, I wanted to wrap everything with a `v-app` component. I made a wrapper function like so:
```js
import {
  mount as vtuMount,
  shallowMount as vtuShallowMount,
} from '@vue/test-utils';

export function mount(Component, opts = {}) {
  const wrapper = {
    name: 'Wrapper',
    components: { Component },
    inheritAttrs: false,
    template: '<v-app><Component v-bind="$props" /></v-app>',
  };
  return vtuMount(wrapper, makeOptions(opts)).findComponent(Component);
}
```
but when I try to render a component, the props arent rendered:
```js
mount({
  template: '<span>{{ msg }}</span>',
  props: ['msg'],
  data() {
    return {
      foo: true,
    };
  },
})
```
simply returns `<span></span>`
