### ISSUE TITLE
Strange provide/inject related regression in rc13

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-test-utils-next#900]
The following test no longer works in rc13 but works fine in rc12. It looks like the prop change is never detected and it's the only test in our entire project that fails on it.

The component has a slot and provides its own props to the children, which then respond to changes (like the `icon` prop).

My best guess is that something with provide/inject no longer works in the test utils and/or that there's some sort of caching/stubbing going on in slots.

```ts
  describe('props', () => {
    it('renders both default and custom icons', async () => {
      expect(wrapper.findAllComponents(ClIcon)).toHaveLength(1)
      expect(wrapper.findComponent(ClIcon).props('icon')).toBe('ChevronRightIcon')

      await wrapper.setProps({ icon: 'ActivityIcon' })

      expect(wrapper.findAllComponents(ClIcon)).toHaveLength(1)
      expect(wrapper.findComponent(ClIcon).props('icon')).toBe('ActivityIcon')
    })
  })
```

Jest Output:
```
    expect(received).toBe(expected) // Object.is equality

    Expected: "ActivityIcon"
    Received: "ChevronRightIcon"

      47 |
      48 |       expect(wrapper.findAllComponents(ClIcon)).toHaveLength(1)
    > 49 |       expect(wrapper.findComponent(ClIcon).props('icon')).toBe('ActivityIcon')
         |                                                           ^
      50 |     })
      51 |   })
      52 |

      at src/components/navigation/breadcrumb/__tests__/breadcrumb.spec.ts:49:59
      at fulfilled (src/components/navigation/breadcrumb/__tests__/breadcrumb.spec.ts:5:58)
```

The tested component:
```
<template>
  <div
    :class="classes.root"
    data-breadcrumb-root
  >
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType, computed, ref, provide } from 'vue'

import type { Ref } from 'vue'
import type { Breadcrumb } from './types'
import type { Icons } from '../../typography/icon/types'

export default defineComponent({
  name: 'ClBreadcrumb',

  props: {
    icon: {
      type: String as PropType<Icons>,
      default: 'ChevronRightIcon',
    },
  },

  setup (props) {
    const breadcrumbs: Ref<Breadcrumb[]> = ref([])

    provide('ClBreadcrumb', { props, breadcrumbs })

    const classes = computed(() => {
      return {
        root: [
          'flex text-gray-700 text-sm',
        ],
      }
    })

    return {
      classes,
      breadcrumbs,
    }
  },
})
</script>
```

The child component that lives in the slot:
```
<template>
  <div
    :class="classes.root"
    data-breadcrumb-item-root
  >
    <slot />

    <cl-icon
      v-if="!isLast"
      data-breadcrumb-item-icon
      :class="classes.icon"
      :icon="icon"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, inject, ref, getCurrentInstance, onBeforeUnmount } from 'vue'

import ClIcon from '#components/typography/icon'

import type { InjectKey } from './types'

export default defineComponent({
  name: 'ClBreadcrumbItem',

  components: {
    ClIcon,
  },

  setup () {
    const parent = inject('ClBreadcrumb') as InjectKey
    const index = ref(-1)
    const currentInstance = getCurrentInstance()

    onBeforeUnmount(() => {
      /* istanbul ignore next */
      parent.breadcrumbs.value = parent.breadcrumbs.value.filter(instance => instance.uid !== currentInstance?.uid)
    })

    const isLast = computed(() => {
      /* istanbul ignore next */
      return parent.breadcrumbs.value[parent.breadcrumbs.value.length - 1]?.uid === currentInstance?.uid
    })

    const setIndex = (val: number) => {
      /* istanbul ignore next */
      index.value = val
    }

    parent.breadcrumbs.value = [...parent.breadcrumbs.value, {
      setIndex,
      uid: currentInstance?.uid,
    }]

    const classes = computed(() => {
      return {
        root: [
          'flex items-center',
          isLast.value ? 'font-bold text-black-700' : 'text-secondary-700',
        ],
        icon: [
          'text-black-400 mx-2',
        ],
      }
    })

    return {
      classes,
      isLast,
      parent,
      icon: parent.props.icon,
    }
  },
})
</script>
```

**Comment by lmiller1990** [comment]
I tried reproducing in this repo but I couldn't - there isn't enough information. What's `type Breadcrumb`? How are you mounting the component (I don't see `mount(...)` anywhere).

Can you include all the information to reproduce the issue? Or, ideally, fork this repro and add your reproduction? Thanks!

**Comment by TheDutchCoder** [comment]
Let me try to make a reproducible example on StackBlitz, otherwise I can provide all the files.

**Comment by TheDutchCoder** [comment]
This might be a Vue bug, as I actually can see the parent prop change, but the template doesn't update at all: https://stackblitz.com/edit/vue3-flickity-ts-ab4jme?file=src%2Fcomponents%2Fbreadcrumb%2Fbreadcrumb-item.vue

**Comment by TheDutchCoder** [comment]
Okay, apparently the component didn't properly work, but the tests passed.
The provided parent prop wasn't reactive, yet in VTU it _did_ update when changing the prop.

Does VTU, under the hood, to some stubbing of child components in the mount?

I think it created a reactive side-effect that's not actually compatible with what happens in the real situation?

**Comment by LinusBorg** [comment]
> Okay, apparently the component didn't properly work, but the tests passed.
> The provided parent prop wasn't reactive, yet in VTU it did update when changing the prop.

The test case you showed above did fail though?

**Comment by TheDutchCoder** [comment]
No it only fails on rc13, not on any of the previous versions.

**Comment by lmiller1990** [comment]
Is there some way to get the actual code so I can run it on my computer? I cannot find a "clone repo" or similar button in StackBlitz.

**Comment by TheDutchCoder** [comment]
> Is there some way to get the actual code so I can run it on my computer? I cannot find a "clone repo" or similar button in StackBlitz.

Not really :(

It's our company's repo and it's not OSS. Furthermore, the icon itself comes from our own library and is not a component in the tested environment.

If you want you can close the issue. There definitely _was_ something wrong, but seeing as the bug has now disappeared it might not be super relevant anymore (other than understanding why it was actually broken before).

My gut feeling is something along the lines of stubbed children or something, but we always use `mount`, which shouldn't stub children, but who knows.

Sorry I can't be of more help :(

**Comment by lmiller1990** [comment]
Is this still a bug as of rc.17?

**Comment by TheDutchCoder** [comment]
> Is this still a bug as of rc.17?

I will have to go back and install the version that made the test brea and then install rc17.
I'll report back with my findings.

If the issue is still there in the old release, we might be able to diff the two versions and see if that gives us an indication, but I also don't want to make this a time-sink for an issue that seems to have resolved itself anyway ;)
