### ISSUE TITLE
createErrorWrapper function is not exported

### ISSUE THREAD

**Issue by Ricky-rick** [vuejs/vue-test-utils-next#923]
I tried to create a plugin like the data-test-id-plugin example on https://next.vue-test-utils.vuejs.org/guide/extending-vtu/plugins.html#data-test-id-plugin but the createErrorWrapper function is not exported bij @vue/test-utils.

**Comment by lmiller1990** [comment]
Let's expose it. Can you make a PR exporting it from `src/index.ts`?
