### ISSUE TITLE
Build fail due to wrong import in domWrapper.ts

### ISSUE THREAD

**Issue by alfeg** [vuejs/vue-test-utils-next#936]
There is seems to be an error that causes our build to fail after library update to v2.0.0-rc.14
https://github.com/vuejs/vue-test-utils-next/blob/df6c234d2511f500be996620118c99625a86e165/src/domWrapper.ts#L8

I guess proper line should be:
```typescript
import { VueWrapper } from '.';
```
As there is no `src` fodler in npm package:
![image](https://user-images.githubusercontent.com/118516/132848036-43db0833-d8dd-4666-9467-3e9669ecf5cf.png)

**Comment by cexbrayat** [comment]
I see you're preparing a PR 👍

You can use `skipLibCheck: true` in the meantime in your projects (it will be faster to compile, and it will skip the libraries compilation, which is usually useless).

**Comment by alfeg** [comment]
@cexbrayat I've prepared PR and forgot to press create pull request =)

Thanks for workaround!

**Comment by designervoid** [comment]
@cexbrayat 
maybe this is good as a temporary solution, but why not use relative imports with dot or two dots (`.`, `..`)
`2.0.0-rc.18` version
![image](https://user-images.githubusercontent.com/43455658/147373211-afe14fbe-f9b1-4afc-ae09-650aae2dd546.png)

**Comment by designervoid** [comment]
with `skipLibCheck: false`:
![image](https://user-images.githubusercontent.com/43455658/147373227-8a2243b7-c48a-459a-b945-840bcfcffafd.png)

**Comment by designervoid** [comment]
with `skipLibCheck: false` and relative imports:
![image](https://user-images.githubusercontent.com/43455658/147373238-0f829139-a4da-4cc3-8a5c-1c07e9e080c5.png)
🥳

**Comment by cexbrayat** [comment]
Sure, if that fixes an issue, feel free to open a PR, and we'll gladly merge it!

**Comment by designervoid** [comment]
@cexbrayat mentioned this PR

**Comment by catrope** [comment]
This is broken again in 2.0.0-rc.19, because #1180 added more broken imports, but #1184 was submitted before #1180 was merged.

```
../../node_modules/@vue/test-utils/dist/interfaces/wrapperLike.d.ts:1:42 - error TS2307: Cannot find module 'src/constants/dom-events' or its corresponding type declarations.

1 import { DomEventNameWithModifier } from 'src/constants/dom-events';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@vue/test-utils/dist/interfaces/wrapperLike.d.ts:2:32 - error TS2307: Cannot find module 'src/createDomEvent' or its corresponding type declarations.

2 import { TriggerOptions } from 'src/createDomEvent';

```
