### ISSUE TITLE
doc: wrapper.findAllComponents and wrapper.getComponent accept querySelector in docs

### ISSUE THREAD

**Issue by PotatoesFall** [vuejs/vue-test-utils-next#989]
https://github.com/vuejs/vue-test-utils-next/blob/master/docs/api/index.md?plain=1#L1187
https://github.com/vuejs/vue-test-utils-next/blob/master/docs/api/index.md?plain=1#L1284

However this syntax doesn't seem to actually be allowed. Is the desired behavior to also accept querySelector i.e. strings? or is the documentation out of date? What is the correct way to find a component with a querySelector?

**Comment by xanf** [comment]
Hi, @PotatoesFall, thank you for reporting that

We've had some discussion in #904 and are going to re-instantiate an ability to find component with CSS selector. I'll close this one in favor of that issue
